/**
 * ============================================================================
 * BUILD OFFICIAL PDF CONTEXT
 * ============================================================================
 * 
 * Unified context builder for ALL PDF generation across all modules
 * (Logistics, Finance, HR, Projects, Donor CRM, MEAL, etc.)
 * 
 * Combines:
 * ✅ Organization context (org/OU/branding)
 * ✅ Language & direction (EN/AR with RTL/LTR)
 * ✅ Common footer (organization, OU, date, page numbers)
 * ✅ Common metadata (generatedBy, generatedAt, documentId)
 * ✅ User context (who generated, when)
 * ✅ Styling & colors (branding)
 * 
 * USAGE:
 * ```typescript
 * const officialContext = await buildOfficialPdfContext({
 *   db,
 *   organizationId: ctx.scope.organizationId,
 *   operatingUnitId: ctx.scope.operatingUnitId,
 *   userId: ctx.user.id,
 *   language: 'en',
 *   documentType: 'purchase_request',
 *   documentId: 660007,
 * });
 * 
 * // Now use in PDF data:
 * const pdfData = {
 *   ...officialContext,
 *   // Add only module-specific fields
 *   prNumber: pr.prNumber,
 *   lineItems: [...],
 * };
 * ```
 * 
 * BENEFITS:
 * ✅ Ultra-clean module code (no boilerplate)
 * ✅ Consistent PDF styling across all modules
 * ✅ Automatic RTL/LTR and bilingual support
 * ✅ Built-in metadata tracking
 * ✅ Single source of truth for PDF context
 * ✅ Easy to extend with new fields
 * 
 * ============================================================================
 */

import { eq } from 'drizzle-orm';
import { users } from 'drizzle/schema';
import { TRPCError } from '@trpc/server';
import { PdfOrganizationContext, getPdfOrganizationContext } from './getPdfOrganizationContext';

/**
 * Official PDF Context - Complete context for all PDF generation
 */
export interface OfficialPdfContext extends PdfOrganizationContext {
  // ========== LANGUAGE & DIRECTION ==========
  language: 'en' | 'ar';
  direction: 'ltr' | 'rtl';
  isArabic: boolean;
  isRTL: boolean;

  // ========== USER CONTEXT ==========
  generatedBy: string; // User name who generated the PDF
  generatedByEmail: string;
  generatedAt: string; // ISO timestamp
  generatedAtFormatted: string; // Formatted date for display

  // ========== DOCUMENT METADATA ==========
  documentType: string; // 'purchase_request', 'bid_opening_minutes', etc.
  documentId: number;
  documentModule: string; // 'Logistics', 'Finance', 'HR', etc.

  // ========== FOOTER CONTEXT ==========
  footerOrganizationName: string;
  footerOperatingUnitName: string;
  footerText: string;
  footerDate: string;
  footerGeneratedBy: string;

  // ========== STYLING & COLORS ==========
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  textColor: string;
  borderColor: string;
  backgroundColor: string;
  headerBackgroundColor: string;
  footerBackgroundColor: string;

  // ========== COMMON LABELS (BILINGUAL) ==========
  labels: {
    page: string; // 'Page' or 'صفحة'
    of: string; // 'of' or 'من'
    generatedBy: string; // 'Generated By' or 'تم الإنشاء بواسطة'
    generatedAt: string; // 'Generated At' or 'تم الإنشاء في'
    date: string; // 'Date' or 'التاريخ'
    organization: string; // 'Organization' or 'المنظمة'
    operatingUnit: string; // 'Operating Unit' or 'وحدة التشغيل'
    confidential: string; // 'Confidential' or 'سري'
    official: string; // 'Official Document' or 'وثيقة رسمية'
  };

  // ========== UTILITIES ==========
  textAlign: 'left' | 'right'; // Based on language
  alignClass: string; // 'text-left' or 'text-right'
  alignOpposite: 'left' | 'right'; // Opposite of textAlign
  marginStart: string; // 'ml' or 'mr' based on direction
  marginEnd: string; // 'mr' or 'ml' based on direction
  paddingStart: string; // 'pl' or 'pr' based on direction
  paddingEnd: string; // 'pr' or 'pl' based on direction
}

/**
 * Configuration for building official PDF context
 */
export interface BuildOfficialPdfContextConfig {
  db: any;
  organizationId: number;
  operatingUnitId: number;
  userId: number;
  language: 'en' | 'ar';
  documentType: string;
  documentId: number;
  documentModule?: string;
}

/**
 * Build complete official PDF context
 * 
 * @param config - Configuration object
 * @returns Complete official PDF context ready for use in any PDF generator
 * 
 * @throws TRPCError if organization, operating unit, or user not found
 */
export async function buildOfficialPdfContext(
  config: BuildOfficialPdfContextConfig
): Promise<OfficialPdfContext> {
  const {
    db,
    organizationId,
    operatingUnitId,
    userId,
    language,
    documentType,
    documentId,
    documentModule = 'General',
  } = config;

  console.log(
    `[Official PDF Context] Building context: module=${documentModule}, type=${documentType}, lang=${language}`
  );

  // ========== STEP 1: Get organization context ==========
  const orgContext = await getPdfOrganizationContext(db, organizationId, operatingUnitId);

  // ========== STEP 2: Get user information ==========
  const user = await db.query.users.findMany({
    where: eq(users.id, userId),
  });

  if (!user) {
    throw new TRPCError({
      code: 'NOT_FOUND',
      message: `User not found: ID=${userId}`,
    });
  }

  console.log(`[Official PDF Context] ✅ User found: ${user.name || user.email}`);

  // ========== STEP 3: Build language-specific labels ==========
  const labels = buildPdfLabels(language);

  // ========== STEP 4: Build styling context ==========
  const styling = buildPdfStyling(orgContext, language);

  // ========== STEP 5: Build utility classes ==========
  const utilities = buildPdfUtilities(language);

  // ========== STEP 6: Format timestamps ==========
  const now = new Date();
  const generatedAt = now.toISOString();
  const generatedAtFormatted = formatDateForPdf(now, language);

  // ========== STEP 7: Build footer context ==========
  const footerContext = buildFooterContext(orgContext, user, now, language);

  // ========== BUILD COMPLETE CONTEXT ==========
  const context: OfficialPdfContext = {
    // Spread organization context
    ...orgContext,

    // Language & Direction
    language,
    direction: language === 'ar' ? 'rtl' : 'ltr',
    isArabic: language === 'ar',
    isRTL: language === 'ar',

    // User Context
    generatedBy: user.name || user.email || 'Unknown User',
    generatedByEmail: user.email || '',
    generatedAt,
    generatedAtFormatted,

    // Document Metadata
    documentType,
    documentId,
    documentModule,

    // Footer Context
    ...footerContext,

    // Styling & Colors
    ...styling,

    // Labels
    labels,

    // Utilities
    ...utilities,
  };

  console.log(`[Official PDF Context] ✅ Official PDF context ready`);

  return context;
}

/**
 * Build bilingual labels for PDF
 */
function buildPdfLabels(language: 'en' | 'ar'): OfficialPdfContext['labels'] {
  if (language === 'ar') {
    return {
      page: 'صفحة',
      of: 'من',
      generatedBy: 'تم الإنشاء بواسطة',
      generatedAt: 'تم الإنشاء في',
      date: 'التاريخ',
      organization: 'المنظمة',
      operatingUnit: 'وحدة التشغيل',
      confidential: 'سري',
      official: 'وثيقة رسمية',
    };
  }

  return {
    page: 'Page',
    of: 'of',
    generatedBy: 'Generated By',
    generatedAt: 'Generated At',
    date: 'Date',
    organization: 'Organization',
    operatingUnit: 'Operating Unit',
    confidential: 'Confidential',
    official: 'Official Document',
  };
}

/**
 * Build styling context from branding
 */
function buildPdfStyling(
  orgContext: PdfOrganizationContext,
  language: 'en' | 'ar'
): Partial<OfficialPdfContext> {
  // Default colors
  const defaultPrimary = '#1e40af';
  const defaultSecondary = '#64748b';
  const defaultAccent = '#f59e0b';

  return {
    primaryColor: orgContext.brandingPrimaryColor || defaultPrimary,
    secondaryColor: orgContext.brandingSecondaryColor || defaultSecondary,
    accentColor: orgContext.brandingAccentColor || defaultAccent,
    textColor: '#1f2937',
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
    headerBackgroundColor: orgContext.brandingPrimaryColor || defaultPrimary,
    footerBackgroundColor: '#f9fafb',
  };
}

/**
 * Build utility classes and properties for RTL/LTR
 */
function buildPdfUtilities(language: 'en' | 'ar'): Partial<OfficialPdfContext> {
  const isRTL = language === 'ar';

  return {
    textAlign: isRTL ? 'right' : 'left',
    alignClass: isRTL ? 'text-right' : 'text-left',
    alignOpposite: isRTL ? 'left' : 'right',
    marginStart: isRTL ? 'mr' : 'ml',
    marginEnd: isRTL ? 'ml' : 'mr',
    paddingStart: isRTL ? 'pr' : 'pl',
    paddingEnd: isRTL ? 'pl' : 'pr',
  };
}

/**
 * Build footer context
 */
function buildFooterContext(
  orgContext: PdfOrganizationContext,
  user: any,
  date: Date,
  language: 'en' | 'ar'
): Partial<OfficialPdfContext> {
  const footerDate = formatDateForPdf(date, language);
  const generatedByText = user.name || user.email || 'System';

  return {
    footerOrganizationName: orgContext.organizationName || '',
    footerOperatingUnitName: orgContext.operatingUnitName || '',
    footerText: `${orgContext.organizationName} - ${orgContext.operatingUnitName}`,
    footerDate,
    footerGeneratedBy: generatedByText,
  };
}

/**
 * Format date for PDF display
 */
function formatDateForPdf(date: Date, language: 'en' | 'ar'): string {
  if (language === 'ar') {
    const formatter = new Intl.DateTimeFormat('ar-SA', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
    return formatter.format(date);
  }

  const formatter = new Intl.DateTimeFormat('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
  return formatter.format(date);
}

/**
 * Get HTML header with official PDF styling
 */
export function getOfficialPdfHeader(context: OfficialPdfContext): string {
  const isRTL = context.isRTL;

  return `
    <!DOCTYPE html>
    <html dir="${isRTL ? 'rtl' : 'ltr'}" lang="${context.language}">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${context.documentType}</title>
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }

        body {
          font-family: 'Arial', 'Segoe UI', sans-serif;
          color: ${context.textColor};
          background-color: ${context.backgroundColor};
          line-height: 1.6;
          direction: ${isRTL ? 'rtl' : 'ltr'};
          text-align: ${isRTL ? 'right' : 'left'};
        }

        .page {
          width: 210mm;
          height: 297mm;
          padding: 20mm;
          margin: 0 auto;
          background: white;
          box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
          page-break-after: always;
        }

        .page:last-child {
          page-break-after: avoid;
        }

        .header {
          background-color: ${context.headerBackgroundColor};
          color: white;
          padding: 15px 20px;
          margin-bottom: 20px;
          border-radius: 4px;
          display: flex;
          justify-content: space-between;
          align-items: center;
        }

        .header-logo {
          max-width: 100px;
          max-height: 50px;
        }

        .header-title {
          flex: 1;
          text-align: ${isRTL ? 'right' : 'left'};
          margin: 0 20px;
        }

        .header-title h1 {
          font-size: 24px;
          font-weight: bold;
          margin: 0;
        }

        .header-title p {
          font-size: 12px;
          opacity: 0.9;
          margin: 5px 0 0 0;
        }

        .footer {
          background-color: ${context.footerBackgroundColor};
          border-top: 1px solid ${context.borderColor};
          padding: 15px 20px;
          margin-top: 20px;
          font-size: 10px;
          color: #666;
          display: flex;
          justify-content: space-between;
          align-items: center;
          direction: ${isRTL ? 'rtl' : 'ltr'};
        }

        .footer-left {
          flex: 1;
          text-align: ${isRTL ? 'right' : 'left'};
        }

        .footer-right {
          text-align: ${isRTL ? 'left' : 'right'};
        }

        .content {
          min-height: 200mm;
        }

        table {
          width: 100%;
          border-collapse: collapse;
          margin: 15px 0;
        }

        th {
          background-color: #f3f4f6;
          border: 1px solid ${context.borderColor};
          padding: 10px;
          text-align: ${isRTL ? 'right' : 'left'};
          font-weight: 600;
        }

        td {
          border: 1px solid ${context.borderColor};
          padding: 10px;
          text-align: ${isRTL ? 'right' : 'left'};
        }

        .section-title {
          background-color: ${context.primaryColor};
          color: white;
          padding: 10px 15px;
          margin: 20px 0 10px 0;
          border-radius: 4px;
          font-weight: bold;
          font-size: 14px;
        }

        .metadata {
          background-color: #f9fafb;
          border: 1px solid ${context.borderColor};
          padding: 10px;
          margin: 10px 0;
          font-size: 11px;
          border-radius: 4px;
        }

        .metadata-row {
          display: flex;
          justify-content: space-between;
          margin: 5px 0;
        }

        .metadata-label {
          font-weight: 600;
          color: ${context.primaryColor};
        }

        .official-stamp {
          border: 2px solid ${context.accentColor};
          padding: 10px;
          text-align: center;
          margin: 20px 0;
          border-radius: 4px;
          background-color: rgba(245, 158, 11, 0.05);
        }

        .official-stamp-text {
          color: ${context.accentColor};
          font-weight: bold;
          font-size: 14px;
        }

        ${context.brandingCustomCss || ''}
      </style>
    </head>
    <body>
  `;
}

/**
 * Get HTML footer with page numbers and metadata
 */
export function getOfficialPdfFooter(
  context: OfficialPdfContext,
  pageNumber: number = 1,
  totalPages: number = 1
): string {
  const pageText =
    context.language === 'ar'
      ? `${context.labels.page} ${pageNumber} ${context.labels.of} ${totalPages}`
      : `${context.labels.page} ${pageNumber} ${context.labels.of} ${totalPages}`;

  const isRTL = context.isRTL;

  return `
    <div class="footer" style="direction: ${isRTL ? 'rtl' : 'ltr'};">
      <div class="footer-left" style="text-align: ${isRTL ? 'right' : 'left'};">
        <div>${context.footerOrganizationName}</div>
        <div>${context.footerOperatingUnitName}</div>
        <div style="margin-top: 5px; font-size: 9px; color: #999;">
          ${context.labels.generatedBy}: ${context.generatedBy}
        </div>
      </div>
      <div class="footer-right" style="text-align: ${isRTL ? 'left' : 'right'};">
        <div>${context.footerDate}</div>
        <div style="margin-top: 5px;">${pageText}</div>
      </div>
    </div>
  `;
}

/**
 * Get official metadata section for PDF
 */
export function getOfficialMetadataSection(context: OfficialPdfContext): string {
  const isRTL = context.isRTL;

  return `
    <div class="metadata" style="direction: ${isRTL ? 'rtl' : 'ltr'};">
      <div class="metadata-row">
        <span class="metadata-label">${context.labels.organization}:</span>
        <span>${context.organizationName}</span>
      </div>
      <div class="metadata-row">
        <span class="metadata-label">${context.labels.operatingUnit}:</span>
        <span>${context.operatingUnitName}</span>
      </div>
      <div class="metadata-row">
        <span class="metadata-label">${context.labels.generatedBy}:</span>
        <span>${context.generatedBy}</span>
      </div>
      <div class="metadata-row">
        <span class="metadata-label">${context.labels.generatedAt}:</span>
        <span>${context.generatedAtFormatted}</span>
      </div>
    </div>
  `;
}

/**
 * Validate official PDF context
 */
export function validateOfficialPdfContext(context: OfficialPdfContext): void {
  const requiredFields: (keyof OfficialPdfContext)[] = [
    'organizationId',
    'organizationName',
    'operatingUnitId',
    'operatingUnitName',
    'language',
    'direction',
    'generatedBy',
    'generatedAt',
    'documentType',
    'documentId',
  ];

  for (const field of requiredFields) {
    if (!context[field]) {
      throw new Error(`Missing required field in official PDF context: ${String(field)}`);
    }
  }

  console.log(`[Official PDF Context] ✅ Validation passed`);
}
