/**
 * ============================================================================
 * PAYROLL SLIP PRINT MODAL - Individual Employee Pay Stub
 * ============================================================================
 * ✅ Official payslip document for individual employee
 * ✅ A4 Layout, print-optimized
 * ✅ Organization branding from System Settings
 * ✅ Earnings + Deductions breakdown
 * ✅ Suitable for bank submission & tax records
 * ============================================================================
 */

import { X, Printer, DollarSign } from 'lucide-react';
import { StaffMember } from '../types/hrTypes';
import type { PayrollRecord } from '../types/hrTypes';
import { useState, useEffect } from 'react';
import { getOrganizationSettings } from '@/app/services/organizationService';

interface Props {
  payrollRecord: PayrollRecord;
  employee: StaffMember;
  payPeriod: string; // e.g., "January 2025"
  onClose: () => void;
}

export function PayrollSlipPrintModal({ payrollRecord, employee, payPeriod, onClose }: Props) {
  const [language] = useState<'en' | 'ar'>('en');
  const [isRTL] = useState(false);
  const orgSettings = getOrganizationSettings();
  const orgName = language === 'ar' && orgSettings.nameAr ? orgSettings.nameAr : orgSettings.name;

  const handlePrint = () => {
    window.print();
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: employee.currency || 'USD',
      minimumFractionDigits: 2
    }).format(amount);
  };

  const formatDate = (dateString?: string) => {
    if (!dateString) return '-';
    return new Date(dateString).toLocaleDateString(language === 'ar' ? 'ar' : 'en', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  const t = {
    title: language === 'en' ? 'PAYROLL SLIP' : 'قسيمة الراتب',
    payPeriod: language === 'en' ? 'Pay Period' : 'فترة الدفع',
    payDate: language === 'en' ? 'Pay Date' : 'تاريخ الدفع',
    
    employeeInfo: language === 'en' ? 'Employee Information' : 'معلومات الموظف',
    staffId: language === 'en' ? 'Staff ID' : 'رقم الموظف',
    fullName: language === 'en' ? 'Full Name' : 'الاسم الكامل',
    position: language === 'en' ? 'Position' : 'المنصب',
    department: language === 'en' ? 'Department' : 'القسم',
    project: language === 'en' ? 'Project' : 'المشروع',
    
    earnings: language === 'en' ? 'Earnings' : 'الإيرادات',
    basicSalary: language === 'en' ? 'Basic Salary' : 'الراتب الأساسي',
    housingAllowance: language === 'en' ? 'Housing Allowance' : 'بدل السكن',
    transportAllowance: language === 'en' ? 'Transport Allowance' : 'بدل النقل',
    representationAllowance: language === 'en' ? 'Representation Allowance' : 'بدل التمثيل',
    otherAllowances: language === 'en' ? 'Other Allowances' : 'بدلات أخرى',
    grossSalary: language === 'en' ? 'Gross Salary' : 'إجمالي الراتب',
    
    deductions: language === 'en' ? 'Deductions' : 'الاستقطاعات',
    tax: language === 'en' ? 'Income Tax' : 'ضريبة الدخل',
    socialSecurity: language === 'en' ? 'Social Security' : 'الضمان الاجتماعي',
    healthInsurance: language === 'en' ? 'Health Insurance' : 'التأمين الصحي',
    otherDeductions: language === 'en' ? 'Other Deductions' : 'استقطاعات أخرى',
    totalDeductions: language === 'en' ? 'Total Deductions' : 'إجمالي الاستقطاعات',
    
    netSalary: language === 'en' ? 'NET SALARY' : 'صافي الراتب',
    
    paymentDetails: language === 'en' ? 'Payment Details' : 'تفاصيل الدفع',
    bankName: language === 'en' ? 'Bank Name' : 'اسم البنك',
    accountNumber: language === 'en' ? 'Account Number' : 'رقم الحساب',
    iban: language === 'en' ? 'IBAN' : 'رقم الآيبان',
    
    confidential: language === 'en' 
      ? 'This payslip is confidential and intended for the named employee only.'
      : 'قسيمة الراتب هذه سرية ومخصصة للموظف المذكور فقط.',
    
    generatedBy: language === 'en' ? 'Generated by' : 'تم الإنشاء بواسطة',
    generatedOn: language === 'en' ? 'Generated on' : 'تاريخ الإنشاء',
    
    print: language === 'en' ? 'Print' : 'طباعة',
    close: language === 'en' ? 'Close' : 'إغلاق'
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4" onClick={onClose}>
      <div 
        className="bg-white rounded-lg w-full max-w-4xl max-h-[90vh] overflow-hidden flex flex-col"
        onClick={(e) => e.stopPropagation()}
        dir={isRTL ? 'rtl' : 'ltr'}
      >
        {/* Header (Print Hidden) */}
        <div className="px-6 py-4 border-b border-gray-200 flex items-center justify-between bg-green-50 print:hidden">
          <h2 className="text-xl font-bold text-gray-900">{t.title}</h2>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-2 px-3 py-2 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700"
            >
              <Printer className="w-4 h-4" />
              <span>{t.print}</span>
            </button>
            <button onClick={onClose} className="text-gray-400 hover:text-gray-600">
              <X className="w-6 h-6" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-8">
          <div className="max-w-[210mm] mx-auto bg-white print:p-0">
            
            {/* Organization Header */}
            <div className="mb-8 text-center border-b-2 border-blue-600 pb-4">
              {orgSettings.logo && (
                <img 
                  src={orgSettings.logo} 
                  alt={orgName} 
                  className="h-16 mx-auto mb-2 object-contain"
                />
              )}
              <h1 className="text-2xl font-bold text-gray-900">{orgName}</h1>
              <p className="text-sm text-gray-600 mt-1">{language === 'en' ? 'Human Resources Department' : 'قسم الموارد البشرية'}</p>
            </div>

            {/* Document Title */}
            <div className="text-center mb-6">
              <div className="inline-flex items-center gap-2 px-4 py-2 bg-blue-100 rounded-lg">
                <DollarSign className="w-6 h-6 text-blue-600" />
                <h2 className="text-xl font-bold text-blue-900">{t.title}</h2>
              </div>
            </div>

            {/* Pay Period Info */}
            <div className="mb-8 bg-gray-50 border border-gray-200 rounded-lg p-4">
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <span className="font-medium text-gray-700">{t.payPeriod}:</span>
                  <p className="text-lg font-bold text-gray-900">{payPeriod}</p>
                </div>
                <div>
                  <span className="font-medium text-gray-700">{t.payDate}:</span>
                  <p className="text-lg font-bold text-gray-900">{formatDate(new Date().toISOString())}</p>
                </div>
              </div>
            </div>

            {/* Employee Information */}
            <div className="mb-6 border border-gray-300 rounded-lg p-4">
              <h3 className="text-sm font-bold text-gray-900 mb-3 uppercase bg-gray-100 px-3 py-2 rounded">
                {t.employeeInfo}
              </h3>
              <div className="grid grid-cols-2 gap-3 text-sm">
                <div className="flex justify-between">
                  <span className="text-gray-600">{t.staffId}:</span>
                  <span className="font-semibold text-gray-900">{employee.staffId}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">{t.fullName}:</span>
                  <span className="font-semibold text-gray-900">{employee.fullName}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">{t.position}:</span>
                  <span className="font-semibold text-gray-900">{employee.position}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">{t.department}:</span>
                  <span className="font-semibold text-gray-900">{employee.department}</span>
                </div>
                <div className="flex justify-between col-span-2">
                  <span className="text-gray-600">{t.project}:</span>
                  <span className="font-semibold text-gray-900">{payrollRecord.project}</span>
                </div>
              </div>
            </div>

            {/* Earnings Section */}
            <div className="mb-6">
              <h3 className="text-sm font-bold text-green-900 mb-3 uppercase bg-green-100 px-3 py-2 rounded">
                {t.earnings}
              </h3>
              <div className="border border-green-300 rounded-lg overflow-hidden">
                <table className="w-full text-sm">
                  <tbody>
                    <tr className="border-b border-green-200">
                      <td className="px-4 py-2 text-gray-700">{t.basicSalary}</td>
                      <td className="px-4 py-2 text-right font-semibold text-gray-900">{formatCurrency(payrollRecord.basicSalary)}</td>
                    </tr>
                    <tr className="border-b border-green-200 bg-green-50">
                      <td className="px-4 py-2 text-gray-700">{t.housingAllowance}</td>
                      <td className="px-4 py-2 text-right font-semibold text-gray-900">{formatCurrency(payrollRecord.housingAllowance)}</td>
                    </tr>
                    <tr className="border-b border-green-200">
                      <td className="px-4 py-2 text-gray-700">{t.transportAllowance}</td>
                      <td className="px-4 py-2 text-right font-semibold text-gray-900">{formatCurrency(payrollRecord.transportAllowance)}</td>
                    </tr>
                    <tr className="border-b border-green-200 bg-green-50">
                      <td className="px-4 py-2 text-gray-700">{t.representationAllowance}</td>
                      <td className="px-4 py-2 text-right font-semibold text-gray-900">{formatCurrency(payrollRecord.representationAllowance)}</td>
                    </tr>
                    <tr className="border-b-2 border-green-400">
                      <td className="px-4 py-2 text-gray-700">{t.otherAllowances}</td>
                      <td className="px-4 py-2 text-right font-semibold text-gray-900">{formatCurrency(payrollRecord.otherAllowances)}</td>
                    </tr>
                    <tr className="bg-green-100">
                      <td className="px-4 py-3 font-bold text-green-900">{t.grossSalary}</td>
                      <td className="px-4 py-3 text-right font-bold text-lg text-green-900">{formatCurrency(payrollRecord.grossSalary)}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            {/* Deductions Section */}
            <div className="mb-6">
              <h3 className="text-sm font-bold text-red-900 mb-3 uppercase bg-red-100 px-3 py-2 rounded">
                {t.deductions}
              </h3>
              <div className="border border-red-300 rounded-lg overflow-hidden">
                <table className="w-full text-sm">
                  <tbody>
                    <tr className="border-b border-red-200">
                      <td className="px-4 py-2 text-gray-700">{t.tax}</td>
                      <td className="px-4 py-2 text-right font-semibold text-gray-900">{formatCurrency(payrollRecord.taxAmount)}</td>
                    </tr>
                    <tr className="border-b border-red-200 bg-red-50">
                      <td className="px-4 py-2 text-gray-700">{t.socialSecurity}</td>
                      <td className="px-4 py-2 text-right font-semibold text-gray-900">{formatCurrency(payrollRecord.socialSecurityAmount)}</td>
                    </tr>
                    <tr className="border-b border-red-200">
                      <td className="px-4 py-2 text-gray-700">{t.healthInsurance}</td>
                      <td className="px-4 py-2 text-right font-semibold text-gray-900">{formatCurrency(payrollRecord.healthInsuranceAmount)}</td>
                    </tr>
                    <tr className="border-b-2 border-red-400 bg-red-50">
                      <td className="px-4 py-2 text-gray-700">{t.otherDeductions}</td>
                      <td className="px-4 py-2 text-right font-semibold text-gray-900">{formatCurrency(payrollRecord.otherDeductions)}</td>
                    </tr>
                    <tr className="bg-red-100">
                      <td className="px-4 py-3 font-bold text-red-900">{t.totalDeductions}</td>
                      <td className="px-4 py-3 text-right font-bold text-lg text-red-900">{formatCurrency(payrollRecord.totalDeductions)}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            {/* Net Salary */}
            <div className="mb-8 bg-gradient-to-r from-blue-600 to-blue-700 rounded-lg p-6 text-white">
              <div className="flex justify-between items-center">
                <span className="text-xl font-bold uppercase">{t.netSalary}</span>
                <span className="text-3xl font-bold">{formatCurrency(payrollRecord.netSalary)}</span>
              </div>
            </div>

            {/* Payment Details */}
            {(employee.bankName || employee.accountNumber || employee.iban) && (
              <div className="mb-6 border border-gray-300 rounded-lg p-4 bg-blue-50">
                <h3 className="text-sm font-bold text-blue-900 mb-3">{t.paymentDetails}</h3>
                <div className="grid grid-cols-2 gap-3 text-sm">
                  {employee.bankName && (
                    <div className="flex justify-between">
                      <span className="text-gray-700">{t.bankName}:</span>
                      <span className="font-semibold text-gray-900">{employee.bankName}</span>
                    </div>
                  )}
                  {employee.accountNumber && (
                    <div className="flex justify-between">
                      <span className="text-gray-700">{t.accountNumber}:</span>
                      <span className="font-semibold text-gray-900">{employee.accountNumber}</span>
                    </div>
                  )}
                  {employee.iban && (
                    <div className="flex justify-between col-span-2">
                      <span className="text-gray-700">{t.iban}:</span>
                      <span className="font-semibold text-gray-900">{employee.iban}</span>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Confidential Notice */}
            <div className="mb-6 bg-yellow-50 border-l-4 border-yellow-500 p-3">
              <p className="text-xs text-yellow-900 font-medium">{t.confidential}</p>
            </div>

            {/* Footer */}
            <div className="mt-8 pt-4 border-t border-gray-200 text-xs text-gray-500 text-center">
              <p>{t.generatedBy}: {orgName}</p>
              <p>{t.generatedOn}: {formatDate(new Date().toISOString())}</p>
            </div>
          </div>
        </div>

        {/* Footer Actions (Print Hidden) */}
        <div className="px-6 py-4 border-t border-gray-200 bg-gray-50 flex items-center justify-end gap-3 print:hidden">
          <button
            onClick={handlePrint}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            <Printer className="w-5 h-5" />
            <span>{t.print}</span>
          </button>
          <button
            onClick={onClose}
            className="px-4 py-2 text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50"
          >
            {t.close}
          </button>
        </div>
      </div>

      {/* Print Styles */}
      <style>{`
        @media print {
          @page {
            size: A4;
            margin: 15mm;
          }
          
          body {
            -webkit-print-color-adjust: exact;
            print-color-adjust: exact;
          }
          
          .print\\:hidden {
            display: none !important;
          }
          
          body * {
            visibility: hidden;
          }
          
          .fixed, .fixed * {
            visibility: visible;
          }
          
          .fixed {
            position: static;
            background: white;
          }
        }
      `}</style>
    </div>
  );
}
