// Correct vendors table definition matching the exported schema
export const vendors = mysqlTable('vendors', {
  id: int('id').autoincrement().primaryKey(),
  organizationId: int('organizationId').notNull(),
  operatingUnitId: int('operatingUnitId'),
  vendorCode: varchar('vendorCode', { length: 50 }).notNull(),
  name: varchar('name', { length: 255 }).notNull(),
  nameAr: varchar('nameAr', { length: 255 }),
  vendorType: mysqlEnum('vendorType', ['supplier', 'contractor', 'service_provider', 'consultant', 'other']).default('supplier'),
  taxId: varchar('taxId', { length: 50 }),
  registrationNumber: varchar('registrationNumber', { length: 100 }),
  contactPerson: varchar('contactPerson', { length: 255 }),
  email: varchar('email', { length: 255 }),
  phone: varchar('phone', { length: 50 }),
  mobile: varchar('mobile', { length: 50 }),
  fax: varchar('fax', { length: 50 }),
  website: varchar('website', { length: 255 }),
  addressLine1: varchar('addressLine1', { length: 255 }),
  addressLine2: varchar('addressLine2', { length: 255 }),
  city: varchar('city', { length: 100 }),
  state: varchar('state', { length: 100 }),
  country: varchar('country', { length: 100 }),
  postalCode: varchar('postalCode', { length: 20 }),
  bankName: varchar('bankName', { length: 255 }),
  bankBranch: varchar('bankBranch', { length: 255 }),
  bankAccountNumber: varchar('bankAccountNumber', { length: 100 }),
  bankAccountName: varchar('bankAccountName', { length: 255 }),
  iban: varchar('iban', { length: 50 }),
  swiftCode: varchar('swiftCode', { length: 20 }),
  currencyId: int('currencyId'),
  paymentTerms: varchar('paymentTerms', { length: 100 }),
  creditLimit: decimal('creditLimit', { precision: 15, scale: 2 }),
  currentBalance: decimal('currentBalance', { precision: 15, scale: 2 }).default('0.00'),
  glAccountId: int('glAccountId'),
  isActive: boolean('isActive').default(true),
  isPreferred: boolean('isPreferred').default(false),
  isBlacklisted: boolean('isBlacklisted').default(false),
  blacklistReason: text('blacklistReason'),
  notes: text('notes'),
  attachments: text('attachments'),
  createdAt: timestamp('createdAt').defaultNow(),
  updatedAt: timestamp('updatedAt').defaultNow().onUpdateNow(),
  createdBy: int('createdBy'),
  updatedBy: int('updatedBy'),
  deletedAt: timestamp('deletedAt'),
  deletedBy: int('deletedBy'),
}, (table) => ({
  ukOrgCode: uniqueIndex('uk_org_code').on(table.organizationId, table.vendorCode),
  idxOrg: index('idx_org').on(table.organizationId),
  idxOu: index('idx_ou').on(table.operatingUnitId),
  idxType: index('idx_type').on(table.vendorType),
  idxActive: index('idx_active').on(table.isActive),
}));
