CREATE TABLE `finance_encumbrances` (
	`id` int AUTO_INCREMENT NOT NULL,
	`purchaseRequestId` int NOT NULL,
	`purchaseOrderId` int,
	`budgetLineId` int NOT NULL,
	`vendorId` int,
	`projectId` int NOT NULL,
	`organizationId` int NOT NULL,
	`operatingUnitId` int,
	`encumbranceNumber` varchar(50),
	`encumbranceDate` timestamp DEFAULT (now()),
	`encumberedAmount` decimal(15,2) NOT NULL,
	`currency` varchar(10) DEFAULT 'USD',
	`exchangeRate` decimal(15,6) DEFAULT '1.000000',
	`baseCurrencyAmount` decimal(15,2),
	`status` enum('active','partially_liquidated','fully_liquidated','cancelled') DEFAULT 'active',
	`liquidatedAmount` decimal(15,2) DEFAULT '0',
	`remainingAmount` decimal(15,2),
	`reservationId` int,
	`createdBy` int,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`closedAt` timestamp,
	CONSTRAINT `finance_encumbrances_id` PRIMARY KEY(`id`),
	CONSTRAINT `finance_encumbrances_encumbranceNumber_unique` UNIQUE(`encumbranceNumber`)
);
--> statement-breakpoint
CREATE TABLE `pr_budget_reservations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`purchaseRequestId` int NOT NULL,
	`budgetLineId` int NOT NULL,
	`projectId` int NOT NULL,
	`organizationId` int NOT NULL,
	`operatingUnitId` int,
	`reservationNumber` varchar(50),
	`reservationDate` timestamp DEFAULT (now()),
	`reservedAmount` decimal(15,2) NOT NULL,
	`currency` varchar(10) DEFAULT 'USD',
	`exchangeRate` decimal(15,6) DEFAULT '1.000000',
	`baseCurrencyAmount` decimal(15,2),
	`status` enum('active','converted_to_encumbrance','released','expired') DEFAULT 'active',
	`convertedToEncumbranceAt` timestamp,
	`releasedAt` timestamp,
	`expiryDate` timestamp,
	`createdBy` int,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pr_budget_reservations_id` PRIMARY KEY(`id`),
	CONSTRAINT `pr_budget_reservations_reservationNumber_unique` UNIQUE(`reservationNumber`)
);
--> statement-breakpoint
CREATE TABLE `procurement_invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`purchaseRequestId` int NOT NULL,
	`purchaseOrderId` int NOT NULL,
	`grnId` int,
	`vendorId` int NOT NULL,
	`payableId` int,
	`organizationId` int NOT NULL,
	`operatingUnitId` int,
	`invoiceNumber` varchar(100) NOT NULL,
	`vendorInvoiceNumber` varchar(100),
	`invoiceDate` date NOT NULL,
	`invoiceAmount` decimal(15,2) NOT NULL,
	`currency` varchar(10) DEFAULT 'USD',
	`exchangeRate` decimal(15,6) DEFAULT '1.000000',
	`baseCurrencyAmount` decimal(15,2),
	`matchingStatus` enum('pending','matched','variance_detected','rejected') DEFAULT 'pending',
	`prAmount` decimal(15,2),
	`poAmount` decimal(15,2),
	`grnAmount` decimal(15,2),
	`varianceAmount` decimal(15,2),
	`varianceReason` text,
	`approvalStatus` enum('pending','approved','rejected') DEFAULT 'pending',
	`approvedBy` int,
	`approvedAt` timestamp,
	`rejectionReason` text,
	`paymentStatus` enum('unpaid','payment_scheduled','paid') DEFAULT 'unpaid',
	`paymentId` int,
	`paidAt` timestamp,
	`invoiceDocumentUrl` varchar(500),
	`createdBy` int,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `procurement_invoices_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `procurement_payables` (
	`id` int AUTO_INCREMENT NOT NULL,
	`purchaseRequestId` int NOT NULL,
	`purchaseOrderId` int NOT NULL,
	`vendorId` int NOT NULL,
	`encumbranceId` int,
	`organizationId` int NOT NULL,
	`operatingUnitId` int,
	`payableNumber` varchar(50),
	`payableDate` timestamp DEFAULT (now()),
	`totalAmount` decimal(15,2) NOT NULL,
	`currency` varchar(10) DEFAULT 'USD',
	`exchangeRate` decimal(15,6) DEFAULT '1.000000',
	`baseCurrencyAmount` decimal(15,2),
	`paymentTerms` varchar(255),
	`dueDate` date,
	`status` enum('draft','pending_grn','pending_invoice','pending_payment','partially_paid','fully_paid','cancelled') DEFAULT 'draft',
	`paidAmount` decimal(15,2) DEFAULT '0',
	`remainingAmount` decimal(15,2),
	`createdBy` int,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `procurement_payables_id` PRIMARY KEY(`id`),
	CONSTRAINT `procurement_payables_payableNumber_unique` UNIQUE(`payableNumber`)
);
