import { Link } from 'wouter';
/**
 * ============================================================================
 * HR REPORTS & ANALYTICS MODULE
 * ============================================================================
 * 
 * Management and audit-ready insights
 * Read-only, filterable, exportable
 * All data pulled from authoritative sources
 * 
 * Categories:
 * - Workforce Reports
 * - Payroll Reports
 * - Leave Reports
 * - Recruitment Reports
 * - Compliance Reports
 * 
 * ============================================================================
 */

import { Link } from 'wouter';
import { useState, useEffect } from 'react';
import { BarChart3, Users, DollarSign, Calendar, UserCheck, AlertTriangle, Download, FileText, TrendingUp } from 'lucide-react';
import { useNavigate } from '@/lib/router-compat';
import { useLanguage } from '@/contexts/LanguageContext';
import { staffService } from '@/app/services/hrService';
import { leaveRequestService } from './leave/leaveService';
import { vacancyService, candidateService } from './recruitment/recruitmentService';
import { useTranslation } from '@/i18n/useTranslation';
import { BackButton } from "@/components/BackButton";

type ReportCategory = 'workforce' | 'payroll' | 'leave' | 'recruitment' | 'compliance';

export function HRReports() {
 const { t } = useTranslation();
 const { language, isRTL } = useLanguage();
 const navigate = useNavigate();
 const [activeCategory, setActiveCategory] = useState<ReportCategory>('workforce');
 const [dateFilter, setDateFilter] = useState<string>('');

 const labels = {
 title: t.hrReports.reportsAnalytics,
 subtitle: t.hrReports.managementAndAuditreadyHrInsights,
 
 // Categories
 workforceReports: t.hrReports.workforceReports,
 payrollReports: t.hrReports.payrollReports,
 leaveReports: t.hrReports.leaveReports,
 recruitmentReports: t.hrReports.recruitmentReports,
 complianceReports: t.hrReports.complianceReports,
 
 // Workforce
 totalHeadcount: t.hrReports.totalHeadcount,
 activeEmployees: t.hrReports.activeEmployees,
 archivedEmployees: t.hrReports.archivedEmployees,
 exitedEmployees: t.hrReports.exitedEmployees,
 headcountByDepartment: t.hrReports.headcountByDepartment,
 headcountByProject: t.hrReports.headcountByProject,
 genderBreakdown: t.hrReports.genderBreakdown,
 nationalityBreakdown: t.hrReports.nationalityBreakdown,
 
 // Common
 export: t.hrReports.exportToExcel,
 print: t.hrReports.printReport,
 dateRange: t.hrReports.dateRange,
 
 department: t.hrReports.department,
 count: t.hrReports.count,
 percentage: t.hrReports.percentage,
 
 readOnlyNote: t.hrReports.allReportsAreReadonlyAndAutogenerated
 };

 // Calculate workforce statistics
 const getWorkforceStats = () => {
 const allStaff = staffService.getAll();
 const active = allStaff.filter(s => s.status === 'active');
 const archived = allStaff.filter(s => s.status === 'archived');
 const exited = allStaff.filter(s => s.status === 'exited');
 
 // By department
 const departmentCounts: Record<string, number> = {};
 active.forEach(staff => {
 const dept = staff.department || 'Unassigned';
 departmentCounts[dept] = (departmentCounts[dept] || 0) + 1;
 });
 
 // By project
 const projectCounts: Record<string, number> = {};
 active.forEach(staff => {
 const proj = staff.project || 'Unassigned';
 projectCounts[proj] = (projectCounts[proj] || 0) + 1;
 });
 
 // By gender
 const genderCounts: Record<string, number> = {};
 active.forEach(staff => {
 const gender = staff.gender || 'Not Specified';
 genderCounts[gender] = (genderCounts[gender] || 0) + 1;
 });
 
 // By nationality
 const nationalityCounts: Record<string, number> = {};
 active.forEach(staff => {
 const nat = staff.nationality || 'Not Specified';
 nationalityCounts[nat] = (nationalityCounts[nat] || 0) + 1;
 });
 
 return {
 total: allStaff.length,
 active: active.length,
 archived: archived.length,
 exited: exited.length,
 byDepartment: Object.entries(departmentCounts).map(([name, count]) => ({
 name,
 count,
 percentage: active.length > 0 ? ((count / active.length) * 100).toFixed(1) : '0'
 })),
 byProject: Object.entries(projectCounts).map(([name, count]) => ({
 name,
 count,
 percentage: active.length > 0 ? ((count / active.length) * 100).toFixed(1) : '0'
 })),
 byGender: Object.entries(genderCounts).map(([name, count]) => ({
 name,
 count,
 percentage: active.length > 0 ? ((count / active.length) * 100).toFixed(1) : '0'
 })),
 byNationality: Object.entries(nationalityCounts).map(([name, count]) => ({
 name,
 count,
 percentage: active.length > 0 ? ((count / active.length) * 100).toFixed(1) : '0'
 }))
 };
 };

 // Calculate leave statistics
 const getLeaveStats = () => {
 const allLeaves = leaveRequestService.getAll();
 const pending = allLeaves.filter(l => l.status === 'Pending');
 const approved = allLeaves.filter(l => l.status === 'Approved');
 const rejected = allLeaves.filter(l => l.status === 'Rejected');
 
 // By type
 const typeCounts: Record<string, number> = {};
 allLeaves.forEach(leave => {
 typeCounts[leave.leaveType] = (typeCounts[leave.leaveType] || 0) + 1;
 });
 
 return {
 total: allLeaves.length,
 pending: pending.length,
 approved: approved.length,
 rejected: rejected.length,
 byType: Object.entries(typeCounts).map(([type, count]) => ({
 type,
 count
 }))
 };
 };

 // Calculate recruitment statistics
 const getRecruitmentStats = () => {
 const allVacancies = vacancyService.getAll();
 const allCandidates = candidateService.getAll();
 
 const openVacancies = allVacancies.filter(v => v.status === 'Open');
 const closedVacancies = allVacancies.filter(v => v.status === 'Closed');
 
 const avgCandidatesPerVacancy = allVacancies.length > 0 
 ? (allCandidates.length / allVacancies.length).toFixed(1)
 : '0';
 
 return {
 totalVacancies: allVacancies.length,
 openVacancies: openVacancies.length,
 closedVacancies: closedVacancies.length,
 totalCandidates: allCandidates.length,
 avgCandidatesPerVacancy
 };
 };

 const workforceStats = getWorkforceStats();
 const leaveStats = getLeaveStats();
 const recruitmentStats = getRecruitmentStats();

 const categories = [
 { id: 'workforce' as ReportCategory, name: labels.workforceReports, icon: Users },
 { id: 'payroll' as ReportCategory, name: labels.payrollReports, icon: DollarSign },
 { id: 'leave' as ReportCategory, name: labels.leaveReports, icon: Calendar },
 { id: 'recruitment' as ReportCategory, name: labels.recruitmentReports, icon: UserCheck },
 { id: 'compliance' as ReportCategory, name: labels.complianceReports, icon: AlertTriangle }
 ];

 const handleExport = () => {
 alert('Export to Excel - In a real system, this would generate an Excel file');
 };

 const handlePrint = () => {
 window.print();
 };

 return (
 <div className="space-y-6" dir={isRTL ? 'rtl' : 'ltr'}>
 {/* Back Button */}
 <BackButton href="/organization/hr" label={t.hrReports.hrDashboard} />

 {/* Header */}
 <div>
 <h1 className="text-3xl font-bold text-gray-900">{labels.title}</h1>
 <p className="text-base text-gray-600 mt-2">{labels.subtitle}</p>
 </div>

 {/* Read-Only Note */}
 <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
 <p className="text-sm text-blue-900">{labels.readOnlyNote}</p>
 </div>

 {/* Category Tabs */}
 <div className="bg-white rounded-lg border border-gray-200">
 <div className="border-b border-gray-200">
 <div className="flex overflow-x-auto">
 {categories.map(cat => {
 const Icon = cat.icon;
 return (
 <button
 key={cat.id}
 onClick={() => setActiveCategory(cat.id)}
 className={`flex items-center gap-2 px-6 py-3 text-sm font-medium border-b-2 transition-colors whitespace-nowrap ${ activeCategory === cat.id ? 'border-blue-500 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300' }`}
 >
 <Icon className="w-4 h-4" />
 {cat.name}
 </button>
 );
 })}
 </div>
 </div>

 {/* Action Buttons */}
 <div className="p-4 border-b border-gray-200 flex items-center justify-between">
 <div className="flex items-center gap-3">
 <button
 onClick={handleExport}
 className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 text-sm"
 >
 <Download className="w-4 h-4" />
 {labels.export}
 </button>
 <button
 onClick={handlePrint}
 className="flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 text-sm"
 >
 <FileText className="w-4 h-4" />
 {labels.print}
 </button>
 </div>
 </div>

 {/* Report Content */}
 <div className="p-6">
 {/* Workforce Reports */}
 {activeCategory === 'workforce' && (
 <div className="space-y-6">
 {/* Summary Cards */}
 <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
 <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
 <p className="text-xs text-blue-700 mb-1">{labels.totalHeadcount}</p>
 <p className="text-3xl font-bold text-blue-900">{workforceStats.total}</p>
 </div>
 <div className="bg-green-50 border border-green-200 rounded-lg p-4">
 <p className="text-xs text-green-700 mb-1">{labels.activeEmployees}</p>
 <p className="text-3xl font-bold text-green-900">{workforceStats.active}</p>
 </div>
 <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
 <p className="text-xs text-amber-700 mb-1">{labels.archivedEmployees}</p>
 <p className="text-3xl font-bold text-amber-900">{workforceStats.archived}</p>
 </div>
 <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
 <p className="text-xs text-gray-700 mb-1">{labels.exitedEmployees}</p>
 <p className="text-3xl font-bold text-gray-900">{workforceStats.exited}</p>
 </div>
 </div>

 {/* Headcount by Department */}
 <div className="bg-white border border-gray-200 rounded-lg p-6">
 <h3 className="text-lg font-semibold text-gray-900 mb-4">{labels.headcountByDepartment}</h3>
 <div className="overflow-x-auto">
 <table className="w-full">
 <thead className="bg-gray-50 border-b border-gray-200">
 <tr>
 <th className={`px-4 py-3 text-xs font-medium text-gray-500 uppercase text-start`}>{labels.department}</th>
 <th className={`px-4 py-3 text-xs font-medium text-gray-500 uppercase text-start`}>{labels.count}</th>
 <th className={`px-4 py-3 text-xs font-medium text-gray-500 uppercase text-start`}>{labels.percentage}</th>
 </tr>
 </thead>
 <tbody className="divide-y divide-gray-200">
 {workforceStats.byDepartment.map((dept, idx) => (
 <tr key={idx}>
 <td className="px-4 py-3 text-sm font-medium text-gray-900">{dept.name}</td>
 <td className="px-4 py-3 text-sm text-gray-900">{dept.count}</td>
 <td className="px-4 py-3 text-sm text-gray-500">{dept.percentage}%</td>
 </tr>
 ))}
 </tbody>
 </table>
 </div>
 </div>

 {/* Gender Breakdown */}
 <div className="bg-white border border-gray-200 rounded-lg p-6">
 <h3 className="text-lg font-semibold text-gray-900 mb-4">{labels.genderBreakdown}</h3>
 <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
 {workforceStats.byGender.map((gender, idx) => (
 <div key={idx} className="bg-gray-50 rounded-lg p-4">
 <p className="text-sm text-gray-600">{gender.name}</p>
 <p className="text-2xl font-bold text-gray-900 mt-1">{gender.count}</p>
 <p className="text-xs text-gray-500 mt-1">{gender.percentage}%</p>
 </div>
 ))}
 </div>
 </div>
 </div>
 )}

 {/* Payroll Reports */}
 {activeCategory === 'payroll' && (
 <div className="text-center py-12">
 <DollarSign className="w-16 h-16 text-gray-300 mx-auto mb-4" />
 <p className="text-gray-500">
 {t.hrReports.payrollReportsComingSoon}
 </p>
 <p className="text-xs text-gray-400 mt-2">
 {t.hrReports.willShowPayrollCostsByMonth}
 </p>
 </div>
 )}

 {/* Leave Reports */}
 {activeCategory === 'leave' && (
 <div className="space-y-6">
 {/* Summary Cards */}
 <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
 <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
 <p className="text-xs text-blue-700 mb-1">Total Leaves</p>
 <p className="text-3xl font-bold text-blue-900">{leaveStats.total}</p>
 </div>
 <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
 <p className="text-xs text-yellow-700 mb-1">Pending</p>
 <p className="text-3xl font-bold text-yellow-900">{leaveStats.pending}</p>
 </div>
 <div className="bg-green-50 border border-green-200 rounded-lg p-4">
 <p className="text-xs text-green-700 mb-1">Approved</p>
 <p className="text-3xl font-bold text-green-900">{leaveStats.approved}</p>
 </div>
 <div className="bg-red-50 border border-red-200 rounded-lg p-4">
 <p className="text-xs text-red-700 mb-1">Rejected</p>
 <p className="text-3xl font-bold text-red-900">{leaveStats.rejected}</p>
 </div>
 </div>

 {/* Leave by Type */}
 <div className="bg-white border border-gray-200 rounded-lg p-6">
 <h3 className="text-lg font-semibold text-gray-900 mb-4">Leave Requests by Type</h3>
 <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
 {leaveStats.byType.map((type, idx) => (
 <div key={idx} className="bg-gray-50 rounded-lg p-4">
 <p className="text-sm text-gray-600">{type.type}</p>
 <p className="text-2xl font-bold text-gray-900 mt-1">{type.count}</p>
 </div>
 ))}
 </div>
 </div>
 </div>
 )}

 {/* Recruitment Reports */}
 {activeCategory === 'recruitment' && (
 <div className="space-y-6">
 {/* Summary Cards */}
 <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
 <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
 <p className="text-xs text-blue-700 mb-1">Total Vacancies</p>
 <p className="text-3xl font-bold text-blue-900">{recruitmentStats.totalVacancies}</p>
 </div>
 <div className="bg-green-50 border border-green-200 rounded-lg p-4">
 <p className="text-xs text-green-700 mb-1">Open Vacancies</p>
 <p className="text-3xl font-bold text-green-900">{recruitmentStats.openVacancies}</p>
 </div>
 <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
 <p className="text-xs text-gray-700 mb-1">Total Candidates</p>
 <p className="text-3xl font-bold text-gray-900">{recruitmentStats.totalCandidates}</p>
 </div>
 </div>

 <div className="bg-white border border-gray-200 rounded-lg p-6">
 <h3 className="text-lg font-semibold text-gray-900 mb-2">Average Candidates per Vacancy</h3>
 <p className="text-4xl font-bold text-blue-600">{recruitmentStats.avgCandidatesPerVacancy}</p>
 </div>
 </div>
 )}

 {/* Compliance Reports */}
 {activeCategory === 'compliance' && (
 <div className="text-center py-12">
 <AlertTriangle className="w-16 h-16 text-gray-300 mx-auto mb-4" />
 <p className="text-gray-500">
 {t.hrReports.complianceReportsComingSoon}
 </p>
 <p className="text-xs text-gray-400 mt-2">
 {t.hrReports.willShowContractsExpiringMissingDocuments}
 </p>
 </div>
 )}
 </div>
 </div>
 </div>
 );
}