/**
 * ============================================================================
 * OFFICIAL DOCUMENT TEMPLATE - Global Print Layout for All HR Forms
 * ============================================================================
 * 
 * MANDATORY RULE:
 * All printable HR documents MUST use this template.
 * UI forms ≠ Official documents.
 * 
 * FEATURES:
 * - Organization branding (logo + name) from System Settings
 * - Department: Human Resources
 * - Dynamic form title
 * - Confidential label
 * - Generated by / Generated on
 * - Page numbers (future)
 * - A4 layout, print-optimized
 * - LTR / RTL support
 * 
 * USAGE:
 * <OfficialDocumentTemplate
 *   title="Performance Appraisal Form"
 *   language="en"
 *   isRTL={false}
 *   confidential={true}
 *   generatedBy="HR Manager"
 * >
 *   {/* Document content goes here *\/}
 * </OfficialDocumentTemplate>
 * 
 * ============================================================================
 */

import { formatDate } from '@/utils/formatters';
import { useEffect, useState } from 'react';
import { getOrganizationSettings, OrganizationSettings } from '@/services/organizationService';

interface Props {
  title: string;
  titleAr?: string;
  language: 'en' | 'ar';
  isRTL: boolean;
  confidential?: boolean;
  generatedBy?: string;
  employeeName?: string;
  staffId?: string;
  children: React.ReactNode;
}

export function OfficialDocumentTemplate({
  title,
  titleAr,
  language,
  isRTL,
  confidential = true,
  generatedBy,
  employeeName,
  staffId,
  children
}: Props) {
  const [orgSettings, setOrgSettings] = useState<OrganizationSettings | null>(null);

  useEffect(() => {
    setOrgSettings(getOrganizationSettings());
  }, []);

  const formatDate = (date: Date) => {
    return date.toLocaleDateString(language === 'ar' ? 'ar' : 'en', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  const t = {
    hrDepartment: language === 'en' ? 'Human Resources Department' : 'قسم الموارد البشرية',
    confidential: language === 'en' ? 'CONFIDENTIAL – INTERNAL USE' : 'سري – للاستخدام الداخلي',
    generatedOn: language === 'en' ? 'Generated on' : 'تم الإنشاء في',
    generatedByLabel: language === 'en' ? 'Generated by' : 'تم الإنشاء بواسطة',
    staffIdLabel: language === 'en' ? 'Staff ID' : 'رقم الموظف',
    employeeLabel: language === 'en' ? 'Employee' : 'الموظف',
    page: language === 'en' ? 'Page' : 'صفحة',
    of: language === 'en' ? 'of' : 'من'
  };

  const displayTitle = language === 'ar' && titleAr ? titleAr : title;
  const orgName = language === 'ar' && orgSettings?.nameAr 
    ? orgSettings.nameAr 
    : (orgSettings?.name || 'Humanitarian Organization');

  return (
    <div className="bg-white min-h-screen" dir={isRTL ? 'rtl' : 'ltr'}>
      {/* A4 Page Container */}
      <div className="max-w-[210mm] mx-auto p-[20mm] print:p-[15mm]">
        
        {/* Official Header */}
        <div className="border-b-4 border-blue-600 pb-6 mb-8">
          {/* Logo + Organization Name */}
          <div className={`flex items-center gap-4 mb-4 ${isRTL ? 'flex-row-reverse' : ''}`}>
            {orgSettings?.logo && (
              <img 
                src={orgSettings.logo} 
                alt="Organization Logo" 
                className="h-16 w-auto object-contain"
              />
            )}
            <div className={isRTL ? 'text-right' : 'text-left'}>
              <h1 className="text-2xl font-bold text-gray-900">{orgName}</h1>
              <p className="text-sm text-gray-600 mt-1">{t.hrDepartment}</p>
            </div>
          </div>

          {/* Document Title + Confidential Label */}
          <div className={`flex items-center justify-between mt-6 ${isRTL ? 'flex-row-reverse' : ''}`}>
            <h2 className="text-xl font-bold text-blue-900">{displayTitle}</h2>
            {confidential && (
              <span className="px-3 py-1 bg-red-100 text-red-700 text-xs font-bold rounded border border-red-300">
                {t.confidential}
              </span>
            )}
          </div>

          {/* Employee Info (if provided) */}
          {(staffId || employeeName) && (
            <div className={`mt-4 text-sm text-gray-700 ${isRTL ? 'text-right' : 'text-left'}`}>
              {staffId && (
                <p><strong>{t.staffIdLabel}:</strong> {staffId}</p>
              )}
              {employeeName && (
                <p><strong>{t.employeeLabel}:</strong> {employeeName}</p>
              )}
            </div>
          )}
        </div>

        {/* Document Content */}
        <div className="space-y-6">
          {children}
        </div>

        {/* Official Footer */}
        <div className="mt-12 pt-6 border-t-2 border-gray-300">
          <div className={`text-xs text-gray-600 space-y-1 ${isRTL ? 'text-right' : 'text-left'}`}>
            <p>
              <strong>{t.generatedOn}:</strong> {formatDate(new Date())}
            </p>
            {generatedBy && (
              <p>
                <strong>{t.generatedByLabel}:</strong> {generatedBy}
              </p>
            )}
            <p className="text-gray-500 mt-2">
              {language === 'en' 
                ? 'This is an official HR document. Unauthorized access, use, or distribution is prohibited.' 
                : 'هذه وثيقة رسمية للموارد البشرية. يُحظر الوصول أو الاستخدام أو التوزيع غير المصرح به.'}
            </p>
          </div>

          {/* Page Numbers (Future Enhancement) */}
          {/* <div className="text-center text-xs text-gray-500 mt-4">
            {t.page} 1 {t.of} 1
          </div> */}
        </div>
      </div>

      {/* Print Styles */}
      <style>{`
        @media print {
          @page {
            size: A4;
            margin: 15mm;
          }
          
          body {
            -webkit-print-color-adjust: exact;
            print-color-adjust: exact;
          }
          
          .print\\:hidden {
            display: none !important;
          }
          
          .print\\:p-\\[15mm\\] {
            padding: 0 !important;
          }
          
          /* Ensure black text on white background */
          body, .bg-white {
            background: white !important;
            color: black !important;
          }
          
          /* Hide browser UI elements */
          button, .no-print {
            display: none !important;
          }
          
          /* Page breaks */
          .page-break {
            page-break-after: always;
          }
        }
      `}</style>
    </div>
  );
}
