// FINANCE REPORTING CENTER — /finance/reporting
// Enterprise Financial Reporting Workspace.
//
// Backend: trpc.financialReports.* (single source of truth)
//   • getFilterMeta       — filter options (projects, donors, grants, fiscal years)
//   • generateReport      — real report data via ReportEnvelope
//   • getFinancialIntelligence — AI insights from live data
//   • getExportHistory    — audit log of generated reports
//   • logGeneratedReport  — mutation to log exports
//
// Data contract: every report returns a ReportEnvelope:
//   { status: 'ok' | 'not_implemented' | 'error', data, message }
//
// NO MOCK DATA. Every number is live, a skeleton while pending, or an explicit
// Empty State when the backend has nothing (or the report is not yet available).
// Design system: reuses @/app/components/finance/fdashboard tokens + components
// to stay visually consistent with the Finance Dashboard / Risk / Compliance.
// ============================================================================

import { useState, useMemo, useCallback } from "react";
import {
  Bar, BarChart, CartesianGrid, ComposedChart, Legend, Line,
  ResponsiveContainer, Tooltip, XAxis, YAxis, ReferenceLine, Cell,
} from "recharts";
import {
  Bot, Calendar, Clock, Download, FileBarChart, FileText, Globe,
  LayoutList, Printer, ShieldCheck, Users, Wallet, TrendingUp,
  Building2, Landmark, Activity, ChevronDown, ChevronRight,
} from "lucide-react";
import { useLanguage } from "@//contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import {
  FinanceCard, WidgetHeader, ChartWrapper, ExecutiveTable, FinanceKpiCard,
  FinanceFilterBar, LoadingSkeleton, EmptyState, ErrorState,
  FINANCE_COLORS, CHART_COLORS, compactCurrency,
  type TableColumn, type FilterDropdown,
} from "@/components/finance/fdashboard";

// ─── Translations (EN / AR / IT) ─────────────────────────────────────────────
const T = {
  en: {
    pageTitle: "Finance Reporting Center",
    pageSubtitle: "Live financial reports across the organization portfolio",
    project: "Project", allProjects: "All Projects",
    fiscalYear: "Fiscal Year", reportingPeriod: "Reporting Period",
    monthly: "Monthly", quarterly: "Quarterly", semiAnnual: "Semi-Annual",
    annual: "Annual", custom: "Custom Period",
    periodFrom: "From", periodTo: "To",
    financialStatements: "Financial Statements", donorReports: "Donor Reports",
    managementReports: "Management Reports", complianceReports: "Compliance Reports",
    executiveReports: "Executive Reports",
    donor: "Donor", grant: "Grant", operatingUnit: "Operating Unit",
    generated: "Generated", generatedBy: "Generated By", reportStatus: "Status",
    lastRefreshed: "Last Refreshed", period: "Period",
    executiveSummary: "Executive Summary",
    budget: "Budget", actual: "Actual Expenditure", remaining: "Remaining Budget",
    burnRate: "Burn Rate", utilization: "Budget Utilization",
    financialHealth: "Financial Health", commitments: "Outstanding Commitments",
    majorVariances: "Major Variances",
    available: "Available", openingBalance: "Opening Balance",
    operatingCash: "Operating Cash", investingCash: "Investing Cash",
    financingCash: "Financing Cash", closingBalance: "Closing Balance",
    assets: "Assets", liabilities: "Liabilities", equity: "Equity",
    workingCapital: "Working Capital", currentRatio: "Current Ratio",
    netIncome: "Net Income", revenue: "Revenue", expenses: "Expenses",
    totalDebit: "Total Debit", totalCredit: "Total Credit",
    reportWorkspace: "Report Workspace",
    financialIntelligence: "Financial Intelligence",
    reportHistory: "Report History",
    selectReport: "Select a report to begin",
    selectReportBody: "Choose a category and report from the left to load live data.",
    notAvailableTitle: "Report not yet available",
    noData: "No data available for the selected project and period.",
    category: "Category", variance: "Variance", forecast: "Forecast",
    date: "Date", opening: "Opening", inflow: "Inflow", outflow: "Outflow",
    closing: "Closing", account: "Account", debit: "Debit", credit: "Credit",
    budgetLine: "Budget Line", allocated: "Allocated", spent: "Spent",
    print: "Print", exportPdf: "Export PDF", exportExcel: "Export Excel",
    download: "Download", noHistory: "No reports have been generated yet.",
    healthy: "Healthy", watch: "Watch", critical: "Critical",
    exportRecorded: "Export recorded",
    // report names (catalogue)
    rptMonthly: "Monthly Financial Report",
    rptQuarterly: "Quarterly Report",
    rptSemiannual: "Semi-Annual Report",
    rptAnnual: "Annual Report",
    rptBudgetVsActual: "Budget vs Actual",
    rptCashFlow: "Cash Flow Statement",
    rptIncomeStatement: "Income Statement",
    rptBalanceSheet: "Balance Sheet",
    rptTrialBalance: "Trial Balance",
    rptExecutiveSummary: "Executive Summary",
    rptGLSummary: "GL Account Summary",
    rptGrantFinancial: "Grant Financial Report",
    rptBudgetPerformance: "Budget Performance",
    rptDonorUtilization: "Donor Utilization",
    rptDonorExpenditure: "Donor Expenditure",
    rptCostShare: "Cost Share Report",
    rptGrantClosure: "Grant Closure Report",
    rptCashPosition: "Cash Position",
    rptCommitments: "Commitments",
    rptRevenueAnalysis: "Revenue Analysis",
    rptExpenseAnalysis: "Expense Analysis",
    rptCostCenter: "Cost Center Report",
    rptOUPerformance: "Operating Unit Performance",
    rptProjectPerformance: "Project Performance",
    rptForecastVsActual: "Forecast vs Actual",
    rptProcurementCompliance: "Procurement Compliance",
    rptAuditFindings: "Audit Findings",
    rptFinancialRisks: "Financial Risks",
    rptComplianceSummary: "Compliance Summary",
    rptBudgetCompliance: "Budget Compliance",
    rptJournalValidation: "Journal Validation",
    rptExecFinancialSummary: "Executive Financial Summary",
    rptOrgSummary: "Organization Summary",
    rptConsolidated: "Consolidated Report",
    rptFinancialKpis: "Financial KPIs",
    rptDashboardSummary: "Dashboard Summary",
  },
  ar: {
    pageTitle: "مركز التقارير المالية",
    pageSubtitle: "التقارير المالية المباشرة عبر محفظة المنظمة",
    project: "المشروع", allProjects: "جميع المشاريع",
    fiscalYear: "السنة المالية", reportingPeriod: "فترة الإبلاغ",
    monthly: "شهري", quarterly: "ربع سنوي", semiAnnual: "نصف سنوي",
    annual: "سنوي", custom: "فترة مخصصة",
    periodFrom: "من", periodTo: "إلى",
    financialStatements: "البيانات المالية", donorReports: "تقارير المانحين",
    managementReports: "تقارير الإدارة", complianceReports: "تقارير الامتثال",
    executiveReports: "التقارير التنفيذية",
    donor: "المانح", grant: "المنحة", operatingUnit: "وحدة التشغيل",
    generated: "تم الإنشاء", generatedBy: "تم الإنشاء بواسطة", reportStatus: "الحالة",
    lastRefreshed: "آخر تحديث", period: "الفترة",
    executiveSummary: "الملخص التنفيذي",
    budget: "الميزانية", actual: "النفقات الفعلية", remaining: "الميزانية المتبقية",
    burnRate: "معدل الإنفاق", utilization: "استخدام الميزانية",
    financialHealth: "الصحة المالية", commitments: "الالتزامات المعلقة",
    majorVariances: "الفروقات الرئيسية",
    available: "متاح", openingBalance: "الرصيد الافتتاحي",
    operatingCash: "النقد التشغيلي", investingCash: "نقد الاستثمار",
    financingCash: "نقد التمويل", closingBalance: "الرصيد الختامي",
    assets: "الأصول", liabilities: "الالتزامات", equity: "حقوق الملكية",
    workingCapital: "رأس المال العامل", currentRatio: "النسبة الحالية",
    netIncome: "صافي الدخل", revenue: "الإيرادات", expenses: "النفقات",
    totalDebit: "إجمالي الخصم", totalCredit: "إجمالي الائتمان",
    reportWorkspace: "مساحة عمل التقرير",
    financialIntelligence: "الذكاء المالي",
    reportHistory: "سجل التقارير",
    selectReport: "حدد تقرير للبدء",
    selectReportBody: "اختر فئة وتقرير من اليسار لتحميل البيانات المباشرة.",
    notAvailableTitle: "التقرير غير متاح حالياً",
    noData: "لا توجد بيانات متاحة للمشروع والفترة المحددة.",
    category: "الفئة", variance: "الفرق", forecast: "التنبؤ",
    date: "التاريخ", opening: "الافتتاح", inflow: "التدفق الداخلي", outflow: "التدفق الخارجي",
    closing: "الإغلاق", account: "الحساب", debit: "خصم", credit: "ائتمان",
    budgetLine: "بند الميزانية", allocated: "مخصص", spent: "منفق",
    print: "طباعة", exportPdf: "تصدير PDF", exportExcel: "تصدير Excel",
    download: "تحميل", noHistory: "لم يتم إنشاء أي تقارير حتى الآن.",
    healthy: "صحي", watch: "مراقبة", critical: "حرج",
    exportRecorded: "تم تسجيل التصدير",
  },
  it: {
    pageTitle: "Centro Reporting Finanziario",
    pageSubtitle: "Rapporti finanziari in tempo reale su tutto il portafoglio organizzativo",
    project: "Progetto", allProjects: "Tutti i Progetti",
    fiscalYear: "Anno Fiscale", reportingPeriod: "Periodo di Rendicontazione",
    monthly: "Mensile", quarterly: "Trimestrale", semiAnnual: "Semestrale",
    annual: "Annuale", custom: "Periodo Personalizzato",
    periodFrom: "Dal", periodTo: "Al",
    financialStatements: "Bilanci Finanziari", donorReports: "Report dei Donatori",
    managementReports: "Report Gestionali", complianceReports: "Report di Conformità",
    executiveReports: "Report Esecutivi",
    donor: "Donatore", grant: "Sovvenzione", operatingUnit: "Unità Operativa",
    generated: "Generato", generatedBy: "Generato da", reportStatus: "Stato",
    lastRefreshed: "Ultimo Aggiornamento", period: "Periodo",
    executiveSummary: "Sintesi Esecutiva",
    budget: "Budget", actual: "Spesa Effettiva", remaining: "Budget Residuo",
    burnRate: "Tasso di Spesa", utilization: "Utilizzo del Budget",
    financialHealth: "Salute Finanziaria", commitments: "Impegni in Sospeso",
    majorVariances: "Scostamenti Principali",
    available: "Disponibile", openingBalance: "Saldo di Apertura",
    operatingCash: "Cassa Operativa", investingCash: "Cassa da Investimenti",
    financingCash: "Cassa da Finanziamenti", closingBalance: "Saldo di Chiusura",
    assets: "Attività", liabilities: "Passività", equity: "Patrimonio Netto",
    workingCapital: "Capitale Circolante", currentRatio: "Indice di Liquidità",
    netIncome: "Reddito Netto", revenue: "Ricavi", expenses: "Spese",
    totalDebit: "Totale Dare", totalCredit: "Totale Avere",
    reportWorkspace: "Area di Lavoro Report",
    financialIntelligence: "Intelligence Finanziaria",
    reportHistory: "Cronologia Report",
    selectReport: "Seleziona un report per iniziare",
    selectReportBody: "Scegli una categoria e un report dalla barra laterale per caricare i dati in tempo reale.",
    notAvailableTitle: "Report non ancora disponibile",
    noData: "Nessun dato disponibile per il progetto e il periodo selezionati.",
    category: "Categoria", variance: "Scostamento", forecast: "Previsione",
    date: "Data", opening: "Apertura", inflow: "Entrate", outflow: "Uscite",
    closing: "Chiusura", account: "Conto", debit: "Dare", credit: "Avere",
    budgetLine: "Voce di Budget", allocated: "Allocato", spent: "Speso",
    print: "Stampa", exportPdf: "Esporta PDF", exportExcel: "Esporta Excel",
    download: "Scarica", noHistory: "Nessun report è stato ancora generato.",
    healthy: "Sano", watch: "Attenzione", critical: "Critico",
    exportRecorded: "Esportazione registrata",
    rptMonthly: "Report Finanziario Mensile",
    rptQuarterly: "Report Trimestrale",
    rptSemiannual: "Report Semestrale",
    rptAnnual: "Report Annuale",
    rptBudgetVsActual: "Budget vs Consuntivo",
    rptCashFlow: "Rendiconto Finanziario",
    rptIncomeStatement: "Conto Economico",
    rptBalanceSheet: "Stato Patrimoniale",
    rptTrialBalance: "Bilancio di Verifica",
    rptExecutiveSummary: "Sintesi Esecutiva",
    rptGrantFinancial: "Report Finanziario della Sovvenzione",
    rptBudgetPerformance: "Performance del Budget",
    rptCashPosition: "Posizione di Cassa",
    rptCommitments: "Impegni",
    rptRevenueAnalysis: "Analisi dei Ricavi",
    rptExpenseAnalysis: "Analisi delle Spese",
    rptCostCenter: "Performance del Centro di Costo",
    rptOUPerformance: "Performance dell'Unità Operativa",
    rptProjectPerformance: "Performance Finanziaria del Progetto",
    rptForecastVsActual: "Previsione vs Consuntivo",
    rptProcurementCompliance: "Conformità degli Acquisti",
    rptAuditFindings: "Risultati dell'Audit",
    rptFinancialRisks: "Rischi Finanziari",
    rptComplianceSummary: "Riepilogo Conformità",
    rptBudgetCompliance: "Conformità del Budget",
    rptJournalValidation: "Validazione delle Registrazioni",
    rptExecFinancialSummary: "Sintesi Finanziaria Esecutiva",
    rptOrgSummary: "Riepilogo dell'Organizzazione",
    rptConsolidated: "Bilancio Consolidato",
    rptGLSummary: "Riepilogo Libro Mastro",
    rptDonorUtilization: "Utilizzo del Budget del Donatore",
    rptDonorExpenditure: "Analisi delle Spese del Donatore",
    rptCostShare: "Report di Cofinanziamento",
    rptGrantClosure: "Report di Chiusura della Sovvenzione",
    rptFinancialKpis: "KPI Finanziari",
    rptDashboardSummary: "Riepilogo Dashboard Finanziaria",
  },
};

type Lang = "en" | "ar" | "it";

// ─── Report catalogue ───────────────────────────────────────────────────────
type GroupKey = "financialStatements" | "donor" | "management" | "compliance" | "executive";

interface CatalogueGroup {
  group: GroupKey;
  titleKey: keyof typeof T.en;
  icon: React.ElementType;
  reports: { id: string; titleKey: keyof typeof T.en }[];
}

const CATALOGUE: CatalogueGroup[] = [
  {
    group: "financialStatements", titleKey: "financialStatements", icon: FileBarChart,
    reports: [
      { id: "monthly", titleKey: "rptMonthly" },
      { id: "quarterly", titleKey: "rptQuarterly" },
      { id: "semiannual", titleKey: "rptSemiannual" },
      { id: "annual", titleKey: "rptAnnual" },
      { id: "budget-vs-actual", titleKey: "rptBudgetVsActual" },
      { id: "cash-flow", titleKey: "rptCashFlow" },
      { id: "income-statement", titleKey: "rptIncomeStatement" },
      { id: "balance-sheet", titleKey: "rptBalanceSheet" },
      { id: "trial-balance", titleKey: "rptTrialBalance" },
      { id: "gl-summary", titleKey: "rptGLSummary" },
      { id: "executive-summary", titleKey: "rptExecutiveSummary" },
    ],
  },
  {
    group: "donor", titleKey: "donorReports", icon: Users,
    reports: [
      { id: "grant-financial", titleKey: "rptGrantFinancial" },
      { id: "budget-performance", titleKey: "rptBudgetPerformance" },
      { id: "donor-utilization", titleKey: "rptDonorUtilization" },
      { id: "donor-expenditure", titleKey: "rptDonorExpenditure" },
      { id: "cost-share", titleKey: "rptCostShare" },
      { id: "grant-closure", titleKey: "rptGrantClosure" },
    ],
  },
  {
    group: "management", titleKey: "managementReports", icon: LayoutList,
    reports: [
      { id: "cash-position", titleKey: "rptCashPosition" },
      { id: "commitments", titleKey: "rptCommitments" },
      { id: "revenue-analysis", titleKey: "rptRevenueAnalysis" },
      { id: "expense-analysis", titleKey: "rptExpenseAnalysis" },
      { id: "cost-center", titleKey: "rptCostCenter" },
      { id: "ou-performance", titleKey: "rptOUPerformance" },
      { id: "project-performance", titleKey: "rptProjectPerformance" },
      { id: "forecast-vs-actual", titleKey: "rptForecastVsActual" },
    ],
  },
  {
    group: "compliance", titleKey: "complianceReports", icon: ShieldCheck,
    reports: [
      { id: "budget-compliance", titleKey: "rptBudgetCompliance" },
      { id: "journal-validation", titleKey: "rptJournalValidation" },
      { id: "procurement-compliance", titleKey: "rptProcurementCompliance" },
      { id: "audit-findings", titleKey: "rptAuditFindings" },
      { id: "financial-risks", titleKey: "rptFinancialRisks" },
      { id: "compliance-summary", titleKey: "rptComplianceSummary" },
    ],
  },
  {
    group: "executive", titleKey: "executiveReports", icon: Globe,
    reports: [
      { id: "exec-financial-summary", titleKey: "rptExecFinancialSummary" },
      { id: "org-summary", titleKey: "rptOrgSummary" },
      { id: "consolidated", titleKey: "rptConsolidated" },
      { id: "financial-kpis", titleKey: "rptFinancialKpis" },
      { id: "dashboard-summary", titleKey: "rptDashboardSummary" },
    ],
  },
];

const GROUP_BY_REPORT: Record<string, GroupKey> = Object.fromEntries(
  CATALOGUE.flatMap((g) => g.reports.map((r) => [r.id, g.group])),
);

// ─── Number helpers ─────────────────────────────────────────────────────────
const n = (v: unknown): number => {
  const x = Number(v ?? 0);
  return isNaN(x) ? 0 : x;
};
const money = (v: unknown, currency = "USD") => compactCurrency(n(v), currency);
const pct = (v: unknown) => `${n(v).toFixed(1)}%`;

// ─── KPI registry ───────────────────────────────────────────────────────────
interface KpiSpec {
  label: keyof typeof T.en;
  icon: React.ElementType;
  value: (data: any, currency: string) => string;
  progress?: (data: any) => number | undefined;
}

const KPI_REGISTRY: Record<string, KpiSpec[]> = {
  _budget: [
    { label: "budget", icon: Wallet, value: (d, c) => money(d?.summary?.totalBudget ?? d?.data?.reduce?.((s: number, r: any) => s + n(r.budgeted), 0), c) },
    { label: "actual", icon: TrendingUp, value: (d, c) => money(d?.summary?.totalActual ?? d?.summary?.totalExpenses, c) },
    { label: "available", icon: Landmark, value: (d, c) => money(n(d?.summary?.totalBudget) - n(d?.summary?.totalActual), c) },
    { label: "variance", icon: Activity, value: (d, c) => money(d?.summary?.totalVariance ?? d?.summary?.budgetVariance, c) },
    { label: "utilization", icon: Activity, value: (d) => pct(d?.summary?.totalBudget ? (n(d.summary.totalActual) / n(d.summary.totalBudget)) * 100 : 0), progress: (d) => d?.summary?.totalBudget ? (n(d.summary.totalActual) / n(d.summary.totalBudget)) * 100 : 0 },
  ],
  "cash-flow": [
    { label: "openingBalance", icon: Wallet, value: (d, c) => money(d?.beginningBalance, c) },
    { label: "operatingCash", icon: Activity, value: (d, c) => money(d?.operatingActivities?.totalOperating, c) },
    { label: "investingCash", icon: TrendingUp, value: (d, c) => money(d?.investingActivities?.totalInvesting, c) },
    { label: "financingCash", icon: Landmark, value: (d, c) => money(d?.financingActivities?.totalFinancing, c) },
    { label: "closingBalance", icon: Wallet, value: (d, c) => money(d?.endingBalance, c) },
  ],
  "balance-sheet": [
    { label: "assets", icon: Building2, value: (d, c) => money(d?.assets?.totalAssets, c) },
    { label: "liabilities", icon: Landmark, value: (d, c) => money(d?.liabilities?.totalLiabilities, c) },
    { label: "equity", icon: Wallet, value: (d, c) => money(d?.equity?.totalEquity, c) },
    { label: "workingCapital", icon: Activity, value: (d, c) => money(n(d?.assets?.current?.[0]?.amount) - n(d?.liabilities?.current?.[0]?.amount), c) },
  ],
  "income-statement": [
    { label: "revenue", icon: TrendingUp, value: (d, c) => money(d?.revenue?.totalRevenue, c) },
    { label: "expenses", icon: Activity, value: (d, c) => money(d?.expenses?.totalExpenses, c) },
    { label: "netIncome", icon: Wallet, value: (d, c) => money(d?.netIncome, c) },
  ],
  "trial-balance": [
    { label: "totalDebit", icon: Activity, value: (d, c) => money(d?.totals?.totalDebit, c) },
    { label: "totalCredit", icon: Activity, value: (d, c) => money(d?.totals?.totalCredit, c) },
  ],
  monthly: [
    { label: "revenue", icon: TrendingUp, value: (d, c) => money(d?.summary?.totalRevenue, c) },
    { label: "expenses", icon: Activity, value: (d, c) => money(d?.summary?.totalExpenses, c) },
    { label: "netIncome", icon: Wallet, value: (d, c) => money(d?.summary?.netIncome, c) },
    { label: "variance", icon: Activity, value: (d, c) => money(d?.summary?.budgetVariance, c) },
  ],
};

function kpiSpecFor(reportId: string): KpiSpec[] {
  if (KPI_REGISTRY[reportId]) return KPI_REGISTRY[reportId];
  if (["budget-vs-actual", "quarterly", "semiannual", "annual", "budget-performance", "budget-compliance"].includes(reportId))
    return KPI_REGISTRY._budget;
  if (["executive-summary", "exec-financial-summary", "commitments"].includes(reportId))
    return KPI_REGISTRY.monthly;
  return KPI_REGISTRY._budget;
}

// ─── Main component ─────────────────────────────────────────────────────────
export function FinanceReportingCenter() {
  const { language } = useLanguage();
  const lang: Lang = language === "ar" ? "ar" : language === "it" ? "it" : "en";
  const t = T[lang];

  const [reportId, setReportId] = useState<string | null>("monthly");
  const [openGroups, setOpenGroups] = useState<Record<string, boolean>>({
    "financialStatements": true, donor: false, management: false, compliance: false, executive: false,
  });

  // ─── Filter State ────────────────────────────────────────────────────────
  const [fiscalYear, setFiscalYear] = useState<string>("2025");
  const [projectId, setProjectId] = useState<number | undefined>(undefined);

  // ─── Fetch Filter Metadata (real SQL) ────────────────────────────────────
  const filterMeta = trpc.financialReports.getFilterMeta.useQuery(undefined, {
    staleTime: 5 * 60 * 1000,
  });

  // ─── Build Filter Input ──────────────────────────────────────────────────
  const filterInput = {
    reportId: reportId || "monthly",
    fiscalYear,
    currency: "USD",
    projectIds: projectId ? [projectId] : undefined,
  };

  // ─── Fetch Report Data (real SQL) ────────────────────────────────────────
  const reportQ = trpc.financialReports.generateReport.useQuery(filterInput, {
    enabled: !!reportId,
  });

  // ─── Fetch Financial Intelligence (real insights) ──────────────────────
  const aiQ = trpc.financialReports.getFinancialIntelligence.useQuery({
    projectIds: filterInput.projectIds,
    fiscalYear,
  });

  // ─── Fetch Export History ────────────────────────────────────────────────
  const historyQ = trpc.financialReports.getExportHistory.useQuery();

  // ─── Log Generated Report Mutation ───────────────────────────────────────
  const logMutation = trpc.financialReports.logGeneratedReport.useMutation();

  // ─── Handle Export ───────────────────────────────────────────────────────
  const handleExport = useCallback(
    (format: "PDF" | "XLSX") => {
      logMutation.mutate(
        {
          reportType: reportId || "monthly",
          fileName: `${reportId}-${fiscalYear}.${format === "PDF" ? "pdf" : "xlsx"}`,
          filePath: `finance-reporting://${reportId}/${fiscalYear}`,
          format,
        },
        {
          onSuccess: () => historyQ.refetch(),
        }
      );
    },
    [reportId, fiscalYear, logMutation, historyQ]
  );

  // ─── Build Filter Dropdowns ──────────────────────────────────────────────
  const filterDropdowns: FilterDropdown[] = [
    {
      id: "project",
      label: t.project,
      minWidth: "240px",
      value: projectId ? String(projectId) : "",
      onChange: (v) => setProjectId(v ? Number(v) : undefined),
      options: [
        ...(filterMeta.data?.projects ?? []).map((p) => ({
          value: String(p.id),
          label: `${p.projectCode} — ${p.title}`,
        })),
        { value: "", label: t.allProjects },
      ],
    },
    {
      id: "fiscalYear",
      label: t.fiscalYear,
      minWidth: "120px",
      value: fiscalYear,
      onChange: (v) => setFiscalYear(v),
      options: (filterMeta.data?.fiscalYears ?? []).map((fy) => ({
        label: fy.label,
        value: fy.value,
      })),
    },
  ];

  // ─── Render ──────────────────────────────────────────────────────────────
  return (
    <div className="flex h-full flex-col gap-4 bg-[#f5f7fb] p-4" dir={lang === "ar" ? "rtl" : "ltr"}>
      {/* Page Header */}
      <div className="flex items-end justify-between gap-4">
        <div>
          <h1 className="text-[20px] font-semibold text-slate-800">{t.pageTitle}</h1>
          <p className="text-[11px] text-slate-500">{t.pageSubtitle}</p>
        </div>
      </div>

      {/* Filter Bar */}
      <div className="flex flex-wrap items-end gap-3">
        <div className="min-w-0 flex-1">
          <FinanceFilterBar dropdowns={filterDropdowns} />
        </div>
      </div>

      {/* Main Content */}
      <div className="flex flex-1 gap-4 overflow-hidden">
        {/* Left Sidebar: Report Catalogue */}
        <div className="w-64 flex-shrink-0 overflow-y-auto rounded-lg bg-white p-4 shadow-sm">
          {CATALOGUE.map((cat) => (
            <div key={cat.group} className="mb-4">
              <button
                onClick={() =>
                  setOpenGroups((g) => ({ ...g, [cat.group]: !g[cat.group] }))
                }
                className="flex w-full items-center gap-2 rounded px-2 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-100"
              >
                {openGroups[cat.group] ? (
                  <ChevronDown className="h-4 w-4" />
                ) : (
                  <ChevronRight className="h-4 w-4" />
                )}
                {t[cat.titleKey]}
              </button>
              {openGroups[cat.group] && (
                <div className="space-y-1 pl-6">
                  {cat.reports.map((r) => (
                    <button
                      key={r.id}
                      onClick={() => setReportId(r.id)}
                      className={`block w-full text-left rounded px-2 py-1.5 text-xs font-medium transition ${
                        reportId === r.id
                          ? "bg-blue-100 text-blue-700"
                          : "text-slate-600 hover:bg-slate-100"
                      }`}
                    >
                      {t[r.titleKey]}
                    </button>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Right Content: Report Workspace */}
        <div className="flex-1 overflow-y-auto">
          {!reportId ? (
            <FinanceCard>
              <EmptyState
                title={t.selectReport}
                message={t.selectReportBody}
              />
            </FinanceCard>
          ) : (
            <ReportView
              reportId={reportId}
              group={GROUP_BY_REPORT[reportId]}
              filterInput={filterInput}
              reportQ={reportQ}
              aiQ={aiQ}
              historyQ={historyQ}
              onExport={handleExport}
              onRetry={() => reportQ.refetch()}
              lang={lang}
              t={t}
            />
          )}
        </div>
      </div>
    </div>
  );
}

// ─── Report View Component ───────────────────────────────────────────────────
function ReportView({
  reportId,
  group,
  filterInput,
  reportQ,
  aiQ,
  historyQ,
  onExport,
  onRetry,
  lang,
  t,
}: {
  reportId: string;
  group: GroupKey;
  filterInput: any;
  reportQ: any;
  aiQ: any;
  historyQ: any;
  onExport: (format: "PDF" | "XLSX") => void;
  onRetry: () => void;
  lang: Lang;
  t: any;
}) {
  const reportTitleKey = CATALOGUE.flatMap((g) => g.reports).find(
    (r) => r.id === reportId
  )?.titleKey;
  const reportTitle = reportTitleKey ? t[reportTitleKey] : reportId;

  const envelope = reportQ.data;
  const payload = envelope?.data;
  const metadata = payload?.metadata;

  // ─── Handle Loading States ───────────────────────────────────────────────
  if (reportQ.isLoading) {
    return (
      <FinanceCard>
        <LoadingSkeleton />
      </FinanceCard>
    );
  }

  // ─── Handle Errors ──────────────────────────────────────────────────────
  if (reportQ.error) {
    return (
      <FinanceCard>
        <ErrorState message={reportQ.error.message || "Failed to load report"} onRetry={onRetry} />
      </FinanceCard>
    );
  }

  // ─── Handle Not Implemented ─────────────────────────────────────────────
  if (envelope?.status === "not_implemented") {
    return (
      <FinanceCard>
        <EmptyState title={t.notAvailableTitle} />
      </FinanceCard>
    );
  }

  // ─── Handle Report Errors ───────────────────────────────────────────────
  if (envelope?.status === "error") {
    return (
      <FinanceCard>
        <ErrorState message={envelope.message || "Report generation failed"} onRetry={onRetry} />
      </FinanceCard>
    );
  }

  // ─── Handle No Data ─────────────────────────────────────────────────────
  if (!envelope?.data) {
    return (
      <FinanceCard>
        <EmptyState title={t.noData} />
      </FinanceCard>
    );
  }

  const isLoading = reportQ.isLoading;
  const ok = envelope?.status === "ok" && !!payload;

  // ─── Render Report ──────────────────────────────────────────────────────
  return (
    <div className="flex flex-col gap-4" dir={lang === "ar" ? "rtl" : "ltr"}>
      {/* Report header */}
      <FinanceCard>
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div className="min-w-0">
            <div className="mb-1 flex items-center gap-2">
              <span className="rounded bg-[#003b70]/10 px-2 py-0.5 text-[10px] font-bold uppercase tracking-widest text-[#003b70]">
                {t[CATALOGUE.find((g) => g.group === group)!.titleKey]}
              </span>
              {metadata?.status && <StatusPill status={metadata.status} />}
            </div>
            <h2 className="text-[18px] font-bold text-slate-900">{reportTitle}</h2>
          </div>
          {/* Actions */}
          <div className="flex flex-wrap items-center gap-2">
            <button
              onClick={() => window.print()}
              className="inline-flex items-center gap-1.5 rounded-lg border border-slate-300 bg-white px-3.5 py-2 text-[12px] font-semibold text-slate-700 transition-colors hover:bg-slate-50"
            >
              <Printer className="h-4 w-4" /> {t.print}
            </button>
            <button
              onClick={() => onExport("XLSX")}
              disabled={!ok}
              className="inline-flex items-center gap-1.5 rounded-lg border border-slate-300 bg-white px-3.5 py-2 text-[12px] font-semibold text-slate-700 transition-colors hover:bg-slate-50 disabled:opacity-50"
            >
              <Download className="h-4 w-4" /> {t.exportExcel}
            </button>
            <button
              onClick={() => onExport("PDF")}
              disabled={!ok}
              className="inline-flex items-center gap-1.5 rounded-lg bg-[#003b70] px-3.5 py-2 text-[12px] font-bold text-white transition-colors hover:bg-[#002a55] disabled:opacity-50"
            >
              <Download className="h-4 w-4" /> {t.exportPdf}
            </button>
          </div>
        </div>
      </FinanceCard>

      {/* Executive Summary */}
      <ExecutiveSummary
        reportId={reportId} payload={payload} currency={filterInput.currency}
        isLoading={isLoading} lang={lang}
      />

      {/* KPI strip */}
      <KpiStrip reportId={reportId} payload={payload} currency={filterInput.currency} isLoading={isLoading} lang={lang} />

      {/* Report Body */}
      <ReportBody reportId={reportId} payload={payload} currency={filterInput.currency} isLoading={isLoading} lang={lang} />

      {/* Financial Intelligence */}
      <FinanceCard noPadding>
        <WidgetHeader title={t.financialIntelligence} icon={<Bot className="h-4 w-4" />} />
        <div className="p-4">
          {aiQ.isLoading ? (
            <LoadingSkeleton variant="list" rows={3} />
          ) : aiQ.data?.insights?.length === 0 ? (
            <EmptyState
              title={t.financialIntelligence}
              message={aiQ.data?.explanation ?? t.noData}
              className="py-8"
            />
          ) : (
            <div className="space-y-2">
              {aiQ.data?.insights?.map((ins: any) => {
                const tone =
                  ins.severity === "critical" ? "border-red-100 bg-red-50 text-red-900"
                  : ins.severity === "warning" ? "border-amber-100 bg-amber-50 text-amber-900"
                  : "border-blue-100 bg-blue-50 text-blue-900";
                const badge =
                  ins.severity === "critical" ? "bg-red-200 text-red-900"
                  : ins.severity === "warning" ? "bg-amber-200 text-amber-900"
                  : "bg-blue-200 text-blue-900";
                return (
                  <div key={ins.id} className={`rounded border p-2.5 ${tone}`}>
                    <div className="flex items-center justify-between gap-2">
                      <p className="text-[12px] font-semibold">{ins.title}</p>
                      <span className={`shrink-0 rounded px-2 py-0.5 text-[10px] font-bold ${badge}`}>
                        {ins.category}
                      </span>
                    </div>
                    <p className="mt-0.5 text-[10px] opacity-80">{ins.detail}</p>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </FinanceCard>

      {/* Report History */}
      <FinanceCard noPadding>
        <WidgetHeader title={t.reportHistory} icon={<Clock className="h-4 w-4" />} />
        <div className="p-4">
          {historyQ.isLoading ? (
            <LoadingSkeleton variant="list" rows={3} />
          ) : historyQ.data?.length === 0 ? (
            <EmptyState title={t.reportHistory} message={t.noHistory} className="py-8" />
          ) : (
            <div className="space-y-1.5">
              {historyQ.data?.slice(0, 6).map((h: any) => (
                <div key={h.id} className="flex items-center justify-between rounded bg-slate-50 px-3 py-2 text-[11px]">
                  <span className="truncate font-medium text-slate-700">{h.fileName}</span>
                  <span className="flex items-center gap-3 text-slate-400">
                    <span>{new Date(h.generatedAt).toLocaleDateString()}</span>
                    <span className="font-mono uppercase">{h.mimeType?.includes("pdf") ? "PDF" : "XLSX"}</span>
                  </span>
                </div>
              ))}
            </div>
          )}
        </div>
      </FinanceCard>
    </div>
  );
}

// ─── Executive Summary ───────────────────────────────────────────────────────
function ExecutiveSummary({
  reportId, payload, currency, isLoading, lang,
}: { reportId: string; payload: any; currency: string; isLoading: boolean; lang: Lang }) {
  const t = T[lang];

  const summary = useMemo(() => {
    if (!payload) return null;
    const totalBudget =
      n(payload?.summary?.totalBudget) ||
      (Array.isArray(payload?.data) ? payload.data.reduce((s: number, r: any) => s + n(r.budgeted), 0) : 0);
    const totalActual =
      n(payload?.summary?.totalActual) || n(payload?.summary?.totalExpenses) ||
      (Array.isArray(payload?.data) ? payload.data.reduce((s: number, r: any) => s + n(r.actual), 0) : 0);
    const remaining = totalBudget - totalActual;
    const utilization = totalBudget > 0 ? (totalActual / totalBudget) * 100 : 0;
    const commitments = Array.isArray(payload?.sections?.commitments)
      ? payload.sections.commitments.reduce((s: number, r: any) => s + n(r.amount), 0)
      : 0;
    const variances = Array.isArray(payload?.data)
      ? payload.data.filter((r: any) => Math.abs(n(r.variancePercent)) > 10).length
      : 0;
    const health = utilization > 100 ? "critical" : utilization > 90 ? "watch" : "healthy";
    return { totalBudget, totalActual, remaining, utilization, commitments, variances, health };
  }, [payload]);

  if (isLoading) {
    return (
      <FinanceCard noPadding>
        <WidgetHeader title={t.executiveSummary} icon={<FileText className="h-4 w-4" />} />
        <div className="p-4"><LoadingSkeleton variant="text" rows={3} /></div>
      </FinanceCard>
    );
  }
  if (!summary || (!summary.totalBudget && !summary.totalActual)) return null;

  const healthColor =
    summary.health === "critical" ? FINANCE_COLORS.critical
    : summary.health === "watch" ? FINANCE_COLORS.warning
    : FINANCE_COLORS.success;
  const healthLabel =
    summary.health === "critical" ? t.critical : summary.health === "watch" ? t.watch : t.healthy;

  const cells: { label: string; value: string; color?: string }[] = [
    { label: t.budget, value: money(summary.totalBudget, currency) },
    { label: t.actual, value: money(summary.totalActual, currency) },
    { label: t.remaining, value: money(summary.remaining, currency), color: summary.remaining < 0 ? FINANCE_COLORS.critical : undefined },
    { label: t.utilization, value: pct(summary.utilization) },
    { label: t.commitments, value: money(summary.commitments, currency) },
    { label: t.financialHealth, value: healthLabel, color: healthColor },
  ];

  return (
    <FinanceCard noPadding>
      <WidgetHeader title={t.executiveSummary} icon={<FileText className="h-4 w-4" />} />
      <div className="grid grid-cols-2 gap-px bg-slate-100 sm:grid-cols-3 lg:grid-cols-6">
        {cells.map((c) => (
          <div key={c.label} className="bg-white p-3">
            <p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">{c.label}</p>
            <p className="mt-1 font-mono text-[16px] font-bold" style={{ color: c.color ?? FINANCE_COLORS.navy }} dir="ltr">
              {c.value}
            </p>
          </div>
        ))}
      </div>
    </FinanceCard>
  );
}

// ─── KPI strip ──────────────────────────────────────────────────────────────
function KpiStrip({
  reportId, payload, currency, isLoading, lang,
}: { reportId: string; payload: any; currency: string; isLoading: boolean; lang: Lang }) {
  const t = T[lang];
  const specs = kpiSpecFor(reportId);

  if (isLoading) {
    return (
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
        {Array.from({ length: specs.length }).map((_, i) => (
          <FinanceCard key={i} noPadding className="p-3"><LoadingSkeleton variant="kpi" /></FinanceCard>
        ))}
      </div>
    );
  }
  if (!payload) return null;
  if (Array.isArray(payload?.columns) && !payload?.summary) return null;

  return (
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
      {specs.map((s) => (
        <FinanceKpiCard
          key={s.label}
          label={t[s.label]}
          value={s.value(payload, currency)}
          icon={s.icon}
          progressValue={s.progress?.(payload)}
        />
      ))}
    </div>
  );
}

// ─── Report body ────────────────────────────────────────────────────────────
function ReportBody({
  reportId, payload, currency, isLoading, lang,
}: { reportId: string; payload: any; currency: string; isLoading: boolean; lang: Lang }) {
  const t = T[lang];

  const isBudgetFamily =
    ["budget-vs-actual", "quarterly", "semiannual", "annual", "budget-performance", "budget-compliance", "project-performance"].includes(reportId);

  if (reportId === "cash-flow" || reportId === "cash-position") return <CashFlowBody payload={payload} currency={currency} isLoading={isLoading} lang={lang} />;
  if (reportId === "trial-balance" || reportId === "journal-validation")
    return <TrialBalanceBody payload={payload} currency={currency} isLoading={isLoading} lang={lang} />;
  if (reportId === "balance-sheet" || reportId === "org-summary" || reportId === "consolidated")
    return <BalanceSheetBody payload={payload} currency={currency} isLoading={isLoading} lang={lang} />;
  if (reportId === "income-statement" || reportId === "revenue-analysis")
    return <IncomeStatementBody payload={payload} currency={currency} isLoading={isLoading} lang={lang} />;
  if (isBudgetFamily) return <BudgetVsActualBody payload={payload} currency={currency} isLoading={isLoading} lang={lang} />;

  if (Array.isArray(payload?.columns)) return <GenericReportBody payload={payload} currency={currency} isLoading={isLoading} lang={lang} />;

  return <MonthlyBody payload={payload} currency={currency} isLoading={isLoading} lang={lang} />;
}

// Budget vs Actual
function BudgetVsActualBody({ payload, currency, isLoading, lang }: BodyProps) {
  const t = T[lang];
  const rows = (payload?.data ?? []) as any[];
  const chartData = rows.slice(0, 12).map((r) => ({
    name: String(r.category ?? "—").split(" ").slice(0, 2).join(" "),
    Budget: n(r.budgeted), Actual: n(r.actual), Forecast: n(r.forecast ?? r.actual),
  }));
  const cols: TableColumn<any>[] = [
    { key: "category", label: t.category, sortable: true },
    { key: "budgeted", label: t.budget, align: "end", ltr: true, render: (r) => money(r.budgeted, currency) },
    { key: "actual", label: t.actual, align: "end", ltr: true, render: (r) => money(r.actual, currency) },
    { key: "variance", label: t.variance, align: "end", ltr: true, render: (r) => <span style={{ color: n(r.variance) < 0 ? FINANCE_COLORS.critical : FINANCE_COLORS.success }}>{money(r.variance, currency)}</span> },
    { key: "forecast", label: t.forecast, align: "end", ltr: true, render: (r) => money(r.forecast, currency) },
  ];
  return (
    <div className="grid gap-4">
      <ChartWrapper title={t.budget + " vs " + t.actual} icon={<TrendingUp className="h-4 w-4" />}
        isLoading={isLoading} isEmpty={chartData.length === 0} emptyMessage={t.noData} chartHeight="h-[320px]">
        <ResponsiveContainer width="100%" height="100%">
          <ComposedChart data={chartData} margin={{ top: 8, right: 12, left: 0, bottom: 4 }}>
            <CartesianGrid stroke="#e7ebf0" vertical={false} />
            <XAxis dataKey="name" tick={{ fontSize: 11 }} />
            <YAxis tick={{ fontSize: 11 }} tickFormatter={(v) => compactCurrency(v, currency)} />
            <Tooltip formatter={(v: number) => compactCurrency(v, currency)} contentStyle={{ borderRadius: 8, border: "1px solid #e7ebf0", fontSize: 11 }} />
            <Legend wrapperStyle={{ fontSize: 11 }} />
            <Bar dataKey="Budget" fill={CHART_COLORS.budget} radius={[4, 4, 0, 0]} />
            <Bar dataKey="Actual" fill={CHART_COLORS.actual} radius={[4, 4, 0, 0]} />
            <Line type="monotone" dataKey="Forecast" stroke={CHART_COLORS.forecast} strokeWidth={2} dot={false} />
          </ComposedChart>
        </ResponsiveContainer>
      </ChartWrapper>
      {isLoading ? <FinanceCard><LoadingSkeleton variant="table" /></FinanceCard> :
        <ExecutiveTable columns={cols} data={rows} rowKey={(_, i) => i} emptyMessage={t.noData} searchable={rows.length > 8} />}
    </div>
  );
}

// Cash Flow
function CashFlowBody({ payload, currency, isLoading, lang }: BodyProps) {
  const t = T[lang];
  const chartData = payload ? [
    { name: t.operatingCash, value: n(payload?.operatingActivities?.totalOperating) },
    { name: t.investingCash, value: n(payload?.investingActivities?.totalInvesting) },
    { name: t.financingCash, value: n(payload?.financingActivities?.totalFinancing) },
    { name: t.closingBalance, value: n(payload?.endingBalance) },
  ] : [];
  const rows = payload ? [{
    date: payload?.metadata?.period ?? "—",
    opening: n(payload?.beginningBalance),
    inflow: Math.max(0, n(payload?.operatingActivities?.totalOperating)),
    outflow: Math.min(0, n(payload?.operatingActivities?.totalOperating)),
    closing: n(payload?.endingBalance),
  }] : [];
  const cols: TableColumn<any>[] = [
    { key: "date", label: t.date },
    { key: "opening", label: t.opening, align: "end", ltr: true, render: (r) => money(r.opening, currency) },
    { key: "inflow", label: t.inflow, align: "end", ltr: true, render: (r) => money(r.inflow, currency) },
    { key: "outflow", label: t.outflow, align: "end", ltr: true, render: (r) => money(r.outflow, currency) },
    { key: "closing", label: t.closing, align: "end", ltr: true, render: (r) => money(r.closing, currency) },
  ];
  return (
    <div className="grid gap-4">
      <ChartWrapper title={t.operatingCash} icon={<Wallet className="h-4 w-4" />}
        isLoading={isLoading} isEmpty={chartData.length === 0} emptyMessage={t.noData} chartHeight="h-[320px]">
        <ResponsiveContainer width="100%" height="100%">
          <BarChart data={chartData} margin={{ top: 8, right: 12, left: 0, bottom: 4 }}>
            <CartesianGrid stroke="#e7ebf0" vertical={false} />
            <XAxis dataKey="name" tick={{ fontSize: 11 }} />
            <YAxis tick={{ fontSize: 11 }} tickFormatter={(v) => compactCurrency(v, currency)} />
            <ReferenceLine y={0} stroke="#94a3b8" />
            <Tooltip formatter={(v: number) => compactCurrency(v, currency)} contentStyle={{ borderRadius: 8, border: "1px solid #e7ebf0", fontSize: 11 }} />
            <Bar dataKey="value" radius={[4, 4, 0, 0]}>
              {chartData.map((d, i) => (
                <Cell key={i} fill={d.value < 0 ? FINANCE_COLORS.critical : FINANCE_COLORS.success} />
              ))}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </ChartWrapper>
      {isLoading ? <FinanceCard><LoadingSkeleton variant="table" rows={1} /></FinanceCard> :
        <ExecutiveTable columns={cols} data={rows} rowKey={(_, i) => i} emptyMessage={t.noData} searchable={false} />}
    </div>
  );
}

// Trial Balance
function TrialBalanceBody({ payload, currency, isLoading, lang }: BodyProps) {
  const t = T[lang];
  const rows = (payload?.accounts ?? []) as any[];
  const cols: TableColumn<any>[] = [
    { key: "accountCode", label: t.account, sortable: true, render: (r) => <span className="font-mono">{r.accountCode}</span> },
    { key: "accountName", label: t.category },
    { key: "debit", label: t.debit, align: "end", ltr: true, render: (r) => money(r.debit, currency) },
    { key: "credit", label: t.credit, align: "end", ltr: true, render: (r) => money(r.credit, currency) },
  ];
  return isLoading
    ? <FinanceCard><LoadingSkeleton variant="table" rows={8} /></FinanceCard>
    : <ExecutiveTable columns={cols} data={rows} rowKey={(r, i) => r.accountCode ?? i} emptyMessage={t.noData} searchable={rows.length > 10} />;
}

// Balance Sheet
function BalanceSheetBody({ payload, currency, isLoading, lang }: BodyProps) {
  const t = T[lang];
  const chartData = payload ? [
    { name: t.assets, value: n(payload?.assets?.totalAssets) },
    { name: t.liabilities, value: n(payload?.liabilities?.totalLiabilities) },
    { name: t.equity, value: n(payload?.equity?.totalEquity) },
  ] : [];
  const rows = payload ? [
    ...(payload.assets?.current ?? []).map((r: any) => ({ section: t.assets, line: r.category, amount: r.amount })),
    ...(payload.assets?.noncurrent ?? []).map((r: any) => ({ section: t.assets, line: r.category, amount: r.amount })),
    ...(payload.liabilities?.current ?? []).map((r: any) => ({ section: t.liabilities, line: r.category, amount: r.amount })),
    ...(payload.liabilities?.noncurrent ?? []).map((r: any) => ({ section: t.liabilities, line: r.category, amount: r.amount })),
  ] : [];
  const cols: TableColumn<any>[] = [
    { key: "section", label: t.category },
    { key: "line", label: t.budgetLine },
    { key: "amount", label: t.actual, align: "end", ltr: true, render: (r) => money(r.amount, currency) },
  ];
  return (
    <div className="grid gap-4">
      <ChartWrapper title={`${t.assets} / ${t.liabilities} / ${t.equity}`} icon={<Building2 className="h-4 w-4" />}
        isLoading={isLoading} isEmpty={chartData.length === 0} emptyMessage={t.noData} chartHeight="h-[300px]">
        <ResponsiveContainer width="100%" height="100%">
          <BarChart data={chartData} layout="vertical" margin={{ top: 8, right: 16, left: 8, bottom: 4 }}>
            <CartesianGrid stroke="#e7ebf0" horizontal={false} />
            <XAxis type="number" tick={{ fontSize: 11 }} tickFormatter={(v) => compactCurrency(v, currency)} />
            <YAxis type="category" dataKey="name" tick={{ fontSize: 11 }} width={90} />
            <Tooltip formatter={(v: number) => compactCurrency(v, currency)} contentStyle={{ borderRadius: 8, border: "1px solid #e7ebf0", fontSize: 11 }} />
            <Bar dataKey="value" radius={[0, 4, 4, 0]}>
              {chartData.map((_, i) => <Cell key={i} fill={CHART_COLORS.series[i]} />)}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </ChartWrapper>
      {isLoading ? <FinanceCard><LoadingSkeleton variant="table" /></FinanceCard> :
        <ExecutiveTable columns={cols} data={rows} rowKey={(_, i) => i} emptyMessage={t.noData} searchable={false} />}
    </div>
  );
}

// Income Statement
function IncomeStatementBody({ payload, currency, isLoading, lang }: BodyProps) {
  const t = T[lang];
  const revenue = n(payload?.revenue?.totalRevenue);
  const expenses = n(payload?.expenses?.totalExpenses);
  const chartData = payload ? [{ name: payload?.metadata?.period ?? t.period, [t.revenue]: revenue, [t.expenses]: expenses }] : [];
  const rows = (payload?.expenses?.categories ?? []) as any[];
  const cols: TableColumn<any>[] = [
    { key: "category", label: t.category, sortable: true },
    { key: "amount", label: t.actual, align: "end", ltr: true, render: (r) => money(r.amount, currency) },
  ];
  return (
    <div className="grid gap-4">
      <ChartWrapper title={`${t.revenue} vs ${t.expenses}`} icon={<TrendingUp className="h-4 w-4" />}
        isLoading={isLoading} isEmpty={chartData.length === 0} emptyMessage={t.noData} chartHeight="h-[300px]">
        <ResponsiveContainer width="100%" height="100%">
          <BarChart data={chartData} margin={{ top: 8, right: 12, left: 0, bottom: 4 }}>
            <CartesianGrid stroke="#e7ebf0" vertical={false} />
            <XAxis dataKey="name" tick={{ fontSize: 11 }} />
            <YAxis tick={{ fontSize: 11 }} tickFormatter={(v) => compactCurrency(v, currency)} />
            <Tooltip formatter={(v: number) => compactCurrency(v, currency)} contentStyle={{ borderRadius: 8, border: "1px solid #e7ebf0", fontSize: 11 }} />
            <Legend wrapperStyle={{ fontSize: 11 }} />
            <Bar dataKey={t.revenue} fill={FINANCE_COLORS.success} radius={[4, 4, 0, 0]} />
            <Bar dataKey={t.expenses} fill={FINANCE_COLORS.critical} radius={[4, 4, 0, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </ChartWrapper>
      {isLoading ? <FinanceCard><LoadingSkeleton variant="table" /></FinanceCard> :
        <ExecutiveTable columns={cols} data={rows} rowKey={(_, i) => i} emptyMessage={t.noData} searchable={rows.length > 10} />}
    </div>
  );
}

// Monthly / executive-summary / commitments
function MonthlyBody({ payload, currency, isLoading, lang }: BodyProps) {
  const t = T[lang];
  const revenue = n(payload?.summary?.totalRevenue);
  const expenses = n(payload?.summary?.totalExpenses);
  const chartData = payload ? [{ name: payload?.metadata?.period ?? t.period, [t.revenue]: revenue, [t.expenses]: expenses }] : [];
  const rows = (payload?.sections?.expenses ?? []) as any[];
  const cols: TableColumn<any>[] = [
    { key: "category", label: t.category, sortable: true },
    { key: "amount", label: t.actual, align: "end", ltr: true, render: (r) => money(r.amount, currency) },
  ];
  return (
    <div className="grid gap-4">
      <ChartWrapper title={`${t.revenue} vs ${t.expenses}`} icon={<Activity className="h-4 w-4" />}
        isLoading={isLoading} isEmpty={chartData.length === 0} emptyMessage={t.noData} chartHeight="h-[300px]">
        <ResponsiveContainer width="100%" height="100%">
          <BarChart data={chartData} margin={{ top: 8, right: 12, left: 0, bottom: 4 }}>
            <CartesianGrid stroke="#e7ebf0" vertical={false} />
            <XAxis dataKey="name" tick={{ fontSize: 11 }} />
            <YAxis tick={{ fontSize: 11 }} tickFormatter={(v) => compactCurrency(v, currency)} />
            <Tooltip formatter={(v: number) => compactCurrency(v, currency)} contentStyle={{ borderRadius: 8, border: "1px solid #e7ebf0", fontSize: 11 }} />
            <Legend wrapperStyle={{ fontSize: 11 }} />
            <Bar dataKey={t.revenue} fill={FINANCE_COLORS.success} radius={[4, 4, 0, 0]} />
            <Bar dataKey={t.expenses} fill={FINANCE_COLORS.critical} radius={[4, 4, 0, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </ChartWrapper>
      {isLoading ? <FinanceCard><LoadingSkeleton variant="table" /></FinanceCard> :
        <ExecutiveTable columns={cols} data={rows} rowKey={(_, i) => i} emptyMessage={t.noData} searchable={rows.length > 10} />}
    </div>
  );
}

// Generic analytical report
function GenericReportBody({ payload, currency, isLoading, lang }: BodyProps) {
  const t = T[lang];
  const columns = (payload?.columns ?? []) as { key: string; label: string; type?: string; align?: "start" | "end" }[];
  const rows = (payload?.rows ?? []) as any[];
  const chart = (payload?.chart ?? null) as { data: any[]; series: { key: string; label: string; color?: string }[] } | null;
  const totals = (payload?.totals ?? undefined) as Record<string, number> | undefined;

  const cols: TableColumn<any>[] = columns.map((c) => {
    const isNum = c.type === "currency" || c.type === "number" || c.type === "percent";
    return {
      key: c.key,
      label: c.label,
      align: c.align ?? (isNum ? "end" : "start"),
      ltr: isNum,
      sortable: true,
      render: (r: any) => {
        const v = r[c.key];
        if (c.type === "currency") return money(v, currency);
        if (c.type === "percent") return pct(v);
        if (c.type === "number") return <span>{n(v).toLocaleString()}</span>;
        if (c.type === "status") return <StatusPill status={String(v ?? "—")} />;
        return <span dir="auto">{v == null || v === "" ? "—" : String(v)}</span>;
      },
    };
  });

  const chartData = (chart?.data ?? []) as any[];
  const series = (chart?.series ?? []) as { key: string; label: string; color?: string }[];
  const chartTitle = series.map((s) => s.label).join(" · ") || t.category;

  return (
    <div className="grid gap-4">
      {series.length > 0 && (
        <ChartWrapper
          title={chartTitle} icon={<Activity className="h-4 w-4" />}
          isLoading={isLoading} isEmpty={chartData.length === 0} emptyMessage={t.noData} chartHeight="h-[300px]"
        >
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={chartData} margin={{ top: 8, right: 12, left: 0, bottom: 4 }}>
              <CartesianGrid stroke="#e7ebf0" vertical={false} />
              <XAxis dataKey="name" tick={{ fontSize: 11 }} />
              <YAxis tick={{ fontSize: 11 }} tickFormatter={(v) => compactCurrency(Number(v), currency)} />
              <Tooltip formatter={(v: number) => compactCurrency(Number(v), currency)} contentStyle={{ borderRadius: 8, border: "1px solid #e7ebf0", fontSize: 11 }} />
              {series.length > 1 && <Legend wrapperStyle={{ fontSize: 11 }} />}
              {series.map((s, i) => (
                <Bar key={s.key} dataKey={s.key} name={s.label}
                  fill={s.color ?? CHART_COLORS.series[i % CHART_COLORS.series.length]} radius={[4, 4, 0, 0]} />
              ))}
            </BarChart>
          </ResponsiveContainer>
        </ChartWrapper>
      )}

      {isLoading ? <FinanceCard><LoadingSkeleton variant="table" /></FinanceCard> :
        <ExecutiveTable columns={cols} data={rows} rowKey={(_, i) => i} emptyMessage={t.noData} searchable={rows.length > 10} />}

      {totals && Object.keys(totals).length > 0 && (
        <FinanceCard className="flex flex-wrap gap-x-8 gap-y-2">
          {Object.entries(totals).map(([k, v]) => (
            <div key={k} className="min-w-0">
              <span className="block text-[10px] font-bold uppercase tracking-wide text-slate-500">Total · {k}</span>
              <span className="block font-mono text-[14px] font-bold text-[#003b70]" dir="ltr">
                {Math.abs(n(v)) >= 1000 ? compactCurrency(n(v), currency) : n(v).toLocaleString()}
              </span>
            </div>
          ))}
        </FinanceCard>
      )}
    </div>
  );
}

interface BodyProps { payload: any; currency: string; isLoading: boolean; lang: Lang; }

// ─── Helpers ────────────────────────────────────────────────────────────────
function StatusPill({ status }: { status: string }) {
  const s = status.toLowerCase();
  const cls =
    s === "final" ? "bg-green-100 text-green-700"
    : s === "draft" ? "bg-amber-100 text-amber-700"
    : "bg-slate-100 text-slate-600";
  return <span className={`inline-block rounded px-2 py-0.5 text-[10px] font-bold capitalize ${cls}`}>{status}</span>;
}

export default FinanceReportingCenter;
