/**
 * ============================================================================
 * RISK INTELLIGENCE CARDS GRID
 * ============================================================================
 * 
 * Displays auto-generated risks with early-warning detection indicators:
 * - Auto-generated badge (🤖)
 * - Trend direction (↑ Increasing / ↓ Improving / → Stable)
 * - Source badge (Finance / MEAL / Activities)
 * - Trigger value display
 * - Cross-module links to projects/activities/indicators
 * - Mitigation suggestions preview
 * 
 * ============================================================================
 */

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { 
 TrendingUp, 
 TrendingDown, 
 Minus, 
 AlertTriangle,
 DollarSign,
 Activity,
 Target,
 ExternalLink,
 Bot,
 ChevronRight
} from 'lucide-react';
import { useNavigate } from '@/lib/router-compat';
import { useLanguage } from '@/contexts/LanguageContext';
import { useTranslation } from '@/i18n/useTranslation';

interface Risk {
 id: number;
 title: string;
 titleAr?: string;
 description: string;
 descriptionAr?: string;
 level: 'low' | 'medium' | 'high' | 'critical';
 category: string;
 status: string;
 isSystemGenerated: boolean;
 source?: 'finance' | 'meal' | 'activities' | 'manual';
 triggerValue?: string;
 trendDirection?: 'increasing' | 'improving' | 'stable';
 projectId?: number;
 activityId?: number;
 indicatorId?: number;
 autoMitigationSuggestions?: string; // JSON string
}

interface RiskIntelligenceCardsGridProps {
 risks: Risk[];
 showAutoGeneratedOnly?: boolean;
}

export function RiskIntelligenceCardsGrid({
 risks, 
 showAutoGeneratedOnly = false 
}: RiskIntelligenceCardsGridProps) {
 const { t } = useTranslation(); 
 const { language, isRTL } = useLanguage();
 const navigate = useNavigate();

 const labels = {
 autoGenerated: t.organizationModule.autogenerated,
 manual: t.organizationModule.manual,
 increasing: t.organizationModule.increasing,
 improving: t.organizationModule.improving,
 stable: t.organizationModule.stable,
 finance: t.organizationModule.finance,
 meal: 'MEAL',
 activities: t.organizationModule.activities,
 triggerValue: t.organizationModule.trigger,
 viewDetails: t.organizationModule.viewDetails,
 linkedTo: t.organizationModule.linkedTo,
 project: t.organizationModule.project,
 activity: t.organizationModule.activity,
 indicator: t.organizationModule.indicator,
 mitigationSuggestions: t.organizationModule.mitigationSuggestions,
 noRisks: t.organizationModule.noRisksDetected,
 };

 const filteredRisks = showAutoGeneratedOnly 
 ? risks.filter(r => r.isSystemGenerated)
 : risks;

 const getLevelColor = (level: string) => {
 switch (level) {
 case 'low': return 'bg-green-100 text-green-800 border-green-200';
 case 'medium': return 'bg-yellow-100 text-yellow-800 border-yellow-200';
 case 'high': return 'bg-orange-100 text-orange-800 border-orange-200';
 case 'critical': return 'bg-red-100 text-red-800 border-red-200';
 default: return 'bg-gray-100 text-gray-800 border-gray-200';
 }
 };

 const getSourceIcon = (source?: string) => {
 switch (source) {
 case 'finance': return <DollarSign className="h-3 w-3" />;
 case 'meal': return <Target className="h-3 w-3" />;
 case 'activities': return <Activity className="h-3 w-3" />;
 default: return <AlertTriangle className="h-3 w-3" />;
 }
 };

 const getSourceLabel = (source?: string) => {
 switch (source) {
 case 'finance': return labels.finance;
 case 'meal': return labels.meal;
 case 'activities': return labels.activities;
 default: return labels.manual;
 }
 };

 const getTrendIcon = (trend?: string) => {
 switch (trend) {
 case 'increasing': return <TrendingUp className="h-3 w-3 text-red-600" />;
 case 'improving': return <TrendingDown className="h-3 w-3 text-green-600" />;
 case 'stable': return <Minus className="h-3 w-3 text-gray-600" />;
 default: return null;
 }
 };

 const getTrendLabel = (trend?: string) => {
 switch (trend) {
 case 'increasing': return labels.increasing;
 case 'improving': return labels.improving;
 case 'stable': return labels.stable;
 default: return '';
 }
 };

 const handleCrossModuleLink = (risk: Risk) => {
 if (risk.projectId) {
 navigate(`/organization/projects/${risk.projectId}`);
 } else if (risk.activityId) {
 navigate(`/organization/activities/${risk.activityId}`);
 } else if (risk.indicatorId) {
 navigate(`/organization/meal/indicators/${risk.indicatorId}`);
 }
 };

 if (filteredRisks.length === 0) {
 return (
 <Card>
 <CardContent className="py-12 text-center">
 <p className="text-muted-foreground">{labels.noRisks}</p>
 </CardContent>
 </Card>
 );
 }

 return (
 <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4" dir={isRTL ? 'rtl' : 'ltr'}>
 {filteredRisks.map((risk) => {
 const mitigationSuggestions = risk.autoMitigationSuggestions 
 ? JSON.parse(risk.autoMitigationSuggestions) 
 : [];

 return (
 <Card 
 key={risk.id} 
 className={`hover:shadow-lg transition-shadow ${ risk.isSystemGenerated ? 'border-l-4 border-l-blue-500' : '' }`}
 >
 <CardHeader className="pb-3">
 {/* Badges Row */}
 <div className="flex flex-wrap gap-2 mb-2">
 {/* Auto-Generated Badge */}
 {risk.isSystemGenerated && (
 <Badge variant="secondary" className="text-xs">
 <Bot className="h-3 w-3 me-1" />
 {labels.autoGenerated}
 </Badge>
 )}

 {/* Level Badge */}
 <Badge className={`text-xs ${getLevelColor(risk.level)}`}>
 {risk.level.toUpperCase()}
 </Badge>

 {/* Source Badge */}
 {risk.source && (
 <Badge variant="outline" className="text-xs">
 {getSourceIcon(risk.source)}
 <span className="ms-1">{getSourceLabel(risk.source)}</span>
 </Badge>
 )}

 {/* Trend Badge */}
 {risk.trendDirection && (
 <Badge variant="outline" className="text-xs">
 {getTrendIcon(risk.trendDirection)}
 <span className="ms-1">{getTrendLabel(risk.trendDirection)}</span>
 </Badge>
 )}
 </div>

 {/* Risk Title */}
 <CardTitle className="text-base line-clamp-2">
 {language === 'ar' && risk.titleAr ? risk.titleAr : risk.title}
 </CardTitle>
 </CardHeader>

 <CardContent className="space-y-3">
 {/* Risk Description */}
 <p className="text-sm text-muted-foreground line-clamp-3">
 {language === 'ar' && risk.descriptionAr ? risk.descriptionAr : risk.description}
 </p>

 {/* Trigger Value */}
 {risk.triggerValue && (
 <div className="flex items-center gap-2 text-xs text-muted-foreground">
 <span className="font-semibold">{labels.triggerValue}:</span>
 <span className="font-mono bg-gray-100 px-2 py-1 rounded">
 {risk.triggerValue}
 </span>
 </div>
 )}

 {/* Cross-Module Link */}
 {(risk.projectId || risk.activityId || risk.indicatorId) && (
 <Button
 variant="ghost"
 size="sm"
 className="w-full justify-between text-xs"
 onClick={() => handleCrossModuleLink(risk)}
 >
 <span>
 {labels.linkedTo} {risk.projectId && labels.project}
 {risk.activityId && labels.activity}
 {risk.indicatorId && labels.indicator}
 </span>
 <ExternalLink className="h-3 w-3" />
 </Button>
 )}

 {/* Mitigation Suggestions Preview */}
 {mitigationSuggestions.length > 0 && (
 <div className="bg-blue-50 border border-blue-200 rounded-md p-2">
 <p className="text-xs font-semibold text-blue-900 mb-1">
 {labels.mitigationSuggestions}:
 </p>
 <ul className="text-xs text-blue-800 space-y-1">
 {mitigationSuggestions.slice(0, 2).map((suggestion: string, idx: number) => (
 <li key={idx} className="flex items-start gap-1">
 <span className="text-blue-600">•</span>
 <span className="line-clamp-2">{suggestion}</span>
 </li>
 ))}
 </ul>
 {mitigationSuggestions.length > 2 && (
 <p className="text-xs text-blue-600 mt-1">
 +{mitigationSuggestions.length - 2} more
 </p>
 )}
 </div>
 )}

 {/* View Details Button */}
 <Button
 variant="outline"
 size="sm"
 className="w-full"
 onClick={() => navigate(`/organization/risk-compliance/risks/${risk.id}`)}
 >
 {labels.viewDetails}
 {isRTL ? <ChevronRight className="h-4 w-4 me-2" /> : <ChevronRight className="h-4 w-4 ms-2" />}
 </Button>
 </CardContent>
 </Card>
 );
 })}
 </div>
 );
}
