import { getDb } from "../db";
import fs from "fs";
import path from "path";
import { purchaseRequests, purchaseRequestLineItems, rfqVendors, organizations, organizationBranding } from "../../drizzle/schema";
import { eq } from "drizzle-orm";

interface RFQPDFData {
  html: string;
}

const translations = {
  en: {
    title: "REQUEST FOR QUOTATION",
    formNo: "Form No:",
    date: "Date:",
    rfqInfo: "RFQ Information",
    rfqNumber: "RFQ Number",
    prNumber: "PR Number",
    issueDate: "Issue Date",
    submissionDeadline: "Submission Deadline",
    toBeConfirmed: "To be confirmed",
    prDetails: "Purchase Request Details",
    requester: "Requester",
    department: "Department",
    priority: "Priority",
    requiredDeliveryDate: "Required Delivery Date",
    justification: "Justification",
    itemsRequested: "Items Requested",
    itemDescription: "Item Description",
    specifications: "Specifications",
    qty: "Qty",
    unit: "Unit",
    purpose: "Purpose",
    submissionInstructions: "Submission Instructions",
    deadline: "Deadline",
    deadlineText: "Please submit your quotation by",
    format: "Format",
    formatText: "Provide unit prices for each item listed above in your quotation",
    currency: "Currency",
    currencyText: "Clearly specify the currency (USD, EUR, etc.) for all prices",
    deliveryTerms: "Delivery Terms",
    deliveryTermsText: "Include estimated delivery time in days",
    warranty: "Warranty",
    warrantyText: "Specify warranty period in months (if applicable)",
    validity: "Validity",
    validityText: "Your quotation should be valid for at least 30 days from submission",
    reference: "Reference",
    referenceText: "Please quote RFQ Number",
    inYourResponse: "in your response",
    contact: "Contact",
    contactText: "For any clarifications, please contact the procurement department",
    termsTitle: "Terms & Conditions",
    term1: "Prices should include all applicable taxes and duties",
    term2: "Payment terms will be discussed after quotation evaluation",
    term3: "The organization reserves the right to accept or reject any quotation",
    term4: "Partial fulfillment of items may be considered",
    term5: "Quality certifications and compliance documents may be requested",
    approvalTitle: "Approval & Authorization",
    preparedBy: "Prepared By",
    reviewedBy: "Reviewed By",
    approvedBy: "Approved By",
    nameAndDate: "Name & Date",
    footerText: "This is an official Request for Quotation document generated by",
    generatedOn: "Generated on",
    rfqReference: "RFQ Reference",
    prReference: "PR Reference",
  },
  ar: {
    title: "طلب عرض أسعار",
    formNo: "رقم النموذج:",
    date: "التاريخ:",
    rfqInfo: "معلومات طلب عرض الأسعار",
    rfqNumber: "رقم طلب عرض الأسعار",
    prNumber: "رقم طلب الشراء",
    issueDate: "تاريخ الإصدار",
    submissionDeadline: "الموعد النهائي للتقديم",
    toBeConfirmed: "سيتم تأكيده",
    prDetails: "تفاصيل طلب الشراء",
    requester: "مقدم الطلب",
    department: "القسم",
    priority: "الأولوية",
    requiredDeliveryDate: "تاريخ التسليم المطلوب",
    justification: "المبرر",
    itemsRequested: "البنود المطلوبة",
    itemDescription: "وصف البند",
    specifications: "المواصفات",
    qty: "الكمية",
    unit: "الوحدة",
    purpose: "الغرض",
    submissionInstructions: "تعليمات التقديم",
    deadline: "الموعد النهائي",
    deadlineText: "يرجى تقديم عرض الأسعار بحلول",
    format: "الصيغة",
    formatText: "يرجى تقديم أسعار الوحدة لكل بند مذكور أعلاه في عرض الأسعار",
    currency: "العملة",
    currencyText: "يرجى تحديد العملة (دولار أمريكي، يورو، إلخ) لجميع الأسعار بوضوح",
    deliveryTerms: "شروط التسليم",
    deliveryTermsText: "يرجى تضمين وقت التسليم المقدر بالأيام",
    warranty: "الضمان",
    warrantyText: "يرجى تحديد فترة الضمان بالأشهر (إن وجد)",
    validity: "الصلاحية",
    validityText: "يجب أن يكون عرض الأسعار صالحاً لمدة 30 يوماً على الأقل من تاريخ التقديم",
    reference: "المرجع",
    referenceText: "يرجى ذكر رقم طلب عرض الأسعار",
    inYourResponse: "في ردكم",
    contact: "الاتصال",
    contactText: "لأي استفسارات، يرجى التواصل مع قسم المشتريات",
    termsTitle: "الشروط والأحكام",
    term1: "يجب أن تشمل الأسعار جميع الضرائب والرسوم المطبقة",
    term2: "سيتم مناقشة شروط الدفع بعد تقييم عرض الأسعار",
    term3: "تحتفظ المنظمة بحق قبول أو رفض أي عرض أسعار",
    term4: "قد يتم النظر في التنفيذ الجزئي للبنود",
    term5: "قد يُطلب تقديم شهادات الجودة ووثائق الامتثال",
    approvalTitle: "الموافقة والتفويض",
    preparedBy: "أعدّه",
    reviewedBy: "راجعه",
    approvedBy: "اعتمده",
    nameAndDate: "الاسم والتاريخ",
    footerText: "هذه وثيقة رسمية لطلب عرض أسعار صادرة عن",
    generatedOn: "تم الإنشاء في",
    rfqReference: "مرجع طلب عرض الأسعار",
    prReference: "مرجع طلب الشراء",
  },
};

export async function generateRFQPDFOfficial(
  rfqVendorId: number,
  organizationId: number,
  language: 'en' | 'ar' = 'en'
): Promise<RFQPDFData> {
  const db = await getDb();
  const t = translations[language] || translations.en;
  const isRTL = language === 'ar';
  const dir = isRTL ? 'rtl' : 'ltr';
  const textAlign = isRTL ? 'right' : 'left';
  const marginSide = isRTL ? 'margin-right' : 'margin-left';
  const borderSide = isRTL ? 'border-right' : 'border-left';
  
  // Fetch RFQ vendor details
  const [rfqVendor] = await db
    .select()
    .from(rfqVendors)
    .where(eq(rfqVendors.id, rfqVendorId));

  if (!rfqVendor) {
    throw new Error("RFQ vendor not found");
  }

  // Fetch PR details
  const [pr] = await db
    .select()
    .from(purchaseRequests)
    .where(eq(purchaseRequests.id, rfqVendor.purchaseRequestId));

  if (!pr) {
    throw new Error("Purchase request not found");
  }

  // Fetch line items
  const lineItems = await db
    .select()
    .from(purchaseRequestLineItems)
    .where(eq(purchaseRequestLineItems.purchaseRequestId, pr.id)) as any[];

  // Format dates
  const dateLocale = isRTL ? 'ar-SA' : 'en-US';
  const issueDate = new Date().toLocaleDateString(dateLocale, {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });
  
  // Safe data access
  const prNumber = pr?.prNumber || "N/A";
  const requestedBy = pr?.requestedBy || "N/A";
  const department = pr?.department || "N/A";
  const urgency = pr?.urgency || "Normal";
  const justification = pr?.justification || "N/A";
  const requiredDeliveryDate = pr?.requiredDeliveryDate 
    ? new Date(pr.requiredDeliveryDate).toLocaleDateString(dateLocale, {
        year: "numeric",
        month: "2-digit",
        day: "2-digit",
      })
    : "N/A";

  // Fetch organization details
  const [org] = await db
    .select()
    .from(organizations)
    .where(eq(organizations.id, organizationId));

  // Fetch organization branding
  const [branding] = await db
    .select()
    .from(organizationBranding)
    .where(eq(organizationBranding.organizationId, organizationId));

  const orgName = org?.name || "Organization";
  const orgUnit = pr.operatingUnit || (isRTL ? "المقر الرئيسي" : "Headquarters");
  const country = org?.country || (isRTL ? "اليمن" : "Yemen");
  const orgLogo = branding?.logoUrl || null;

  // Load official-pdf.css (BOM's flexbox approach) — proven RTL mirroring
  const officialCssPath = path.join(import.meta.dirname, "../services/pdf/templates/styles/official-pdf.css");
  const officialCss = fs.readFileSync(officialCssPath, "utf-8");

  // Generate HTML
  const html = `<!DOCTYPE html>
<html lang="${language}" dir="${dir}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${t.title}</title>
  <style>
    ${officialCss}
    
    body {
      font-family: ${isRTL ? "'Noto Naskh Arabic', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif" : "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif"};
      font-size: 11pt;
      line-height: 1.5;
      color: #333;
      padding: 40px;
      max-width: 210mm;
      margin: 0 auto;
      background: white;
    }
    
    .page {
      background: white;
      padding: 0;
      margin-bottom: 40px;
    }
    
    h2 {
      font-size: 13pt;
      font-weight: bold;
      color: #1a3a52;
      margin-top: 25px;
      margin-bottom: 12px;
      padding-bottom: 8px;
      border-bottom: 1px solid #ddd;
    }
    
    .info-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 15px;
      margin-bottom: 20px;
    }
    
    .info-item {
      display: flex;
      flex-direction: column;
    }
    
    .info-label {
      font-size: 9pt;
      font-weight: bold;
      color: #555;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 4px;
    }
    
    .info-value {
      font-size: 11pt;
      color: #333;
      font-weight: 500;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 15px;
      margin-bottom: 20px;
      font-size: 10pt;
    }
    
    thead {
      background: #2c3e50;
      color: white;
    }
    
    th {
      padding: 12px 8px;
      text-align: ${textAlign};
      font-weight: bold;
      font-size: 10pt;
      border: 1px solid #2c3e50;
    }
    
    td {
      padding: 10px 8px;
      border: 1px solid #ddd;
      text-align: ${textAlign};
    }
    
    tbody tr:nth-child(even) {
      background: #f9f9f9;
    }
    
    tbody tr:hover {
      background: #f5f5f5;
    }
    
    .text-center {
      text-align: center;
    }
    
    .text-right {
      text-align: right;
    }
    
    .instructions-box {
      background: #fff9e6;
      ${borderSide}: 4px solid #f39c12;
      padding: 12px 15px;
      margin: 20px 0;
      font-size: 10pt;
      line-height: 1.6;
    }
    
    .instructions-title {
      font-weight: bold;
      color: #d68910;
      margin-bottom: 8px;
      font-size: 11pt;
    }
    
    .instructions-list {
      ${marginSide}: 20px;
    }
    
    .instructions-list li {
      margin-bottom: 6px;
      color: #333;
    }
    
    .instructions-list strong {
      color: #d68910;
    }
    
    .signature-section {
      margin-top: 40px;
      page-break-inside: avoid;
    }
    
    .signature-grid {
      display: grid;
      grid-template-columns: 1fr 1fr 1fr;
      gap: 30px;
      margin-top: 30px;
    }
    
    .signature-block {
      text-align: center;
      font-size: 10pt;
    }
    
    .signature-line {
      border-top: 1px solid #333;
      margin-top: 40px;
      margin-bottom: 8px;
      height: 1px;
    }
    
    .signature-label {
      font-weight: bold;
      color: #333;
      font-size: 10pt;
    }
    
    .signature-date {
      font-size: 9pt;
      color: #666;
      margin-top: 4px;
    }
    
    .footer {
      margin-top: 40px;
      padding-top: 15px;
      border-top: 1px solid #ddd;
      text-align: center;
      font-size: 9pt;
      color: #999;
    }
    
    .terms-box {
      background: #f0f0f0;
      border: 1px solid #ddd;
      padding: 12px 15px;
      margin: 20px 0;
      font-size: 9pt;
      line-height: 1.5;
    }
    
    .terms-title {
      font-weight: bold;
      color: #333;
      margin-bottom: 8px;
      font-size: 10pt;
    }
    
    .terms-list {
      ${marginSide}: 20px;
    }
    
    .terms-list li {
      margin-bottom: 4px;
      color: #555;
    }
    
    @media print {
      body {
        padding: 20px;
      }
      .page {
        page-break-after: always;
        margin-bottom: 0;
      }
    }
  </style>
</head>
<body>
  <div class="page">
    <!-- HEADER (BOM flexbox approach - auto-mirrors in RTL) -->
    <div class="official-header">
      <div class="header-left">
        <div class="org-block">
          <div class="org-name">${orgName}</div>
          <div class="ou-name">${orgUnit}</div>
          <div class="module-name">${country}</div>
        </div>
      </div>
      <div class="header-center">
        <div class="doc-title">${t.title}</div>
      </div>
      <div class="header-right">
        ${orgLogo ? `<img class="org-logo" src="${orgLogo}" alt="Logo" />` : ""}
        <div class="ref-date">
          <div class="value ltr-safe">RFQ-${rfqVendor?.id || "N/A"}</div>
          <div class="value ltr-safe">${issueDate}</div>
        </div>
      </div>
    </div>
    <hr class="hr-strong" />
    
    <!-- RFQ INFORMATION -->
    <h2>${t.rfqInfo}</h2>
    <div class="info-grid">
      <div class="info-item">
        <span class="info-label">${t.rfqNumber}</span>
        <span class="info-value">${rfqVendor.rfqNumber || "N/A"}</span>
      </div>
      <div class="info-item">
        <span class="info-label">${t.prNumber}</span>
        <span class="info-value">${prNumber}</span>
      </div>
      <div class="info-item">
        <span class="info-label">${t.issueDate}</span>
        <span class="info-value">${issueDate}</span>
      </div>
      <div class="info-item">
        <span class="info-label">${t.submissionDeadline}</span>
        <span class="info-value">${t.toBeConfirmed}</span>
      </div>
    </div>
    
    <!-- PURCHASE REQUEST DETAILS -->
    <h2>${t.prDetails}</h2>
    <div class="info-grid">
      <div class="info-item">
        <span class="info-label">${t.requester}</span>
        <span class="info-value">${requestedBy}</span>
      </div>
      <div class="info-item">
        <span class="info-label">${t.department}</span>
        <span class="info-value">${department}</span>
      </div>
      <div class="info-item">
        <span class="info-label">${t.priority}</span>
        <span class="info-value">${urgency}</span>
      </div>
      <div class="info-item">
        <span class="info-label">${t.requiredDeliveryDate}</span>
        <span class="info-value">${requiredDeliveryDate}</span>
      </div>
      <div class="info-item" style="grid-column: 1 / -1;">
        <span class="info-label">${t.justification}</span>
        <span class="info-value">${justification}</span>
      </div>
    </div>
    
    <!-- ITEMS REQUESTED -->
    <h2>${t.itemsRequested}</h2>
    <table>
      <thead>
        <tr>
          <th style="width: 5%;">#</th>
          <th style="width: 25%;">${t.itemDescription}</th>
          <th style="width: 20%;">${t.specifications}</th>
          <th style="width: 10%;" class="text-center">${t.qty}</th>
          <th style="width: 10%;" class="text-center">${t.unit}</th>
          <th style="width: 30%;">${t.purpose}</th>
        </tr>
      </thead>
      <tbody>
        ${lineItems
          .map(
            (item: any, index: number) => `
        <tr>
          <td class="text-center">${index + 1}</td>
          <td><strong>${item.itemName || item.itemDescription || "N/A"}</strong></td>
          <td>${item.specifications || "-"}</td>
          <td class="text-center">${(item.quantity || 0).toFixed(2)}</td>
          <td class="text-center">${item.unit || "N/A"}</td>
          <td>${item.purpose || "-"}</td>
        </tr>
        `
          )
          .join("")}
      </tbody>
    </table>
    
    <!-- SUBMISSION INSTRUCTIONS -->
    <div class="instructions-box">
      <div class="instructions-title">${isRTL ? '📋' : '📋'} ${t.submissionInstructions}</div>
      <ul class="instructions-list">
        <li><strong>${t.deadline}:</strong> ${t.deadlineText} <strong>[${t.toBeConfirmed}]</strong></li>
        <li><strong>${t.format}:</strong> ${t.formatText}</li>
        <li><strong>${t.currency}:</strong> ${t.currencyText}</li>
        <li><strong>${t.deliveryTerms}:</strong> ${t.deliveryTermsText}</li>
        <li><strong>${t.warranty}:</strong> ${t.warrantyText}</li>
        <li><strong>${t.validity}:</strong> ${t.validityText}</li>
        <li><strong>${t.reference}:</strong> ${t.referenceText} <strong>${rfqVendor.rfqNumber || "N/A"}</strong> ${t.inYourResponse}</li>
        <li><strong>${t.contact}:</strong> ${t.contactText}</li>
      </ul>
    </div>
    
    <!-- TERMS & CONDITIONS -->
    <div class="terms-box">
      <div class="terms-title">${t.termsTitle}</div>
      <ul class="terms-list">
        <li>${t.term1}</li>
        <li>${t.term2}</li>
        <li>${t.term3}</li>
        <li>${t.term4}</li>
        <li>${t.term5}</li>
      </ul>
    </div>
    
    <!-- SIGNATURE SECTION -->
    <div class="signature-section">
      <h2>${t.approvalTitle}</h2>
      <div class="signature-grid">
        <div class="signature-block">
          <div class="signature-line"></div>
          <div class="signature-label">${t.preparedBy}</div>
          <div class="signature-date">${t.nameAndDate}</div>
        </div>
        <div class="signature-block">
          <div class="signature-line"></div>
          <div class="signature-label">${t.reviewedBy}</div>
          <div class="signature-date">${t.nameAndDate}</div>
        </div>
        <div class="signature-block">
          <div class="signature-line"></div>
          <div class="signature-label">${t.approvedBy}</div>
          <div class="signature-date">${t.nameAndDate}</div>
        </div>
      </div>
    </div>
    
    <!-- FOOTER -->
    <div class="footer">
      <p>${t.footerText} ${orgName}</p>
      <p>${t.generatedOn} ${issueDate} | ${t.rfqReference}: ${rfqVendor.rfqNumber || "N/A"} | ${t.prReference}: ${pr.prNumber || "N/A"}</p>
    </div>
  </div>
</body>
</html>`;

  return { html };
}
