import { useState, useEffect } from "react";
import { Link, useLocation, useRoute } from "wouter";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Save, Plus, Trash2 } from "lucide-react";
import { useLanguage } from "@/contexts/LanguageContext";
import { useTranslation } from '@/i18n/useTranslation';
import { BackButton } from "@/components/BackButton";

export default function StockRequestsForm() {
 const { t } = useTranslation();
 const [, setLocation] = useLocation();
 const [, params] = useRoute("/organization/logistics/stock/requests/:id");
 const [, editParams] = useRoute("/organization/logistics/stock/requests/:id/edit");
 const requestId = params?.id || editParams?.id;
 const isEditMode = !!requestId;
 const { isRTL } = useLanguage();

 const [formData, setFormData] = useState({
 requestNumber: "",
 requestDate: new Date().toISOString().split("T")[0],
 requestedBy: "",
 department: "",
 purpose: "",
 remarks: "",
 status: "draft",
 });

 const [lineItems, setLineItems] = useState<any[]>([
 { stockItemId: "", quantityRequested: "", unit: "", notes: "" },
 ]);

 const { data: stockItems = [] } = trpc.logistics.stock.listItems.useQuery({});
 const utils = trpc.useUtils();

 const handleAddLineItem = () => {
 setLineItems([...lineItems, { stockItemId: "", quantityRequested: "", unit: "", notes: "" }]);
 };

 const handleRemoveLineItem = (index: number) => {
 setLineItems(lineItems.filter((_, i) => i !== index));
 };

 const handleLineItemChange = (index: number, field: string, value: any) => {
 const updated = [...lineItems];
 updated[index] = { ...updated[index], [field]: value };
 setLineItems(updated);
 };

 const handleSubmit = async (e: React.FormEvent, status: string = "draft") => {
 e.preventDefault();
 try {
 const payload = {
 ...formData,
 status,
 lineItems: lineItems.filter(item => item.stockItemId),
 };
 
 // Note: Backend create/update mutations need to be implemented
 console.log("Saving request:", payload);
 
 utils.logistics.stock.listRequests.invalidate();
 setLocation("/organization/logistics/stock/requests");
 } catch (error) {
 console.error("Error saving request:", error);
 }
 };

 const labels = {
 title: isEditMode ? (t.logistics.editRequest) : (t.logistics.newRequest),
 requestNumber: t.logistics.requestNumber,
 requestDate: t.logistics.requestDate,
 requestedBy: t.logistics.requestedBy,
 department: t.logistics.department,
 purpose: t.logistics.purpose,
 remarks: t.logistics.remarks,
 lineItems: t.logistics.requestedItems,
 item: t.logistics.item,
 quantity: t.logistics.quantity,
 unit: t.logistics.unit,
 notes: t.logistics.notes,
 addItem: t.logistics.addItem20,
 saveDraft: t.logistics.saveDraft,
 submit: t.logistics.submit22,
 cancel: t.logistics.cancel,
 };

 return (
 <div className="min-h-screen bg-background p-6" dir={isRTL ? 'rtl' : 'ltr'}>
 <div className="container max-w-6xl">
 <div className="flex items-center gap-4 mb-6">
 <BackButton href="/organization/logistics/stock/requests" iconOnly />
 <h1 className="text-3xl font-bold text-foreground">{labels.title}</h1>
 </div>

 <form onSubmit={(e) => handleSubmit(e, "draft")}>
 <Card className="mb-6">
 <CardHeader>
 <CardTitle>{t.logistics.requestInformation}</CardTitle>
 </CardHeader>
 <CardContent className="space-y-4">
 <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
 <div className="space-y-2">
 <Label htmlFor="requestNumber">{labels.requestNumber}</Label>
 <Input
 id="requestNumber"
 value={formData.requestNumber}
 placeholder={t.placeholders.autoGenerated}
 disabled
 />
 </div>
 <div className="space-y-2">
 <Label htmlFor="requestDate">{labels.requestDate} *</Label>
 <Input
 id="requestDate"
 type="date"
 value={formData.requestDate}
 onChange={(e) => setFormData({ ...formData, requestDate: e.target.value })}
 required
 />
 </div>
 </div>

 <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
 <div className="space-y-2">
 <Label htmlFor="requestedBy">{labels.requestedBy} *</Label>
 <Input
 id="requestedBy"
 value={formData.requestedBy}
 onChange={(e) => setFormData({ ...formData, requestedBy: e.target.value })}
 required
 />
 </div>
 <div className="space-y-2">
 <Label htmlFor="department">{labels.department}</Label>
 <Input
 id="department"
 value={formData.department}
 onChange={(e) => setFormData({ ...formData, department: e.target.value })}
 />
 </div>
 </div>

 <div className="space-y-2">
 <Label htmlFor="purpose">{labels.purpose}</Label>
 <Textarea
 id="purpose"
 value={formData.purpose}
 onChange={(e) => setFormData({ ...formData, purpose: e.target.value })}
 rows={2}
 />
 </div>

 <div className="space-y-2">
 <Label htmlFor="remarks">{labels.remarks}</Label>
 <Textarea
 id="remarks"
 value={formData.remarks}
 onChange={(e) => setFormData({ ...formData, remarks: e.target.value })}
 rows={2}
 />
 </div>
 </CardContent>
 </Card>

 <Card className="mb-6">
 <CardHeader>
 <div className="flex items-center justify-between">
 <CardTitle>{labels.lineItems}</CardTitle>
 <Button type="button" variant="outline" size="sm" onClick={handleAddLineItem}>
 <Plus className="h-4 w-4 me-2" />
 {labels.addItem}
 </Button>
 </div>
 </CardHeader>
 <CardContent className="space-y-4">
 {lineItems.map((item, index) => (
 <div key={index} className="grid grid-cols-12 gap-4 items-end">
 <div className="col-span-4 space-y-2">
 <Label>{labels.item}</Label>
 <select
 className="w-full h-10 px-3 rounded-md border border-input bg-background"
 value={item.stockItemId}
 onChange={(e) => handleLineItemChange(index, "stockItemId", e.target.value)}
 >
 <option value="">{isRTL ? "اختر صنفاً..." : "Select item..."}</option>
 {stockItems.map((stockItem: any) => (
 <option key={stockItem.id} value={stockItem.id}>
 {stockItem.itemName}
 </option>
 ))}
 </select>
 </div>
 <div className="col-span-2 space-y-2">
 <Label>{labels.quantity}</Label>
 <Input
 type="number"
 value={item.quantityRequested}
 onChange={(e) => handleLineItemChange(index, "quantityRequested", e.target.value)}
 />
 </div>
 <div className="col-span-2 space-y-2">
 <Label>{labels.unit}</Label>
 <Input
 value={item.unit}
 onChange={(e) => handleLineItemChange(index, "unit", e.target.value)}
 />
 </div>
 <div className="col-span-3 space-y-2">
 <Label>{labels.notes}</Label>
 <Input
 value={item.notes}
 onChange={(e) => handleLineItemChange(index, "notes", e.target.value)}
 />
 </div>
 <div className="col-span-1">
 <Button
 type="button"
 variant="ghost"
 size="icon"
 onClick={() => handleRemoveLineItem(index)}
 >
 <Trash2 className="h-4 w-4 text-destructive" />
 </Button>
 </div>
 </div>
 ))}
 </CardContent>
 </Card>

 <div className="flex justify-end gap-4">
 <Button
 type="button"
 variant="outline"
 onClick={() => setLocation("/organization/logistics/stock/requests")}
 >
 {labels.cancel}
 </Button>
 <Button type="submit" variant="outline">
 <Save className="h-4 w-4 me-2" />
 {labels.saveDraft}
 </Button>
 <Button type="button" onClick={(e: any) => handleSubmit(e, "submitted")}>
 {labels.submit}
 </Button>
 </div>
 </form>
 </div>
 </div>
 );
}
