/**
 * ============================================================================
 * FORM 6: FINAL DISCIPLINARY RECORD (AUTO-GENERATED)
 * ============================================================================
 * 
 * PURPOSE: Permanent historical record
 * 
 * FEATURES:
 * - Auto-generated from Forms 1-5 after approval
 * - Read-only view only
 * - Displays in Employee Profile (read-only)
 * - Printable official record
 * - Triggers system actions:
 *   - Payroll impact (if applicable)
 *   - Status change (if termination)
 * - Bilingual (EN/AR)
 * 
 * ============================================================================
 */

import { useState, useEffect } from 'react';
import { useNavigate, useParams } from '@/lib/router-compat';
import { Printer, ArrowLeft, FileCheck, AlertCircle } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';
import { DisciplinaryCase } from './types';
import { sanctionsService } from './sanctionsService';

export function Form6_FinalRecord() {
  const { language, isRTL } = useLanguage();
  const navigate = useNavigate();
  const { caseRef } = useParams<{ caseRef: string }>();

  const [caseData, setCaseData] = useState<DisciplinaryCase | null>(null);

  useEffect(() => {
    if (caseRef) {
      loadCase();
    }
  }, [caseRef]);

  const loadCase = () => {
    const existing = sanctionsService.getCaseByReference(caseRef!);
    if (existing) {
      setCaseData(existing);
    }
  };

  const finalRecord = caseData?.form6_final;

  if (!finalRecord) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <AlertCircle className="w-16 h-16 text-gray-400 mx-auto mb-4" />
          <h2 className="text-xl font-bold text-gray-900 mb-2">
            {language === 'en' ? 'Final Record Not Available' : 'السجل النهائي غير متاح'}
          </h2>
          <p className="text-sm text-gray-600 mb-6">
            {language === 'en' 
              ? 'This record is auto-generated after Form 5 approval.' 
              : 'يتم إنشاء هذا السجل تلقائيًا بعد الموافقة على النموذج 5.'}
          </p>
          <button
            onClick={() => navigate('/organization/hr/sanctions')}
            className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            {language === 'en' ? 'Back to Cases' : 'العودة إلى القضايا'}
          </button>
        </div>
      </div>
    );
  }

  const t = {
    title: language === 'en' ? 'Final Disciplinary Record' : 'السجل التأديبي النهائي',
    subtitle: language === 'en' ? 'Form 6 of 6 (Auto-Generated)' : 'النموذج 6 من 6 (مُنشأ تلقائيًا)',
    
    caseRef: language === 'en' ? 'Case Reference' : 'مرجع القضية',
    
    employeeDetails: language === 'en' ? 'Employee Details' : 'تفاصيل الموظف',
    staffId: language === 'en' ? 'Staff ID' : 'رقم الموظف',
    fullName: language === 'en' ? 'Full Name' : 'الاسم الكامل',
    position: language === 'en' ? 'Position' : 'الوظيفة',
    department: language === 'en' ? 'Department' : 'القسم',
    
    finalAction: language === 'en' ? 'Final Action Details' : 'تفاصيل الإجراء النهائي',
    finalActionTaken: language === 'en' ? 'Final Action Taken' : 'الإجراء النهائي المتخذ',
    effectiveDate: language === 'en' ? 'Effective Date' : 'تاريخ السريان',
    approvalAuthority: language === 'en' ? 'Approval Authority' : 'سلطة الموافقة',
    approvalDate: language === 'en' ? 'Approval Date' : 'تاريخ الموافقة',
    
    systemImpact: language === 'en' ? 'System Impact' : 'التأثير على النظام',
    payrollImpact: language === 'en' ? 'Payroll Impact' : 'تأثير الرواتب',
    statusChange: language === 'en' ? 'Status Change' : 'تغيير الحالة',
    yes: language === 'en' ? 'Yes' : 'نعم',
    no: language === 'en' ? 'No' : 'لا',
    
    metadata: language === 'en' ? 'Record Metadata' : 'بيانات السجل الوصفية',
    generatedDate: language === 'en' ? 'Generated Date' : 'تاريخ الإنشاء',
    generatedBy: language === 'en' ? 'Generated By' : 'أنشئ بواسطة',
    
    print: language === 'en' ? 'Print' : 'طباعة',
    back: language === 'en' ? 'Back to Cases' : 'العودة إلى القضايا',
    
    autoGeneratedNotice: language === 'en'
      ? '✅ This record was automatically generated upon Form 5 approval. It is now part of the employee\'s permanent HR file.'
      : '✅ تم إنشاء هذا السجل تلقائيًا عند الموافقة على النموذج 5. أصبح الآن جزءًا من ملف الموارد البشرية الدائم للموظف.',
    
    officialRecord: language === 'en' ? 'OFFICIAL RECORD' : 'سجل رسمي',
    permanentFile: language === 'en' ? 'Permanent HR File' : 'ملف الموارد البشرية الدائم'
  };

  return (
    <div className="min-h-screen bg-gray-50 print:bg-white">
      {/* Header - Hidden on print */}
      <div className="bg-white border-b border-gray-200 print:hidden">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <button
            onClick={() => navigate('/organization/hr/sanctions')}
            className={`flex items-center gap-2 text-gray-600 hover:text-gray-900 mb-4 ${isRTL ? 'flex-row-reverse' : ''}`}
          >
            <ArrowLeft className="w-4 h-4" />
            <span className="text-sm">{t.back}</span>
          </button>

          <div className={`flex items-center justify-between ${isRTL ? 'flex-row-reverse' : ''}`}>
            <div className={isRTL ? 'text-right' : 'text-left'}>
              <div className={`flex items-center gap-3 ${isRTL ? 'flex-row-reverse' : ''}`}>
                <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center">
                  <FileCheck className="w-6 h-6 text-green-600" />
                </div>
                <div>
                  <h1 className="text-2xl font-bold text-gray-900">{t.title}</h1>
                  <p className="text-sm text-gray-600">{t.subtitle}</p>
                </div>
              </div>
            </div>

            <button
              onClick={() => window.print()}
              className={`flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 ${isRTL ? 'flex-row-reverse' : ''}`}
            >
              <Printer className="w-4 h-4" />
              <span className="text-sm font-medium">{t.print}</span>
            </button>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-6 print:p-8">
        {/* Print Header */}
        <div className="hidden print:block mb-8 text-center border-b-2 border-gray-300 pb-6">
          <h1 className="text-2xl font-bold text-gray-900 mb-1">
            {language === 'en' ? 'FINAL DISCIPLINARY RECORD' : 'السجل التأديبي النهائي'}
          </h1>
          <p className="text-sm text-red-600 font-semibold">{t.officialRecord}</p>
          <p className="text-xs text-gray-500 mt-2">
            {language === 'en' ? '[Organization Name & Logo]' : '[اسم وشعار المنظمة]'}
          </p>
        </div>

        {/* Auto-generated notice */}
        <div className="mb-6 p-4 bg-green-50 border border-green-200 rounded-lg print:hidden">
          <div className={`flex items-start gap-3 ${isRTL ? 'flex-row-reverse' : ''}`}>
            <FileCheck className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
            <p className="text-sm text-green-800">{t.autoGeneratedNotice}</p>
          </div>
        </div>

        {/* Main Card */}
        <div className="bg-white rounded-lg border-2 border-gray-300 print:border-2 print:border-gray-400">
          <div className="p-6">
            {/* Case Reference Banner */}
            <div className="mb-6 p-4 bg-blue-50 border-2 border-blue-300 rounded-lg text-center">
              <p className="text-xs text-blue-700 mb-1">{t.caseRef}</p>
              <p className="text-2xl font-bold text-blue-900 font-mono">{finalRecord.caseReferenceNumber}</p>
            </div>

            {/* SECTION 1: Employee Details */}
            <div className="mb-8">
              <h2 className={`text-lg font-bold text-gray-900 mb-4 pb-2 border-b-2 border-gray-200 ${isRTL ? 'text-right' : ''}`}>
                {t.employeeDetails}
              </h2>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className={`block text-xs font-medium text-gray-600 mb-1 ${isRTL ? 'text-right' : ''}`}>
                    {t.staffId}
                  </label>
                  <div className="px-3 py-2 bg-gray-50 border border-gray-300 rounded font-mono text-gray-900">
                    {finalRecord.staffId}
                  </div>
                </div>

                <div>
                  <label className={`block text-xs font-medium text-gray-600 mb-1 ${isRTL ? 'text-right' : ''}`}>
                    {t.fullName}
                  </label>
                  <div className="px-3 py-2 bg-gray-50 border border-gray-300 rounded font-medium text-gray-900">
                    {finalRecord.fullName}
                  </div>
                </div>

                <div>
                  <label className={`block text-xs font-medium text-gray-600 mb-1 ${isRTL ? 'text-right' : ''}`}>
                    {t.position}
                  </label>
                  <div className="px-3 py-2 bg-gray-50 border border-gray-300 rounded text-gray-900">
                    {finalRecord.position}
                  </div>
                </div>

                <div>
                  <label className={`block text-xs font-medium text-gray-600 mb-1 ${isRTL ? 'text-right' : ''}`}>
                    {t.department}
                  </label>
                  <div className="px-3 py-2 bg-gray-50 border border-gray-300 rounded text-gray-900">
                    {finalRecord.department}
                  </div>
                </div>
              </div>
            </div>

            {/* SECTION 2: Final Action Details */}
            <div className="mb-8">
              <h2 className={`text-lg font-bold text-gray-900 mb-4 pb-2 border-b-2 border-gray-200 ${isRTL ? 'text-right' : ''}`}>
                {t.finalAction}
              </h2>

              {/* Final Action Taken (HIGHLIGHTED) */}
              <div className="mb-6">
                <label className={`block text-xs font-medium text-gray-600 mb-2 ${isRTL ? 'text-right' : ''}`}>
                  {t.finalActionTaken}
                </label>
                <div className="p-4 bg-amber-50 border-2 border-amber-300 rounded-lg">
                  <p className={`text-base font-semibold text-amber-900 ${isRTL ? 'text-right' : ''}`}>
                    {finalRecord.finalActionTaken}
                  </p>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className={`block text-xs font-medium text-gray-600 mb-1 ${isRTL ? 'text-right' : ''}`}>
                    {t.effectiveDate}
                  </label>
                  <div className="px-3 py-2 bg-gray-50 border border-gray-300 rounded text-gray-900">
                    {new Date(finalRecord.effectiveDate).toLocaleDateString()}
                  </div>
                </div>

                <div>
                  <label className={`block text-xs font-medium text-gray-600 mb-1 ${isRTL ? 'text-right' : ''}`}>
                    {t.approvalDate}
                  </label>
                  <div className="px-3 py-2 bg-gray-50 border border-gray-300 rounded text-gray-900">
                    {new Date(finalRecord.approvalDate).toLocaleDateString()}
                  </div>
                </div>

                <div className="md:col-span-2">
                  <label className={`block text-xs font-medium text-gray-600 mb-1 ${isRTL ? 'text-right' : ''}`}>
                    {t.approvalAuthority}
                  </label>
                  <div className="px-3 py-2 bg-gray-50 border border-gray-300 rounded text-gray-900">
                    {finalRecord.approvalAuthority}
                  </div>
                </div>
              </div>
            </div>

            {/* SECTION 3: System Impact */}
            <div className="mb-8">
              <h2 className={`text-lg font-bold text-gray-900 mb-4 pb-2 border-b-2 border-gray-200 ${isRTL ? 'text-right' : ''}`}>
                {t.systemImpact}
              </h2>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className={`block text-xs font-medium text-gray-600 mb-1 ${isRTL ? 'text-right' : ''}`}>
                    {t.payrollImpact}
                  </label>
                  <div className={`px-3 py-2 rounded font-medium border-2 ${
                    finalRecord.payrollImpact
                      ? 'bg-orange-50 border-orange-300 text-orange-900'
                      : 'bg-gray-50 border-gray-300 text-gray-900'
                  }`}>
                    {finalRecord.payrollImpact ? t.yes : t.no}
                  </div>
                </div>

                <div>
                  <label className={`block text-xs font-medium text-gray-600 mb-1 ${isRTL ? 'text-right' : ''}`}>
                    {t.statusChange}
                  </label>
                  <div className={`px-3 py-2 rounded font-medium border-2 ${
                    finalRecord.statusChange
                      ? 'bg-red-50 border-red-300 text-red-900'
                      : 'bg-gray-50 border-gray-300 text-gray-900'
                  }`}>
                    {finalRecord.statusChange ? t.yes : t.no}
                  </div>
                </div>
              </div>
            </div>

            {/* SECTION 4: Metadata */}
            <div className="mt-8 pt-6 border-t-2 border-gray-200">
              <h2 className={`text-sm font-bold text-gray-700 mb-3 ${isRTL ? 'text-right' : ''}`}>
                {t.metadata}
              </h2>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                <div>
                  <span className="font-medium text-gray-600">{t.generatedDate}:</span>{' '}
                  <span className="text-gray-900">{new Date(finalRecord.generatedDate).toLocaleString()}</span>
                </div>
                <div>
                  <span className="font-medium text-gray-600">{t.generatedBy}:</span>{' '}
                  <span className="text-gray-900">{finalRecord.generatedBy}</span>
                </div>
              </div>
            </div>

            {/* Official Stamp Area (Print only) */}
            <div className="hidden print:block mt-12 pt-8 border-t-2 border-gray-300">
              <div className="text-center">
                <p className="text-xs text-gray-500 mb-4">{t.permanentFile}</p>
                <div className="inline-block border-2 border-gray-400 rounded-lg px-8 py-4">
                  <p className="text-xs text-gray-600">
                    {language === 'en' ? '[Official Stamp & Signature]' : '[الختم الرسمي والتوقيع]'}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
