/**
 * Contract Management Page - Services Procurement
 * Handles: Create, View, Edit, Approve
 * Flow: CBA/QA/RFQ Winner → Create Contract → Add Milestones → Approve → SAC
 *
 * Auto-populated fields (read-only):
 * - Contract Number: CON-[OU]-[Year]-[Seq] (generated server-side)
 * - Vendor: from CBA/QA/RFQ winner
 * - Contract Value: from CBA/QA/RFQ winner quoted amount
 * - Currency: from CBA/QA/RFQ winner currency
 *
 * Uses inline translations pattern per IMSInlineTranslationsGuideline.md
 */
import { useState, useEffect, useMemo } from "react";
import { useParams, useLocation } from "wouter";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogDescription,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Alert, AlertDescription } from "@/components/ui/alert";
import {
  ArrowLeft,
  ArrowRight,
  ScrollText,
  Plus,
  Trash2,
  Save,
  CheckCircle,
  AlertCircle,
  FileText,
  DollarSign,
  Loader2,
  Lock,
  Info,
} from "lucide-react";
import { toast } from "sonner";
import { BackButton } from "@/components/BackButton";

// ============================================================================
// BILINGUAL TRANSLATIONS
// ============================================================================
const translations = {
  en: {
    // Page header
    contract: "Contract",
    type2Label: "Services",
    backToProcurement: "Back",

    // Status labels
    statusDraft: "Draft",
    statusPendingApproval: "Pending Approval",
    statusApproved: "Approved",
    statusActive: "Active",
    statusCompleted: "Completed",
    statusTerminated: "Terminated",

    // Contract form
    contractDetails: "Contract Details",
    createContract: "Create New Contract",
    contractNumber: "Contract Number",
    autoGenerated: "Auto-generated (CON-[OU]-[Year]-[Seq])",
    vendor: "Vendor",
    selectVendor: "Select vendor...",
    contractValue: "Contract Value",
    currency: "Currency",
    paymentStructure: "Payment Structure",
    lumpSum: "Lump Sum",
    percentageBased: "Percentage Based",
    fixedAmount: "Fixed Amount",
    deliverableBased: "Deliverable Based",
    retentionPercentage: "Retention %",
    startDate: "Start Date",
    endDate: "End Date",

    // Auto-populate
    autoPopulatedFields: "Auto-populated fields (read-only)",
    winnerDataReady: "Winner Data Ready",
    noWinnerData: "No Winner Data Available",
    noWinnerDataDesc: "Complete the evaluation process (CBA/QA/RFQ) and select a winner before creating a contract.",
    loadingWinnerData: "Loading winner data...",
    evaluationPath: "Evaluation Path",
    pathCba: "Comparative Bid Analysis (CBA)",
    pathQa: "Quotation Analysis (QA)",
    pathRfq: "Request for Quotation (RFQ)",

    // Actions
    save: "Save",
    cancel: "Cancel",
    approve: "Approve",
    approveContract: "Approve Contract",
    approveContractDesc: "Are you sure you want to approve this contract? Once approved, the SAC (Service Acceptance Certificate) step will be unlocked.",
    confirmApprove: "Yes, Approve",
    goToSac: "Go to SAC",

    // Milestones
    milestones: "Milestones",
    milestonesDesc: "Define payment milestones linked to deliverables",
    addMilestone: "Add Milestone",
    noMilestones: "No milestones defined yet. Add milestones to define the payment schedule.",
    milestoneTitle: "Title",
    milestoneDesc: "Description",
    milestoneAmount: "Amount",
    milestoneDueDate: "Due Date",
    saveMilestones: "Save Milestones",
    totalMilestones: "Total Milestones",
    milestoneTotal: "Total",
    milestoneExceedsContract: "Total milestone amount exceeds the contract value.",

    // Messages
    contractCreated: "Contract created successfully",
    contractUpdated: "Contract updated successfully",
    contractSubmitted: "Contract submitted for approval",
    contractApprovedSuccess: "Contract Approved",
    contractApprovedDesc: "This contract has been approved. You can now proceed to create the Service Acceptance Certificate (SAC).",
    contractRejected: "Contract rejected",
    milestonesAdded: "Milestones saved successfully",
    fillAllRequiredFields: "Please fill all required fields (start date, end date)",
    addAtLeastOneMilestone: "Add at least one milestone with a title",

    // Error states
    prNotFound: "Purchase Request Not Found",
    goBack: "Go Back",
    cbaRequired: "Prerequisite Not Met",
    cbaRequiredDesc: "The sourcing step (CBA award, QA approval, or RFQ quote submission) must be completed before creating a contract.",
  },
  ar: {
    // Page header
    contract: "العقد",
    type2Label: "النوع 2: استشاري",
    backToProcurement: "رجوع",

    // Status labels
    statusDraft: "مسودة",
    statusPendingApproval: "بانتظار الموافقة",
    statusApproved: "معتمد",
    statusActive: "نشط",
    statusCompleted: "مكتمل",
    statusTerminated: "منتهي",

    // Contract form
    contractDetails: "تفاصيل العقد",
    createContract: "إنشاء عقد جديد",
    contractNumber: "رقم العقد",
    autoGenerated: "سيتم إنشاؤه تلقائياً (CON-[OU]-[السنة]-[رقم])",
    vendor: "المورد",
    selectVendor: "اختر المورد...",
    contractValue: "قيمة العقد",
    currency: "العملة",
    paymentStructure: "هيكل الدفع",
    lumpSum: "مبلغ إجمالي",
    percentageBased: "على أساس النسبة",
    fixedAmount: "مبلغ ثابت",
    deliverableBased: "على أساس المخرجات",
    retentionPercentage: "نسبة الاحتجاز",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",

    // Auto-populate
    autoPopulatedFields: "حقول تلقائية (للقراءة فقط)",
    winnerDataReady: "بيانات الفائز جاهزة",
    noWinnerData: "لا توجد بيانات فائز",
    noWinnerDataDesc: "يجب إكمال عملية التقييم (CBA/QA/RFQ) واختيار الفائز قبل إنشاء العقد",
    loadingWinnerData: "جاري تحميل بيانات الفائز...",
    evaluationPath: "مسار التقييم",
    pathCba: "تحليل العطاءات المقارن (CBA)",
    pathQa: "تحليل عروض الأسعار (QA)",
    pathRfq: "طلب عرض أسعار (RFQ)",

    // Actions
    save: "حفظ",
    cancel: "إلغاء",
    approve: "اعتماد",
    approveContract: "اعتماد العقد",
    approveContractDesc: "هل أنت متأكد من اعتماد هذا العقد؟ بعد الاعتماد، سيتم فتح خطوة شهادة قبول الخدمة (SAC).",
    confirmApprove: "نعم، اعتماد",
    goToSac: "الذهاب إلى SAC",

    // Milestones
    milestones: "المراحل",
    milestonesDesc: "تحديد مراحل الدفع المرتبطة بالمخرجات",
    addMilestone: "إضافة مرحلة",
    noMilestones: "لم يتم تحديد مراحل بعد. أضف مراحل لتحديد جدول الدفع.",
    milestoneTitle: "العنوان",
    milestoneDesc: "الوصف",
    milestoneAmount: "المبلغ",
    milestoneDueDate: "تاريخ الاستحقاق",
    saveMilestones: "حفظ المراحل",
    totalMilestones: "إجمالي المراحل",
    milestoneTotal: "الإجمالي",
    milestoneExceedsContract: "إجمالي مبلغ المراحل يتجاوز قيمة العقد.",

    // Messages
    contractCreated: "تم إنشاء العقد بنجاح",
    contractUpdated: "تم تحديث العقد بنجاح",
    contractSubmitted: "تم تقديم العقد للموافقة",
    contractApprovedSuccess: "تم اعتماد العقد",
    contractApprovedDesc: "تم اعتماد هذا العقد. يمكنك الآن المتابعة لإنشاء شهادة قبول الخدمة (SAC).",
    contractRejected: "تم رفض العقد",
    milestonesAdded: "تم حفظ المراحل بنجاح",
    fillAllRequiredFields: "يرجى ملء جميع الحقول المطلوبة (تاريخ البدء، تاريخ الانتهاء)",
    addAtLeastOneMilestone: "أضف مرحلة واحدة على الأقل بعنوان",

    // Error states
    prNotFound: "طلب الشراء غير موجود",
    goBack: "رجوع",
    cbaRequired: "لم يتم استيفاء المتطلبات المسبقة",
    cbaRequiredDesc: "يجب إكمال خطوة التوريد (اعتماد التحليل المقارن أو اعتماد تحليل العروض أو تقديم عرض السعر) قبل إنشاء العقد.",
  },
};

// ============================================================================
// STATUS OPTIONS (bilingual labels)
// ============================================================================
const statusOptions = [
  { value: "draft", labelEn: "Draft", labelAr: "مسودة", color: "bg-gray-100 text-gray-700" },
  { value: "pending_approval", labelEn: "Pending Approval", labelAr: "بانتظار الموافقة", color: "bg-yellow-100 text-yellow-700" },
  { value: "approved", labelEn: "Approved", labelAr: "معتمد", color: "bg-green-100 text-green-700" },
  { value: "active", labelEn: "Active", labelAr: "نشط", color: "bg-blue-100 text-blue-700" },
  { value: "completed", labelEn: "Completed", labelAr: "مكتمل", color: "bg-purple-100 text-purple-700" },
  { value: "terminated", labelEn: "Terminated", labelAr: "منتهي", color: "bg-red-100 text-red-700" },
];

// ============================================================================
// INTERFACES
// ============================================================================
interface Milestone {
  id?: number;
  title: string;
  description: string;
  amount: string;
  currency: string;
  dueDate: string;
  orderIndex: number;
}

// ============================================================================
// COMPONENT
// ============================================================================
export default function ContractManagement() {  const { id } = useParams<{ id: string }>();
  const [, setLocation] = useLocation();
  const { language } = useLanguage();
  const isRTL = language === "ar";
  const t = translations[language as keyof typeof translations] || translations.en;
  const { user } = useAuth();
  const prId = parseInt(id!, 10);

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------
  const getStatusLabel = (status: string) => {
    const opt = statusOptions.find((o) => o.value === status);
    return isRTL ? (opt?.labelAr || status) : (opt?.labelEn || status);
  };

  const getStatusColor = (status: string) => {
    const opt = statusOptions.find((o) => o.value === status);
    return opt?.color || "bg-gray-100 text-gray-700";
  };

  const getPathLabel = (path: string) => {
    switch (path) {
      case 'cba': return t.pathCba;
      case 'qa': return t.pathQa;
      case 'rfq': return t.pathRfq;
      default: return path;
    }
  };

  // ---------------------------------------------------------------------------
  // Data fetching
  // ---------------------------------------------------------------------------
  const { data: pr, isLoading: prLoading } = trpc.logistics.prWorkspace.getById.useQuery(
    { id: prId },
    { enabled: !!id && prId > 0 }
  );

  const { data: existingContract, isLoading: contractLoading, refetch: refetchContract } =
    trpc.procurementPhaseA.contracts.getByPR.useQuery(
      { purchaseRequestId: prId },
      { enabled: !!id && prId > 0 }
    );

  // Fetch winner data for auto-populating contract fields (only when no contract exists)
  const { data: winnerData, isLoading: winnerLoading } =
    trpc.procurementPhaseA.contracts.getWinnerData.useQuery(
      { purchaseRequestId: prId },
      { enabled: !!id && prId > 0 && !existingContract }
    );

  const { data: existingMilestones, refetch: refetchMilestones } =
    trpc.procurementPhaseA.contracts.getMilestones.useQuery(
      { contractId: existingContract?.id || 0 },
      { enabled: !!existingContract?.id }
    );

  // ---------------------------------------------------------------------------
  // Form state (only user-editable fields)
  // ---------------------------------------------------------------------------
  const [paymentStructure, setPaymentStructure] = useState<string>("lump_sum");
  const [retentionPercentage, setRetentionPercentage] = useState("0");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [milestones, setMilestones] = useState<Milestone[]>([]);
  const [showApprovalDialog, setShowApprovalDialog] = useState(false);

  // ---------------------------------------------------------------------------
  // Pre-populate from existing contract
  // ---------------------------------------------------------------------------
  useEffect(() => {
    if (existingContract) {
      setPaymentStructure(existingContract.paymentStructure || "lump_sum");
      setRetentionPercentage(existingContract.retentionPercentage || "0");
      setStartDate(existingContract.startDate ? new Date(existingContract.startDate).toISOString().split("T")[0] : "");
      setEndDate(existingContract.endDate ? new Date(existingContract.endDate).toISOString().split("T")[0] : "");
    }
  }, [existingContract]);

  useEffect(() => {
    if (existingMilestones && existingMilestones.length > 0) {
      setMilestones(
        existingMilestones.map((m: any) => ({
          id: m.id,
          title: m.title || "",
          description: m.description || "",
          amount: m.amount || "0",
          currency: m.currency || existingContract?.currency || "USD",
          dueDate: m.dueDate ? new Date(m.dueDate).toISOString().split("T")[0] : "",
          orderIndex: m.orderIndex || 0,
        }))
      );
    }
  }, [existingMilestones]);

  // ---------------------------------------------------------------------------
  // Mutations
  // ---------------------------------------------------------------------------
  const createContract = trpc.procurementPhaseA.contracts.create.useMutation({
    onSuccess: (data) => {
      toast.success(`${t.contractCreated}: ${data.contractNumber}`);
      refetchContract();
    },
    onError: (err) => toast.error(err.message),
  });

  const updateContract = trpc.procurementPhaseA.contracts.update.useMutation({
    onSuccess: () => {
      toast.success(t.contractUpdated);
      refetchContract();
    },
    onError: (err) => toast.error(err.message),
  });

  const submitForApproval = trpc.procurementPhaseA.contracts.submitForApproval.useMutation({
    onSuccess: () => {
      toast.success(t.contractSubmitted);
      refetchContract();
    },
    onError: (err) => toast.error(err.message),
  });

  const approveContract = trpc.procurementPhaseA.contracts.approve.useMutation({
    onSuccess: (data) => {
      toast.success(
        data.status === "approved" ? t.contractApprovedSuccess : t.contractRejected
      );
      setShowApprovalDialog(false);
      refetchContract();
    },
    onError: (err) => toast.error(err.message),
  });

  const addMilestones = trpc.procurementPhaseA.contracts.addMilestones.useMutation({
    onSuccess: () => {
      toast.success(t.milestonesAdded);
      refetchMilestones();
    },
    onError: (err) => toast.error(err.message),
  });

  // ---------------------------------------------------------------------------
  // Computed
  // ---------------------------------------------------------------------------
  const isEditable = !existingContract || ["draft", "pending_approval"].includes(existingContract.status);
  const isDraft = !existingContract || existingContract.status === "draft";
  const isApproved = existingContract?.status === "approved" || existingContract?.status === "active";

  // Determine contract value and currency from existing contract or winner data
  const displayContractValue = existingContract?.contractValue || winnerData?.quotedAmount || "0";
  const displayCurrency = existingContract?.currency || winnerData?.currency || "USD";
  const displayVendorName = existingContract?.vendorName || winnerData?.vendorName || "-";

  const totalMilestoneAmount = useMemo(
    () => milestones.reduce((sum, m) => sum + parseFloat(m.amount || "0"), 0),
    [milestones]
  );

  // ---------------------------------------------------------------------------
  // Handlers
  // ---------------------------------------------------------------------------
  const handleSave = () => {
    if (!startDate || !endDate) {
      toast.error(t.fillAllRequiredFields);
      return;
    }

    if (existingContract) {
      updateContract.mutate({
        id: existingContract.id,
        retentionPercentage,
        endDate: new Date(endDate),
      });
    } else {
      // Create: backend auto-populates vendor, value, currency, and contract number
      createContract.mutate({
        purchaseRequestId: prId,
        paymentStructure: paymentStructure as any,
        retentionPercentage,
        startDate: new Date(startDate),
        endDate: new Date(endDate),
      });
    }
  };

  const handleApproval = () => {
    if (!existingContract) return;
    approveContract.mutate({
      id: existingContract.id,
      approve: true,
    });
  };

  const handleAddMilestone = () => {
    setMilestones([
      ...milestones,
      {
        title: "",
        description: "",
        amount: "0",
        currency: displayCurrency,
        dueDate: "",
        orderIndex: milestones.length,
      },
    ]);
  };

  const handleRemoveMilestone = (index: number) => {
    setMilestones(milestones.filter((_, i) => i !== index));
  };

  const handleMilestoneChange = (index: number, field: keyof Milestone, value: string) => {
    const updated = [...milestones];
    (updated[index] as any)[field] = value;
    setMilestones(updated);
  };

  const handleSaveMilestones = () => {
    if (!existingContract) return;
    const validMilestones = milestones.filter((m) => m.title.trim());
    if (validMilestones.length === 0) {
      toast.error(t.addAtLeastOneMilestone);
      return;
    }
    addMilestones.mutate({
      contractId: existingContract.id,
      milestones: validMilestones.map((m, i) => ({
        title: m.title,
        description: m.description || undefined,
        amount: m.amount,
        currency: m.currency || displayCurrency,
        dueDate: m.dueDate ? new Date(m.dueDate) : undefined,
        orderIndex: i,
      })),
    });
  };

  // ---------------------------------------------------------------------------
  // Loading state
  // ---------------------------------------------------------------------------
  if (prLoading || contractLoading) {
    return (
      <div className="p-6 space-y-4">
        <Skeleton className="h-10 w-64" />
        <Skeleton className="h-64 w-full" />
      </div>
    );
  }

  // ---------------------------------------------------------------------------
  // PR not found
  // ---------------------------------------------------------------------------
  if (!pr) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-6" dir={isRTL ? "rtl" : "ltr"}>
        <div className="bg-white rounded-lg border p-12 max-w-md text-center">
          <AlertCircle className="w-16 h-16 text-red-500 mx-auto mb-4" />
          <h2 className="text-2xl font-bold text-gray-900 mb-2">{t.prNotFound}</h2>
          <Button onClick={() => setLocation(`/organization/logistics/procurement-workspace/${prId}`)}>
            {t.goBack}
          </Button>
        </div>
      </div>
    );
  }

  // ---------------------------------------------------------------------------
  // No winner data and no existing contract - show guard
  // ---------------------------------------------------------------------------
  if (!winnerData && !winnerLoading && !existingContract) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-6" dir={isRTL ? "rtl" : "ltr"}>
        <div className="bg-white rounded-lg border p-12 max-w-md text-center">
          <AlertCircle className="w-16 h-16 text-yellow-500 mx-auto mb-4" />
          <h2 className="text-2xl font-bold text-gray-900 mb-2">{t.cbaRequired}</h2>
          <p className="text-gray-600 mb-6">{t.cbaRequiredDesc}</p>
          <Button onClick={() => setLocation(`/organization/logistics/procurement-workspace/${prId}`)}>
            {t.goBack}
          </Button>
        </div>
      </div>
    );
  }

  // ---------------------------------------------------------------------------
  // Main render
  // ---------------------------------------------------------------------------
  return (
    <div className="min-h-screen bg-gray-50" dir={isRTL ? "rtl" : "ltr"}>
      <div className="max-w-5xl mx-auto p-6">
        {/* Header */}
        <div className="mb-6">
          <BackButton onClick={() => setLocation(`/organization/logistics/procurement-workspace/${prId}`)} label={t.backToProcurement} />

          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-3 rounded-lg bg-purple-50">
                <ScrollText className="w-6 h-6 text-purple-600" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-gray-900">{t.contract}</h1>
                <p className="text-sm text-gray-500">
                  {pr.prNumber} — {t.type2Label}
                </p>
              </div>
            </div>
            {existingContract && (
              <Badge className={getStatusColor(existingContract.status)}>
                {getStatusLabel(existingContract.status)}
              </Badge>
            )}
          </div>
        </div>

        {/* Contract Form */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <FileText className="w-5 h-5" />
              {t.contractDetails}
            </CardTitle>
            <CardDescription>
              {existingContract
                ? `${t.contract}: ${existingContract.contractNumber}`
                : t.createContract}
            </CardDescription>
          </CardHeader>
          <CardContent>
            {/* Auto-populated fields section (read-only) */}
            <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg mb-6">
              <div className="flex items-center gap-2 mb-3">
                <Lock className="w-3.5 h-3.5 text-blue-600" />
                <span className="text-xs font-semibold text-blue-700 uppercase tracking-wide">
                  {t.autoPopulatedFields}
                </span>
                {!existingContract && winnerData && (
                  <Badge variant="outline" className="text-xs ms-auto">{getPathLabel(winnerData.path)}</Badge>
                )}
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Contract Number */}
                <div className="space-y-1">
                  <Label className="text-xs text-blue-700">{t.contractNumber}</Label>
                  <div className="flex items-center gap-2 p-2.5 bg-white/70 rounded border border-blue-100">
                    <Lock className="w-3 h-3 text-gray-400 shrink-0" />
                    <span className="text-sm font-mono text-gray-700" dir="ltr">
                      {existingContract?.contractNumber || t.autoGenerated}
                    </span>
                  </div>
                </div>

                {/* Vendor */}
                <div className="space-y-1">
                  <Label className="text-xs text-blue-700">{t.vendor}</Label>
                  <div className="flex items-center gap-2 p-2.5 bg-white/70 rounded border border-blue-100">
                    <Lock className="w-3 h-3 text-gray-400 shrink-0" />
                    <span className="text-sm font-medium">{displayVendorName}</span>
                  </div>
                </div>

                {/* Contract Value */}
                <div className="space-y-1">
                  <Label className="text-xs text-blue-700">{t.contractValue}</Label>
                  <div className="flex items-center gap-2 p-2.5 bg-white/70 rounded border border-blue-100">
                    <Lock className="w-3 h-3 text-gray-400 shrink-0" />
                    <span className="text-sm font-bold" dir="ltr">
                      {Number(displayContractValue).toLocaleString()}
                    </span>
                  </div>
                </div>

                {/* Currency */}
                <div className="space-y-1">
                  <Label className="text-xs text-blue-700">{t.currency}</Label>
                  <div className="flex items-center gap-2 p-2.5 bg-white/70 rounded border border-blue-100">
                    <Lock className="w-3 h-3 text-gray-400 shrink-0" />
                    <span className="text-sm font-medium">{displayCurrency}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* User-editable fields */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Payment Structure */}
              <div className="space-y-2">
                <Label>{t.paymentStructure}</Label>
                <Select
                  value={paymentStructure}
                  onValueChange={setPaymentStructure}
                  disabled={!isEditable}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="lump_sum">{t.lumpSum}</SelectItem>
                    <SelectItem value="percentage_based">{t.percentageBased}</SelectItem>
                    <SelectItem value="fixed_amount">{t.fixedAmount}</SelectItem>
                    <SelectItem value="deliverable_based">{t.deliverableBased}</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              {/* Retention */}
              <div className="space-y-2">
                <Label>{t.retentionPercentage}</Label>
                <Input
                  type="number"
                  step="0.01"
                  min="0"
                  max="100"
                  value={retentionPercentage}
                  onChange={(e) => setRetentionPercentage(e.target.value)}
                  disabled={!isEditable}
                  dir="ltr"
                />
              </div>

              {/* Start Date */}
              <div className="space-y-2">
                <Label>{t.startDate} *</Label>
                <Input
                  type="date"
                  value={startDate}
                  onChange={(e) => setStartDate(e.target.value)}
                  disabled={!!existingContract}
                  dir="ltr"
                />
              </div>

              {/* End Date */}
              <div className="space-y-2">
                <Label>{t.endDate} *</Label>
                <Input
                  type="date"
                  value={endDate}
                  onChange={(e) => setEndDate(e.target.value)}
                  disabled={!isEditable}
                  dir="ltr"
                />
              </div>

              {/* Project (auto-loaded from PR) */}
              <div className="space-y-2">
                <Label>{isRTL ? 'المشروع' : 'Project'}</Label>
                <Input
                  value={existingContract?.projectTitle || pr?.projectTitle || '-'}
                  disabled
                  className="bg-gray-50"
                />
              </div>

              {/* Donor (auto-loaded from PR) */}
              <div className="space-y-2">
                <Label>{isRTL ? 'الجهة المانحة' : 'Donor'}</Label>
                <Input
                  value={existingContract?.donorName || pr?.donorName || '-'}
                  disabled
                  className="bg-gray-50"
                />
              </div>

              {/* Budget Line (auto-loaded from PR) */}
              <div className="space-y-2 md:col-span-2">
                <Label>{isRTL ? 'بند الميزانية' : 'Budget Line'}</Label>
                <Input
                  value={(() => {
                    const title = existingContract?.budgetTitle || pr?.budgetTitle || '';
                    const code = existingContract?.budgetCode || pr?.budgetCode || '';
                    const sub = existingContract?.subBudgetLine || pr?.subBudgetLine || '';
                    const main = title || code || '-';
                    return sub ? `${main} — ${sub}` : main;
                  })()}
                  disabled
                  className="bg-gray-50"
                />
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex gap-3 mt-6 pt-6 border-t">
              {(isDraft || !existingContract) && (
                <Button
                  onClick={handleSave}
                  disabled={createContract.isPending || updateContract.isPending || (!existingContract && !winnerData)}
                  className="gap-2"
                >
                  {(createContract.isPending || updateContract.isPending) ? (
                    <Loader2 className="w-4 h-4 animate-spin" />
                  ) : (
                    <Save className="w-4 h-4" />
                  )}
                  {existingContract ? t.save : t.createContract}
                </Button>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Milestones Section */}
        {existingContract && (
          <Card className="mb-6">
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle className="flex items-center gap-2">
                  <DollarSign className="w-5 h-5" />
                  {t.milestones}
                </CardTitle>
                {isEditable && (
                  <Button variant="outline" size="sm" onClick={handleAddMilestone} className="gap-1">
                    <Plus className="w-4 h-4" />
                    {t.addMilestone}
                  </Button>
                )}
              </div>
              <CardDescription>{t.milestonesDesc}</CardDescription>
            </CardHeader>
            <CardContent>
              {milestones.length === 0 ? (
                <div className="text-center py-8 text-gray-500">
                  <DollarSign className="w-12 h-12 mx-auto mb-3 text-gray-300" />
                  <p>{t.noMilestones}</p>
                  {isEditable && (
                    <Button variant="outline" size="sm" onClick={handleAddMilestone} className="mt-3 gap-1">
                      <Plus className="w-4 h-4" />
                      {t.addMilestone}
                    </Button>
                  )}
                </div>
              ) : (
                <>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead className="w-10">#</TableHead>
                        <TableHead>{t.milestoneTitle}</TableHead>
                        <TableHead>{t.milestoneDesc}</TableHead>
                        <TableHead className="text-end">{t.milestoneAmount}</TableHead>
                        <TableHead>{t.milestoneDueDate}</TableHead>
                        {isEditable && <TableHead className="w-10"></TableHead>}
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {milestones.map((m, idx) => (
                        <TableRow key={idx}>
                          <TableCell className="text-gray-500">{idx + 1}</TableCell>
                          <TableCell>
                            {isEditable ? (
                              <Input
                                value={m.title}
                                onChange={(e) => handleMilestoneChange(idx, "title", e.target.value)}
                                placeholder={t.milestoneTitle}
                                className="min-w-[150px]"
                              />
                            ) : (
                              m.title
                            )}
                          </TableCell>
                          <TableCell>
                            {isEditable ? (
                              <Input
                                value={m.description}
                                onChange={(e) => handleMilestoneChange(idx, "description", e.target.value)}
                                placeholder={t.milestoneDesc}
                                className="min-w-[150px]"
                              />
                            ) : (
                              m.description
                            )}
                          </TableCell>
                          <TableCell className="text-end">
                            {isEditable ? (
                              <Input
                                type="number"
                                step="0.01"
                                value={m.amount}
                                onChange={(e) => handleMilestoneChange(idx, "amount", e.target.value)}
                                className="min-w-[100px] text-end"
                                dir="ltr"
                              />
                            ) : (
                              <span dir="ltr">{displayCurrency} {Number(m.amount).toLocaleString()}</span>
                            )}
                          </TableCell>
                          <TableCell>
                            {isEditable ? (
                              <Input
                                type="date"
                                value={m.dueDate}
                                onChange={(e) => handleMilestoneChange(idx, "dueDate", e.target.value)}
                                dir="ltr"
                              />
                            ) : (
                              m.dueDate ? new Date(m.dueDate).toLocaleDateString() : "—"
                            )}
                          </TableCell>
                          {isEditable && (
                            <TableCell>
                              <Button
                                variant="ghost"
                                size="icon"
                                onClick={() => handleRemoveMilestone(idx)}
                                className="text-red-500 hover:text-red-700"
                              >
                                <Trash2 className="w-4 h-4" />
                              </Button>
                            </TableCell>
                          )}
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>

                  {/* Milestone Summary */}
                  <div className="flex items-center justify-between mt-4 pt-4 border-t">
                    <div className="text-sm text-gray-500">
                      {t.totalMilestones}: {milestones.length}
                    </div>
                    <div className="flex items-center gap-4">
                      <div className="text-sm">
                        <span className="text-gray-500">{t.milestoneTotal}:</span>{" "}
                        <span dir="ltr" className={`font-bold ${totalMilestoneAmount > parseFloat(displayContractValue || "0") ? "text-red-600" : "text-gray-900"}`}>
                          {displayCurrency} {totalMilestoneAmount.toLocaleString()}
                        </span>
                        <span className="text-gray-400 mx-1">/</span>
                        <span dir="ltr" className="text-gray-600">{displayCurrency} {Number(displayContractValue || 0).toLocaleString()}</span>
                      </div>
                      {isEditable && (
                        <Button
                          onClick={handleSaveMilestones}
                          disabled={addMilestones.isPending}
                          size="sm"
                          className="gap-1"
                        >
                          {addMilestones.isPending ? (
                            <Loader2 className="w-4 h-4 animate-spin" />
                          ) : (
                            <Save className="w-4 h-4" />
                          )}
                          {t.saveMilestones}
                        </Button>
                      )}
                    </div>
                  </div>

                  {totalMilestoneAmount > parseFloat(displayContractValue || "0") && (
                    <Alert variant="destructive" className="mt-3">
                      <AlertCircle className="h-4 w-4" />
                      <AlertDescription>{t.milestoneExceedsContract}</AlertDescription>
                    </Alert>
                  )}
                </>
              )}
            </CardContent>
          </Card>
        )}

        {/* Approve Button - shown after milestones when contract is draft and saved */}
        {isDraft && existingContract && milestones.length > 0 && (
          <div className="flex justify-end mb-6">
            <Button
              onClick={() => setShowApprovalDialog(true)}
              className="gap-2 bg-green-600 hover:bg-green-700 text-white px-8 py-3 text-base"
              size="lg"
            >
              <CheckCircle className="w-5 h-5" />
              {t.approve}
            </Button>
          </div>
        )}

        {/* Contract Summary (when approved) */}
        {isApproved && existingContract && (
          <Card className="border-green-200 bg-green-50">
            <CardContent className="pt-6">
              <div className="flex items-center gap-3 mb-4">
                <CheckCircle className="w-6 h-6 text-green-600" />
                <h3 className="text-lg font-bold text-green-900">{t.contractApprovedSuccess}</h3>
              </div>
              <p className="text-green-800 text-sm">{t.contractApprovedDesc}</p>
              <Button
                variant="outline"
                className="mt-4 gap-2 border-green-300 text-green-700 hover:bg-green-100"
                onClick={() => setLocation(`/organization/logistics/procurement-workspace/sac/${prId}`)}
              >
                <FileText className="w-4 h-4" />
                {t.goToSac}
              </Button>
            </CardContent>
          </Card>
        )}

        {/* Approval Confirmation Dialog */}
        <Dialog open={showApprovalDialog} onOpenChange={setShowApprovalDialog}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>{t.approveContract}</DialogTitle>
              <DialogDescription>{t.approveContractDesc}</DialogDescription>
            </DialogHeader>
            <DialogFooter>
              <Button variant="outline" onClick={() => setShowApprovalDialog(false)}>
                {t.cancel}
              </Button>
              <Button
                onClick={handleApproval}
                disabled={approveContract.isPending}
                className="bg-green-600 hover:bg-green-700"
              >
                {approveContract.isPending && (
                  <Loader2 className="w-4 h-4 animate-spin me-2" />
                )}
                {t.confirmApprove}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    </div>
  );
}
