import { useState, useMemo } from 'react';
import { useLocation } from 'wouter';
import {
  Download,
  TrendingUp,
  TrendingDown,
  Users,
  DollarSign,
  CheckCircle2,
  Target,
  AlertCircle,
  AlertTriangle,
  Activity,
  Shield,
  BarChart3,
  PieChart as PieChartIcon,
  Calendar,
  Filter,
  RefreshCw,
  Info,
  Loader2,
} from 'lucide-react';
import { useLanguage, formatNumber, formatCurrency } from '@/contexts/LanguageContext';
import { useAutoProgramsReport, type DateRangePreset } from '@/hooks/useAutoProgramsReport';
import { useAuth } from '@/_core/hooks/useAuth';
import {
  PieChart,
  Pie,
  Cell,
  BarChart,
  Bar,
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from 'recharts';
import { useLocalTranslations } from '@/i18n/useLocalTranslations';
import { BackButton } from '@/components/BackButton';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Skeleton } from '@/components/ui/skeleton';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Calendar as CalendarComponent } from '@/components/ui/calendar';
import { Button } from '@/components/ui/button';
import { format } from 'date-fns';

// ============================================================
// TRANSLATIONS
// ============================================================

const L = {
  en: {
    title: 'Auto Programs Report',
    subtitle: 'Real-time intelligence dashboard auto-generated from live ERP data',
    exportPdf: 'Export PDF',
    refresh: 'Refresh',
    allProjects: 'All Projects',
    selectProject: 'Select Project',
    dateRange: 'Date Range',
    from: 'From',
    to: 'To',
    currentYear: 'Current Year',
    lastYear: 'Last Year',
    last6Months: 'Last 6 Months',
    lastQuarter: 'Last Quarter',
    custom: 'Custom',
    executiveSummary: 'Executive Summary',
    financialAnalytics: 'Financial Analytics',
    implementationPerformance: 'Implementation Performance',
    riskCompliance: 'Risk & Compliance',
    beneficiaryAnalytics: 'Beneficiary Analytics',
    projectHealth: 'Project Health',
    totalProjects: 'Total Projects',
    activeProjects: 'Active Projects',
    completedProjects: 'Completed',
    atRiskProjects: 'At Risk',
    criticalProjects: 'Critical',
    totalBudget: 'Total Budget',
    totalSpent: 'Total Spent',
    utilization: 'Utilization',
    beneficiariesReached: 'Beneficiaries Reached',
    overdueReports: 'Overdue Reports',
    expiringProjects: 'Expiring Soon',
    budgetVsSpent: 'Budget vs Spent',
    monthlyBurnTrend: 'Monthly Burn Trend',
    categoryBreakdown: 'Category Breakdown',
    donorFunding: 'Donor Funding',
    burnRate: 'Burn Rate',
    remainingBalance: 'Remaining Balance',
    projectedEnd: 'Projected End',
    perMonth: '/month',
    activityCompletion: 'Activity Completion',
    indicatorAchievement: 'Indicator Achievement',
    taskCompletion: 'Task Completion',
    activities: 'Activities',
    indicators: 'Indicators',
    tasks: 'Tasks',
    completed: 'Completed',
    delayed: 'Delayed',
    offTrack: 'Off Track',
    overdue: 'Overdue',
    achieved: 'Achieved',
    totalRisks: 'Total Risks',
    highRisks: 'High Risks',
    criticalRisks: 'Critical Risks',
    unresolvedRisks: 'Unresolved',
    complianceScore: 'Compliance Score',
    scheduledReports: 'Scheduled Reports',
    totalReached: 'Total Reached',
    male: 'Male',
    female: 'Female',
    ageGroups: 'Age Groups',
    communityTypes: 'Community Types',
    vulnerableGroups: 'Vulnerable Groups',
    healthy: 'Healthy',
    watchlist: 'Watchlist',
    atRisk: 'At Risk',
    critical: 'Critical',
    noData: 'No data available for the selected filters',
    noDataMessage: 'Try adjusting the date range or project selection',
    loading: 'Loading report data...',
    autoGenerated: 'Auto-generated from live system data',
    budget: 'Budget',
    spent: 'Spent',
    project: 'Project',
    status: 'Status',
    health: 'Health',
    score: 'Score',
  },
  ar: {
    title: 'تقرير البرامج التلقائي',
    subtitle: 'لوحة معلومات استخباراتية في الوقت الفعلي يتم إنشاؤها تلقائياً من بيانات النظام',
    exportPdf: 'تصدير PDF',
    refresh: 'تحديث',
    allProjects: 'جميع المشاريع',
    selectProject: 'اختر مشروع',
    dateRange: 'النطاق الزمني',
    from: 'من',
    to: 'إلى',
    currentYear: 'السنة الحالية',
    lastYear: 'السنة الماضية',
    last6Months: 'آخر 6 أشهر',
    lastQuarter: 'الربع الأخير',
    custom: 'مخصص',
    executiveSummary: 'الملخص التنفيذي',
    financialAnalytics: 'التحليلات المالية',
    implementationPerformance: 'أداء التنفيذ',
    riskCompliance: 'المخاطر والامتثال',
    beneficiaryAnalytics: 'تحليلات المستفيدين',
    projectHealth: 'صحة المشاريع',
    totalProjects: 'إجمالي المشاريع',
    activeProjects: 'المشاريع النشطة',
    completedProjects: 'المكتملة',
    atRiskProjects: 'معرضة للخطر',
    criticalProjects: 'حرجة',
    totalBudget: 'إجمالي الميزانية',
    totalSpent: 'إجمالي الإنفاق',
    utilization: 'نسبة الاستخدام',
    beneficiariesReached: 'المستفيدون المخدومون',
    overdueReports: 'التقارير المتأخرة',
    expiringProjects: 'تنتهي قريباً',
    budgetVsSpent: 'الميزانية مقابل الإنفاق',
    monthlyBurnTrend: 'اتجاه الإنفاق الشهري',
    categoryBreakdown: 'توزيع الفئات',
    donorFunding: 'تمويل المانحين',
    burnRate: 'معدل الإنفاق',
    remainingBalance: 'الرصيد المتبقي',
    projectedEnd: 'النهاية المتوقعة',
    perMonth: '/شهر',
    activityCompletion: 'إنجاز الأنشطة',
    indicatorAchievement: 'تحقيق المؤشرات',
    taskCompletion: 'إنجاز المهام',
    activities: 'الأنشطة',
    indicators: 'المؤشرات',
    tasks: 'المهام',
    completed: 'مكتمل',
    delayed: 'متأخر',
    offTrack: 'خارج المسار',
    overdue: 'متأخر',
    achieved: 'محقق',
    totalRisks: 'إجمالي المخاطر',
    highRisks: 'مخاطر عالية',
    criticalRisks: 'مخاطر حرجة',
    unresolvedRisks: 'غير محلولة',
    complianceScore: 'درجة الامتثال',
    scheduledReports: 'التقارير المجدولة',
    totalReached: 'إجمالي المخدومين',
    male: 'ذكور',
    female: 'إناث',
    ageGroups: 'الفئات العمرية',
    communityTypes: 'أنواع المجتمعات',
    vulnerableGroups: 'الفئات الهشة',
    healthy: 'صحي',
    watchlist: 'مراقبة',
    atRisk: 'معرض للخطر',
    critical: 'حرج',
    noData: 'لا توجد بيانات للفلاتر المحددة',
    noDataMessage: 'حاول تعديل النطاق الزمني أو اختيار المشروع',
    loading: 'جاري تحميل بيانات التقرير...',
    autoGenerated: 'يتم إنشاؤه تلقائياً من بيانات النظام الحية',
    budget: 'الميزانية',
    spent: 'الإنفاق',
    project: 'المشروع',
    status: 'الحالة',
    health: 'الصحة',
    score: 'الدرجة',
  },
};

// ============================================================
// CHART COLORS
// ============================================================

const CHART_COLORS = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', '#06b6d4', '#ec4899', '#84cc16'];

const HEALTH_COLORS: Record<string, string> = {
  Healthy: '#10b981',
  Watchlist: '#f59e0b',
  'At Risk': '#f97316',
  Critical: '#ef4444',
  Completed: '#6b7280',
};

// ============================================================
// MAIN COMPONENT
// ============================================================

export default function AutoProgramsReport() {
  const t = useLocalTranslations(L);
  const { language, isRTL } = useLanguage();
  const [, setLocation] = useLocation();
  const { user } = useAuth();

  const {
    data,
    projectsList,
    isLoading,
    isRefetching,
    filters,
    setDateRangePreset,
    setCustomRange,
    setSelectedProjectId,
    refetch,
    resetFilters,
  } = useAutoProgramsReport();

  const [activeTab, setActiveTab] = useState('executive');

  // Date range preset options
  const datePresets: { value: DateRangePreset; label: string }[] = [
    { value: 'current_year', label: t.currentYear },
    { value: 'last_year', label: t.lastYear },
    { value: 'last_6_months', label: t.last6Months },
    { value: 'last_quarter', label: t.lastQuarter },
    { value: 'custom', label: t.custom },
  ];

  // ============================================================
  // LOADING STATE
  // ============================================================

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 p-6" dir={isRTL ? 'rtl' : 'ltr'}>
        <div className="max-w-7xl mx-auto space-y-6">
          <div className="flex items-center gap-4">
            <Skeleton className="h-8 w-8" />
            <div>
              <Skeleton className="h-7 w-64 mb-2" />
              <Skeleton className="h-4 w-96" />
            </div>
          </div>
          <Skeleton className="h-16 w-full" />
          <div className="grid grid-cols-4 gap-4">
            {[1, 2, 3, 4].map(i => <Skeleton key={i} className="h-28" />)}
          </div>
          <Skeleton className="h-80 w-full" />
        </div>
      </div>
    );
  }

  const hasData = data && data.executiveSummary.totalProjects > 0;

  // ============================================================
  // RENDER
  // ============================================================

  return (
    <div className="min-h-screen bg-gray-50 p-6" dir={isRTL ? 'rtl' : 'ltr'}>
      <div className="max-w-7xl mx-auto space-y-6">

        {/* HEADER */}
        <div className="flex items-start gap-2">
          <BackButton onClick={() => setLocation('/organization/projects')} iconOnly />
          <div className="flex-1 text-start">
            <h1 className="text-2xl font-bold text-gray-900">{t.title}</h1>
            <p className="text-gray-600 mt-1 text-sm">{t.subtitle}</p>
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => refetch()}
              disabled={isRefetching}
              className="flex items-center gap-2"
            >
              <RefreshCw className={`w-4 h-4 ${isRefetching ? 'animate-spin' : ''}`} />
              {t.refresh}
            </Button>
            <Button
              size="sm"
              className="flex items-center gap-2"
              onClick={() => {
                // TODO: Connect to trpc.autoProgramsReport.exportPdf
                alert('PDF export coming soon');
              }}
            >
              <Download className="w-4 h-4" />
              {t.exportPdf}
            </Button>
          </div>
        </div>

        {/* FILTERS BAR */}
        <Card>
          <CardContent className="p-4">
            <div className="flex flex-wrap items-center gap-4">
              {/* Date Range Preset */}
              <div className="flex items-center gap-2">
                <Calendar className="w-4 h-4 text-gray-500" />
                <Select
                  value={filters.dateRangePreset}
                  onValueChange={(val) => setDateRangePreset(val as DateRangePreset)}
                >
                  <SelectTrigger className="w-[160px] h-9">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {datePresets.map(p => (
                      <SelectItem key={p.value} value={p.value}>{p.label}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Custom Date Range */}
              {filters.dateRangePreset === 'custom' && (
                <div className="flex items-center gap-2">
                  <input
                    type="date"
                    value={filters.customRange.fromDate}
                    onChange={(e) => setCustomRange({ ...filters.customRange, fromDate: e.target.value })}
                    className="px-3 py-1.5 border border-gray-300 rounded-md text-sm h-9"
                  />
                  <span className="text-gray-500 text-sm">—</span>
                  <input
                    type="date"
                    value={filters.customRange.toDate}
                    onChange={(e) => setCustomRange({ ...filters.customRange, toDate: e.target.value })}
                    className="px-3 py-1.5 border border-gray-300 rounded-md text-sm h-9"
                  />
                </div>
              )}

              {/* Project Filter */}
              <div className="flex items-center gap-2">
                <Filter className="w-4 h-4 text-gray-500" />
                <Select
                  value={filters.projectId?.toString() || 'all'}
                  onValueChange={(val) => setSelectedProjectId(val === 'all' ? undefined : Number(val))}
                >
                  <SelectTrigger className="w-[200px] h-9">
                    <SelectValue placeholder={t.selectProject} />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">{t.allProjects}</SelectItem>
                    {projectsList.map(p => (
                      <SelectItem key={p.id} value={p.id.toString()}>
                        {p.title}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Auto-generated badge */}
              <div className="flex items-center gap-2 px-3 py-1.5 bg-blue-50 rounded-md ms-auto">
                <Info className="w-4 h-4 text-blue-600" />
                <span className="text-xs text-blue-700">{t.autoGenerated}</span>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* NO DATA STATE */}
        {!hasData && (
          <Card className="border-yellow-200 bg-yellow-50">
            <CardContent className="p-6">
              <div className="flex items-start gap-3">
                <AlertCircle className="w-5 h-5 text-yellow-600 flex-shrink-0 mt-0.5" />
                <div className="text-start">
                  <h3 className="font-semibold text-yellow-900">{t.noData}</h3>
                  <p className="text-sm text-yellow-700 mt-1">{t.noDataMessage}</p>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* MAIN CONTENT */}
        {hasData && data && (
          <>
            {/* KPI CARDS */}
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
              <KPICard
                title={t.totalProjects}
                value={data.executiveSummary.totalProjects}
                icon={<Target className="w-5 h-5" />}
                color="blue"
              />
              <KPICard
                title={t.activeProjects}
                value={data.executiveSummary.activeProjects}
                icon={<Activity className="w-5 h-5" />}
                color="green"
              />
              <KPICard
                title={t.totalBudget}
                value={formatCurrency(data.executiveSummary.totalBudget, 'USD', language)}
                icon={<DollarSign className="w-5 h-5" />}
                color="purple"
              />
              <KPICard
                title={t.utilization}
                value={`${data.executiveSummary.utilizationPercent}%`}
                icon={<TrendingUp className="w-5 h-5" />}
                color="orange"
                trend={data.executiveSummary.utilizationPercent > 70 ? 'up' : 'down'}
              />
              <KPICard
                title={t.beneficiariesReached}
                value={formatNumber(data.executiveSummary.totalBeneficiaries)}
                icon={<Users className="w-5 h-5" />}
                color="cyan"
              />
              <KPICard
                title={t.overdueReports}
                value={data.executiveSummary.overdueReports}
                icon={<AlertTriangle className="w-5 h-5" />}
                color={data.executiveSummary.overdueReports > 0 ? 'red' : 'green'}
              />
            </div>

            {/* TABS */}
            <Tabs value={activeTab} onValueChange={setActiveTab}>
              <TabsList className="grid w-full grid-cols-5">
                <TabsTrigger value="executive">{t.executiveSummary}</TabsTrigger>
                <TabsTrigger value="financial">{t.financialAnalytics}</TabsTrigger>
                <TabsTrigger value="implementation">{t.implementationPerformance}</TabsTrigger>
                <TabsTrigger value="risk">{t.riskCompliance}</TabsTrigger>
                <TabsTrigger value="beneficiaries">{t.beneficiaryAnalytics}</TabsTrigger>
              </TabsList>

              {/* TAB: Executive Summary */}
              <TabsContent value="executive" className="space-y-6 mt-6">
                <ExecutiveSummaryTab data={data} t={t} language={language} isRTL={isRTL} />
              </TabsContent>

              {/* TAB: Financial Analytics */}
              <TabsContent value="financial" className="space-y-6 mt-6">
                <FinancialAnalyticsTab data={data} t={t} language={language} isRTL={isRTL} />
              </TabsContent>

              {/* TAB: Implementation Performance */}
              <TabsContent value="implementation" className="space-y-6 mt-6">
                <ImplementationTab data={data} t={t} isRTL={isRTL} />
              </TabsContent>

              {/* TAB: Risk & Compliance */}
              <TabsContent value="risk" className="space-y-6 mt-6">
                <RiskComplianceTab data={data} t={t} isRTL={isRTL} />
              </TabsContent>

              {/* TAB: Beneficiary Analytics */}
              <TabsContent value="beneficiaries" className="space-y-6 mt-6">
                <BeneficiaryTab data={data} t={t} language={language} isRTL={isRTL} />
              </TabsContent>
            </Tabs>

            {/* PROJECT HEALTH TABLE */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Shield className="w-5 h-5" />
                  {t.projectHealth}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ProjectHealthTable data={data.projectHealthList} t={t} language={language} isRTL={isRTL} />
              </CardContent>
            </Card>
          </>
        )}
      </div>
    </div>
  );
}

// ============================================================
// SUB-COMPONENTS
// ============================================================

// KPI Card
interface KPICardProps {
  title: string;
  value: string | number;
  icon: React.ReactNode;
  color: 'blue' | 'green' | 'purple' | 'orange' | 'cyan' | 'red';
  trend?: 'up' | 'down';
}

function KPICard({ title, value, icon, color, trend }: KPICardProps) {
  const colorClasses: Record<string, string> = {
    blue: 'bg-blue-50 text-blue-600',
    green: 'bg-green-50 text-green-600',
    purple: 'bg-purple-50 text-purple-600',
    orange: 'bg-orange-50 text-orange-600',
    cyan: 'bg-cyan-50 text-cyan-600',
    red: 'bg-red-50 text-red-600',
  };

  return (
    <Card className="relative overflow-hidden">
      <CardContent className="p-4">
        <div className="flex items-start justify-between">
          <div className="flex-1 text-start">
            <p className="text-xs font-medium text-gray-500 mb-1">{title}</p>
            <p className="text-xl font-bold text-gray-900 ltr-safe">{value}</p>
          </div>
          <div className={`p-2 rounded-lg ${colorClasses[color]}`}>
            {icon}
          </div>
        </div>
        {trend && (
          <div className="absolute bottom-2 end-2">
            {trend === 'up' ? (
              <TrendingUp className="w-3 h-3 text-green-500" />
            ) : (
              <TrendingDown className="w-3 h-3 text-red-500" />
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// Executive Summary Tab
function ExecutiveSummaryTab({ data, t, language, isRTL }: { data: any; t: any; language: string; isRTL: boolean }) {
  const summary = data.executiveSummary;
  const healthList = data.projectHealthList;

  // Health distribution for pie chart
  const healthDistribution = useMemo(() => {
    const dist: Record<string, number> = {};
    for (const p of healthList) {
      dist[p.healthStatus] = (dist[p.healthStatus] || 0) + 1;
    }
    return Object.entries(dist).map(([name, value]) => ({
      name,
      value,
      color: HEALTH_COLORS[name] || '#6b7280',
    }));
  }, [healthList]);

  return (
    <>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Project Status Distribution */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">{t.projectHealth}</CardTitle>
          </CardHeader>
          <CardContent>
            {healthDistribution.length > 0 ? (
              <ResponsiveContainer width="100%" height={250}>
                <PieChart>
                  <Pie
                    data={healthDistribution}
                    cx="50%"
                    cy="50%"
                    labelLine={false}
                    label={(entry) => `${entry.name}: ${entry.value}`}
                    outerRadius={80}
                    fill="#8884d8"
                    dataKey="value"
                  >
                    {healthDistribution.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
            ) : (
              <EmptyChart message={t.noData} />
            )}
          </CardContent>
        </Card>

        {/* Key Metrics */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">{t.executiveSummary}</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <MetricRow label={t.totalProjects} value={summary.totalProjects} />
            <MetricRow label={t.activeProjects} value={summary.activeProjects} />
            <MetricRow label={t.completedProjects} value={summary.completedProjects} />
            <MetricRow label={t.atRiskProjects} value={summary.atRiskProjects} color="orange" />
            <MetricRow label={t.criticalProjects} value={summary.criticalProjects} color="red" />
            <MetricRow label={t.expiringProjects} value={summary.expiringProjects} color="yellow" />
            <MetricRow label={t.overdueReports} value={summary.overdueReports} color="red" />
            <div className="pt-2 border-t">
              <MetricRow
                label={t.totalBudget}
                value={formatCurrency(summary.totalBudget, 'USD')}
              />
              <MetricRow
                label={t.totalSpent}
                value={formatCurrency(summary.totalSpent, 'USD')}
              />
            </div>
          </CardContent>
        </Card>
      </div>
    </>
  );
}

// Financial Analytics Tab
function FinancialAnalyticsTab({ data, t, language, isRTL }: { data: any; t: any; language: string; isRTL: boolean }) {
  const fin = data.financialAnalytics;

  return (
    <>
      {/* Burn Rate Projection */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card>
          <CardContent className="p-4 text-center">
            <p className="text-xs text-gray-500 mb-1">{t.burnRate}</p>
            <p className="text-2xl font-bold text-gray-900 ltr-safe">
              {formatCurrency(fin.burnRateProjection.currentBurnRate, 'USD')}
            </p>
            <p className="text-xs text-gray-400">{t.perMonth}</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 text-center">
            <p className="text-xs text-gray-500 mb-1">{t.remainingBalance}</p>
            <p className="text-2xl font-bold text-gray-900 ltr-safe">
              {formatCurrency(fin.burnRateProjection.remainingBalance, 'USD')}
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 text-center">
            <p className="text-xs text-gray-500 mb-1">{t.projectedEnd}</p>
            <p className="text-2xl font-bold text-gray-900 ltr-safe">
              {fin.burnRateProjection.projectedEndDate || '—'}
            </p>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Budget vs Spent */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">{t.budgetVsSpent}</CardTitle>
          </CardHeader>
          <CardContent>
            {fin.budgetVsSpent.length > 0 ? (
              <ResponsiveContainer width="100%" height={280}>
                <BarChart data={fin.budgetVsSpent}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="projectName" tick={{ fontSize: 10 }} />
                  <YAxis />
                  <Tooltip />
                  <Legend />
                  <Bar dataKey="budget" fill="#3b82f6" name={t.budget} />
                  <Bar dataKey="spent" fill="#10b981" name={t.spent} />
                </BarChart>
              </ResponsiveContainer>
            ) : (
              <EmptyChart message={t.noData} />
            )}
          </CardContent>
        </Card>

        {/* Monthly Burn Trend */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">{t.monthlyBurnTrend}</CardTitle>
          </CardHeader>
          <CardContent>
            {fin.monthlyBurnTrend.length > 0 ? (
              <ResponsiveContainer width="100%" height={280}>
                <LineChart data={fin.monthlyBurnTrend}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="month" tick={{ fontSize: 10 }} />
                  <YAxis />
                  <Tooltip />
                  <Legend />
                  <Line type="monotone" dataKey="spent" stroke="#ef4444" name={t.spent} strokeWidth={2} />
                  <Line type="monotone" dataKey="budget" stroke="#3b82f6" name={t.budget} strokeWidth={2} />
                </LineChart>
              </ResponsiveContainer>
            ) : (
              <EmptyChart message={t.noData} />
            )}
          </CardContent>
        </Card>
      </div>

      {/* Category Breakdown & Donor Funding */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle className="text-base">{t.categoryBreakdown}</CardTitle>
          </CardHeader>
          <CardContent>
            {fin.categoryBreakdown.length > 0 ? (
              <ResponsiveContainer width="100%" height={250}>
                <PieChart>
                  <Pie
                    data={fin.categoryBreakdown}
                    cx="50%"
                    cy="50%"
                    labelLine={false}
                    label={(entry) => entry.category}
                    outerRadius={80}
                    fill="#8884d8"
                    dataKey="budget"
                    nameKey="category"
                  >
                    {fin.categoryBreakdown.map((_: any, index: number) => (
                      <Cell key={`cell-${index}`} fill={CHART_COLORS[index % CHART_COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
            ) : (
              <EmptyChart message={t.noData} />
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-base">{t.donorFunding}</CardTitle>
          </CardHeader>
          <CardContent>
            {fin.donorFunding.length > 0 ? (
              <ResponsiveContainer width="100%" height={250}>
                <BarChart data={fin.donorFunding} layout="vertical">
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis type="number" />
                  <YAxis dataKey="donor" type="category" width={100} tick={{ fontSize: 10 }} />
                  <Tooltip />
                  <Legend />
                  <Bar dataKey="amount" fill="#8b5cf6" name={t.budget} />
                  <Bar dataKey="spent" fill="#10b981" name={t.spent} />
                </BarChart>
              </ResponsiveContainer>
            ) : (
              <EmptyChart message={t.noData} />
            )}
          </CardContent>
        </Card>
      </div>
    </>
  );
}

// Implementation Performance Tab
function ImplementationTab({ data, t, isRTL }: { data: any; t: any; isRTL: boolean }) {
  const impl = data.implementationPerformance;

  return (
    <>
      {/* Progress Bars */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm font-medium">{t.activityCompletion}</span>
              <span className="text-sm font-bold">{impl.activityCompletionPercent}%</span>
            </div>
            <Progress value={impl.activityCompletionPercent} className="h-3" />
            <div className="flex justify-between mt-2 text-xs text-gray-500">
              <span>{impl.completedActivities} {t.completed}</span>
              <span>{impl.totalActivities} {t.activities}</span>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm font-medium">{t.indicatorAchievement}</span>
              <span className="text-sm font-bold">{impl.indicatorAchievementPercent}%</span>
            </div>
            <Progress value={impl.indicatorAchievementPercent} className="h-3" />
            <div className="flex justify-between mt-2 text-xs text-gray-500">
              <span>{impl.achievedIndicators} {t.achieved}</span>
              <span>{impl.totalIndicators} {t.indicators}</span>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm font-medium">{t.taskCompletion}</span>
              <span className="text-sm font-bold">{impl.taskCompletionPercent}%</span>
            </div>
            <Progress value={impl.taskCompletionPercent} className="h-3" />
            <div className="flex justify-between mt-2 text-xs text-gray-500">
              <span>{impl.completedTasks} {t.completed}</span>
              <span>{impl.totalTasks} {t.tasks}</span>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Detailed Metrics */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <StatCard label={t.delayed} value={impl.delayedActivities} color="orange" />
        <StatCard label={t.offTrack} value={impl.offTrackIndicators} color="red" />
        <StatCard label={`${t.overdue} ${t.tasks}`} value={impl.overdueTasks} color="red" />
        <StatCard
          label={t.completed}
          value={impl.completedActivities + impl.completedTasks}
          color="green"
        />
      </div>
    </>
  );
}

// Risk & Compliance Tab
function RiskComplianceTab({ data, t, isRTL }: { data: any; t: any; isRTL: boolean }) {
  const risk = data.riskCompliance;

  return (
    <>
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
        <StatCard label={t.totalRisks} value={risk.totalRisks} color="gray" />
        <StatCard label={t.highRisks} value={risk.highRisks} color="orange" />
        <StatCard label={t.criticalRisks} value={risk.criticalRisks} color="red" />
        <StatCard label={t.unresolvedRisks} value={risk.unresolvedRisks} color="yellow" />
        <StatCard label={t.overdueReports} value={risk.overdueReports} color="red" />
        <StatCard label={t.scheduledReports} value={risk.totalScheduledReports} color="blue" />
      </div>

      {/* Compliance Score */}
      <Card>
        <CardContent className="p-6">
          <div className="flex items-center justify-between mb-4">
            <span className="text-lg font-semibold">{t.complianceScore}</span>
            <span className={`text-3xl font-bold ${
              risk.complianceScore >= 80 ? 'text-green-600' :
              risk.complianceScore >= 60 ? 'text-yellow-600' : 'text-red-600'
            }`}>
              {risk.complianceScore}%
            </span>
          </div>
          <Progress
            value={risk.complianceScore}
            className={`h-4 ${
              risk.complianceScore >= 80 ? '[&>div]:bg-green-500' :
              risk.complianceScore >= 60 ? '[&>div]:bg-yellow-500' : '[&>div]:bg-red-500'
            }`}
          />
        </CardContent>
      </Card>
    </>
  );
}

// Beneficiary Analytics Tab
function BeneficiaryTab({ data, t, language, isRTL }: { data: any; t: any; language: string; isRTL: boolean }) {
  const ben = data.beneficiaryAnalytics;

  const genderData = [
    { name: t.male, value: ben.male, color: '#3b82f6' },
    { name: t.female, value: ben.female, color: '#ec4899' },
  ];

  return (
    <>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <StatCard label={t.totalReached} value={formatNumber(ben.totalReached)} color="blue" />
        <StatCard label={t.male} value={formatNumber(ben.male)} color="blue" />
        <StatCard label={t.female} value={formatNumber(ben.female)} color="pink" />
        <StatCard label={t.vulnerableGroups} value={formatNumber(ben.vulnerableGroups)} color="purple" />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Gender Distribution */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">{t.male} / {t.female}</CardTitle>
          </CardHeader>
          <CardContent>
            {ben.totalReached > 0 ? (
              <ResponsiveContainer width="100%" height={220}>
                <PieChart>
                  <Pie
                    data={genderData}
                    cx="50%"
                    cy="50%"
                    innerRadius={50}
                    outerRadius={80}
                    fill="#8884d8"
                    dataKey="value"
                    label={(entry) => `${entry.name}: ${entry.value}`}
                  >
                    {genderData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
            ) : (
              <EmptyChart message={t.noData} />
            )}
          </CardContent>
        </Card>

        {/* Age Groups */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">{t.ageGroups}</CardTitle>
          </CardHeader>
          <CardContent>
            {ben.ageGroups.length > 0 ? (
              <ResponsiveContainer width="100%" height={220}>
                <BarChart data={ben.ageGroups}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="group" />
                  <YAxis />
                  <Tooltip />
                  <Bar dataKey="count" fill="#8b5cf6" />
                </BarChart>
              </ResponsiveContainer>
            ) : (
              <EmptyChart message={t.noData} />
            )}
          </CardContent>
        </Card>
      </div>

      {/* Community Types */}
      {ben.communityTypes.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="text-base">{t.communityTypes}</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              {ben.communityTypes.map((ct: any, i: number) => (
                <div key={i} className="bg-gray-50 rounded-lg p-3 text-center">
                  <p className="text-xs text-gray-500">{ct.type}</p>
                  <p className="text-lg font-bold text-gray-900">{formatNumber(ct.count)}</p>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}
    </>
  );
}

// Project Health Table
function ProjectHealthTable({ data, t, language, isRTL }: { data: any[]; t: any; language: string; isRTL: boolean }) {
  if (data.length === 0) return <EmptyChart message={t.noData} />;

  return (
    <div className="overflow-x-auto">
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b border-gray-200">
            <th className="text-start py-3 px-2 font-medium text-gray-600">{t.project}</th>
            <th className="text-start py-3 px-2 font-medium text-gray-600">{t.status}</th>
            <th className="text-start py-3 px-2 font-medium text-gray-600">{t.health}</th>
            <th className="text-start py-3 px-2 font-medium text-gray-600">{t.score}</th>
            <th className="text-start py-3 px-2 font-medium text-gray-600">{t.budget}</th>
            <th className="text-start py-3 px-2 font-medium text-gray-600">{t.spent}</th>
            <th className="text-start py-3 px-2 font-medium text-gray-600">{t.utilization}</th>
          </tr>
        </thead>
        <tbody>
          {data.map((project: any) => {
            const util = project.totalBudget > 0
              ? Math.round((project.totalSpent / project.totalBudget) * 100)
              : 0;

            return (
              <tr key={project.projectId} className="border-b border-gray-100 hover:bg-gray-50">
                <td className="py-3 px-2 font-medium text-gray-900 max-w-[200px] truncate">
                  {project.projectName}
                </td>
                <td className="py-3 px-2">
                  <Badge variant="secondary" className="capitalize text-xs">
                    {project.status}
                  </Badge>
                </td>
                <td className="py-3 px-2">
                  <Badge
                    variant="outline"
                    className="text-xs"
                    style={{
                      borderColor: HEALTH_COLORS[project.healthStatus],
                      color: HEALTH_COLORS[project.healthStatus],
                    }}
                  >
                    {project.healthStatus}
                  </Badge>
                </td>
                <td className="py-3 px-2">
                  <span className={`font-bold ${
                    project.healthScore >= 75 ? 'text-green-600' :
                    project.healthScore >= 55 ? 'text-yellow-600' :
                    project.healthScore >= 35 ? 'text-orange-600' : 'text-red-600'
                  }`}>
                    {project.healthScore}
                  </span>
                </td>
                <td className="py-3 px-2 ltr-safe">
                  {formatCurrency(project.totalBudget, 'USD')}
                </td>
                <td className="py-3 px-2 ltr-safe">
                  {formatCurrency(project.totalSpent, 'USD')}
                </td>
                <td className="py-3 px-2">
                  <div className="flex items-center gap-2">
                    <Progress value={util} className="h-2 w-16" />
                    <span className="text-xs text-gray-600">{util}%</span>
                  </div>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

// ============================================================
// SHARED HELPER COMPONENTS
// ============================================================

function StatCard({ label, value, color }: { label: string; value: string | number; color: string }) {
  const colorClasses: Record<string, string> = {
    blue: 'bg-blue-50 border-blue-200',
    green: 'bg-green-50 border-green-200',
    red: 'bg-red-50 border-red-200',
    orange: 'bg-orange-50 border-orange-200',
    yellow: 'bg-yellow-50 border-yellow-200',
    purple: 'bg-purple-50 border-purple-200',
    pink: 'bg-pink-50 border-pink-200',
    cyan: 'bg-cyan-50 border-cyan-200',
    gray: 'bg-gray-50 border-gray-200',
  };

  return (
    <div className={`rounded-lg border p-4 text-center ${colorClasses[color] || colorClasses.gray}`}>
      <p className="text-xs text-gray-600 mb-1">{label}</p>
      <p className="text-xl font-bold text-gray-900 ltr-safe">{value}</p>
    </div>
  );
}

function MetricRow({ label, value, color }: { label: string; value: string | number; color?: string }) {
  const colorClass = color === 'red' ? 'text-red-600' :
    color === 'orange' ? 'text-orange-600' :
    color === 'yellow' ? 'text-yellow-600' : 'text-gray-900';

  return (
    <div className="flex items-center justify-between py-1.5">
      <span className="text-sm text-gray-600">{label}</span>
      <span className={`text-sm font-semibold ltr-safe ${colorClass}`}>{value}</span>
    </div>
  );
}

function EmptyChart({ message }: { message: string }) {
  return (
    <div className="h-[220px] flex items-center justify-center bg-gray-50 rounded-lg border border-gray-200">
      <span className="text-gray-400 text-sm">{message}</span>
    </div>
  );
}
