import mysql from 'mysql2/promise';

const conn = await mysql.createConnection(process.env.DATABASE_URL);

console.log('=== CREATING LOGISTICS/PROCUREMENT MODULE TABLES ===');
console.log('SAFETY: Only CREATE TABLE IF NOT EXISTS - no DROP statements');

const logisticsTables = [
  {
    name: 'suppliers',
    sql: `CREATE TABLE IF NOT EXISTS suppliers (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      supplierCode VARCHAR(50) NOT NULL,
      name VARCHAR(255) NOT NULL,
      nameAr VARCHAR(255) NULL,
      contactPerson VARCHAR(255) NULL,
      email VARCHAR(320) NULL,
      phone VARCHAR(50) NULL,
      address TEXT NULL,
      city VARCHAR(100) NULL,
      country VARCHAR(100) NULL,
      taxNumber VARCHAR(100) NULL,
      bankName VARCHAR(255) NULL,
      bankAccountNumber VARCHAR(100) NULL,
      bankIban VARCHAR(50) NULL,
      category ENUM('goods', 'services', 'both') DEFAULT 'goods',
      status ENUM('active', 'inactive', 'blacklisted') DEFAULT 'active' NOT NULL,
      rating INT(11) NULL,
      notes TEXT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  },
  {
    name: 'purchase_requests',
    sql: `CREATE TABLE IF NOT EXISTS purchase_requests (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      operatingUnitId INT(11) NULL,
      requestNumber VARCHAR(50) NOT NULL,
      title VARCHAR(255) NOT NULL,
      titleAr VARCHAR(255) NULL,
      description TEXT NULL,
      descriptionAr TEXT NULL,
      requestDate DATE NOT NULL,
      requiredDate DATE NULL,
      requesterId INT(11) NOT NULL,
      department VARCHAR(100) NULL,
      projectId INT(11) NULL,
      grantId INT(11) NULL,
      budgetLineId INT(11) NULL,
      totalAmount DECIMAL(15,2) DEFAULT 0,
      currency VARCHAR(10) DEFAULT 'USD',
      priority ENUM('low', 'medium', 'high', 'urgent') DEFAULT 'medium',
      status ENUM('draft', 'pending', 'approved', 'rejected', 'cancelled', 'ordered') DEFAULT 'draft' NOT NULL,
      approvedBy INT(11) NULL,
      approvedAt TIMESTAMP NULL,
      rejectionReason TEXT NULL,
      attachmentUrl TEXT NULL,
      notes TEXT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  },
  {
    name: 'purchase_request_line_items',
    sql: `CREATE TABLE IF NOT EXISTS purchase_request_line_items (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      purchaseRequestId INT(11) NOT NULL,
      itemNumber INT(11) NOT NULL,
      description VARCHAR(500) NOT NULL,
      descriptionAr VARCHAR(500) NULL,
      quantity DECIMAL(15,3) NOT NULL,
      unit VARCHAR(50) NULL,
      estimatedUnitPrice DECIMAL(15,2) NULL,
      estimatedTotalPrice DECIMAL(15,2) NULL,
      currency VARCHAR(10) DEFAULT 'USD',
      specifications TEXT NULL,
      notes TEXT NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
    )`
  },
  {
    name: 'purchase_orders',
    sql: `CREATE TABLE IF NOT EXISTS purchase_orders (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      operatingUnitId INT(11) NULL,
      orderNumber VARCHAR(50) NOT NULL,
      purchaseRequestId INT(11) NULL,
      supplierId INT(11) NOT NULL,
      title VARCHAR(255) NOT NULL,
      titleAr VARCHAR(255) NULL,
      orderDate DATE NOT NULL,
      expectedDeliveryDate DATE NULL,
      actualDeliveryDate DATE NULL,
      projectId INT(11) NULL,
      grantId INT(11) NULL,
      budgetLineId INT(11) NULL,
      subtotal DECIMAL(15,2) DEFAULT 0,
      taxAmount DECIMAL(15,2) DEFAULT 0,
      discountAmount DECIMAL(15,2) DEFAULT 0,
      totalAmount DECIMAL(15,2) DEFAULT 0,
      currency VARCHAR(10) DEFAULT 'USD',
      paymentTerms VARCHAR(255) NULL,
      deliveryTerms VARCHAR(255) NULL,
      status ENUM('draft', 'pending', 'approved', 'sent', 'partially_received', 'received', 'cancelled', 'closed') DEFAULT 'draft' NOT NULL,
      approvedBy INT(11) NULL,
      approvedAt TIMESTAMP NULL,
      attachmentUrl TEXT NULL,
      notes TEXT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  },
  {
    name: 'purchase_order_line_items',
    sql: `CREATE TABLE IF NOT EXISTS purchase_order_line_items (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      purchaseOrderId INT(11) NOT NULL,
      itemNumber INT(11) NOT NULL,
      description VARCHAR(500) NOT NULL,
      descriptionAr VARCHAR(500) NULL,
      quantity DECIMAL(15,3) NOT NULL,
      receivedQuantity DECIMAL(15,3) DEFAULT 0,
      unit VARCHAR(50) NULL,
      unitPrice DECIMAL(15,2) NOT NULL,
      totalPrice DECIMAL(15,2) NOT NULL,
      currency VARCHAR(10) DEFAULT 'USD',
      taxRate DECIMAL(5,2) DEFAULT 0,
      taxAmount DECIMAL(15,2) DEFAULT 0,
      specifications TEXT NULL,
      notes TEXT NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
    )`
  },
  {
    name: 'goods_receipt_notes',
    sql: `CREATE TABLE IF NOT EXISTS goods_receipt_notes (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      operatingUnitId INT(11) NULL,
      grnNumber VARCHAR(50) NOT NULL,
      purchaseOrderId INT(11) NOT NULL,
      supplierId INT(11) NOT NULL,
      receiptDate DATE NOT NULL,
      deliveryNoteNumber VARCHAR(100) NULL,
      receivedBy INT(11) NOT NULL,
      inspectedBy INT(11) NULL,
      warehouseLocation VARCHAR(255) NULL,
      status ENUM('draft', 'pending_inspection', 'approved', 'rejected', 'partially_accepted') DEFAULT 'draft' NOT NULL,
      notes TEXT NULL,
      attachmentUrl TEXT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  },
  {
    name: 'grn_line_items',
    sql: `CREATE TABLE IF NOT EXISTS grn_line_items (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      grnId INT(11) NOT NULL,
      poLineItemId INT(11) NOT NULL,
      orderedQuantity DECIMAL(15,3) NOT NULL,
      receivedQuantity DECIMAL(15,3) NOT NULL,
      acceptedQuantity DECIMAL(15,3) DEFAULT 0,
      rejectedQuantity DECIMAL(15,3) DEFAULT 0,
      unit VARCHAR(50) NULL,
      condition ENUM('good', 'damaged', 'defective', 'expired') DEFAULT 'good',
      inspectionNotes TEXT NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
    )`
  },
  {
    name: 'quotation_analyses',
    sql: `CREATE TABLE IF NOT EXISTS quotation_analyses (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      purchaseRequestId INT(11) NOT NULL,
      analysisNumber VARCHAR(50) NOT NULL,
      analysisDate DATE NOT NULL,
      minimumQuotations INT(11) DEFAULT 3,
      status ENUM('draft', 'in_progress', 'completed', 'cancelled') DEFAULT 'draft' NOT NULL,
      selectedSupplierId INT(11) NULL,
      selectionReason TEXT NULL,
      approvedBy INT(11) NULL,
      approvedAt TIMESTAMP NULL,
      notes TEXT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  },
  {
    name: 'quotation_analysis_suppliers',
    sql: `CREATE TABLE IF NOT EXISTS quotation_analysis_suppliers (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      quotationAnalysisId INT(11) NOT NULL,
      supplierId INT(11) NOT NULL,
      quotationNumber VARCHAR(100) NULL,
      quotationDate DATE NULL,
      validUntil DATE NULL,
      totalAmount DECIMAL(15,2) NULL,
      currency VARCHAR(10) DEFAULT 'USD',
      deliveryDays INT(11) NULL,
      paymentTerms VARCHAR(255) NULL,
      technicalScore DECIMAL(5,2) NULL,
      financialScore DECIMAL(5,2) NULL,
      overallScore DECIMAL(5,2) NULL,
      isSelected TINYINT(1) DEFAULT 0,
      notes TEXT NULL,
      attachmentUrl TEXT NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
    )`
  },
  {
    name: 'procurement_payments',
    sql: `CREATE TABLE IF NOT EXISTS procurement_payments (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      operatingUnitId INT(11) NULL,
      paymentNumber VARCHAR(50) NOT NULL,
      purchaseOrderId INT(11) NOT NULL,
      supplierId INT(11) NOT NULL,
      invoiceNumber VARCHAR(100) NULL,
      invoiceDate DATE NULL,
      paymentDate DATE NOT NULL,
      amount DECIMAL(15,2) NOT NULL,
      currency VARCHAR(10) DEFAULT 'USD',
      paymentMethod ENUM('bank_transfer', 'check', 'cash', 'credit_card') NOT NULL,
      bankAccountId INT(11) NULL,
      referenceNumber VARCHAR(100) NULL,
      status ENUM('pending', 'approved', 'paid', 'cancelled') DEFAULT 'pending' NOT NULL,
      approvedBy INT(11) NULL,
      approvedAt TIMESTAMP NULL,
      notes TEXT NULL,
      attachmentUrl TEXT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  },
  {
    name: 'procurement_plan',
    sql: `CREATE TABLE IF NOT EXISTS procurement_plan (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      operatingUnitId INT(11) NULL,
      planNumber VARCHAR(50) NOT NULL,
      title VARCHAR(255) NOT NULL,
      titleAr VARCHAR(255) NULL,
      fiscalYear INT(11) NOT NULL,
      projectId INT(11) NULL,
      grantId INT(11) NULL,
      totalBudget DECIMAL(15,2) DEFAULT 0,
      currency VARCHAR(10) DEFAULT 'USD',
      status ENUM('draft', 'approved', 'in_progress', 'completed') DEFAULT 'draft' NOT NULL,
      approvedBy INT(11) NULL,
      approvedAt TIMESTAMP NULL,
      notes TEXT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  },
  {
    name: 'stock_items',
    sql: `CREATE TABLE IF NOT EXISTS stock_items (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      operatingUnitId INT(11) NULL,
      itemCode VARCHAR(50) NOT NULL,
      name VARCHAR(255) NOT NULL,
      nameAr VARCHAR(255) NULL,
      description TEXT NULL,
      category VARCHAR(100) NULL,
      unit VARCHAR(50) NULL,
      currentQuantity DECIMAL(15,3) DEFAULT 0,
      minimumQuantity DECIMAL(15,3) DEFAULT 0,
      maximumQuantity DECIMAL(15,3) NULL,
      reorderLevel DECIMAL(15,3) NULL,
      unitCost DECIMAL(15,2) NULL,
      currency VARCHAR(10) DEFAULT 'USD',
      location VARCHAR(255) NULL,
      expiryDate DATE NULL,
      status ENUM('active', 'inactive', 'discontinued') DEFAULT 'active' NOT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  },
  {
    name: 'stock_requests',
    sql: `CREATE TABLE IF NOT EXISTS stock_requests (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      operatingUnitId INT(11) NULL,
      requestNumber VARCHAR(50) NOT NULL,
      requestDate DATE NOT NULL,
      requesterId INT(11) NOT NULL,
      department VARCHAR(100) NULL,
      projectId INT(11) NULL,
      purpose TEXT NULL,
      status ENUM('draft', 'pending', 'approved', 'rejected', 'issued', 'cancelled') DEFAULT 'draft' NOT NULL,
      approvedBy INT(11) NULL,
      approvedAt TIMESTAMP NULL,
      rejectionReason TEXT NULL,
      notes TEXT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  },
  {
    name: 'stock_request_line_items',
    sql: `CREATE TABLE IF NOT EXISTS stock_request_line_items (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      stockRequestId INT(11) NOT NULL,
      stockItemId INT(11) NOT NULL,
      requestedQuantity DECIMAL(15,3) NOT NULL,
      approvedQuantity DECIMAL(15,3) NULL,
      issuedQuantity DECIMAL(15,3) DEFAULT 0,
      unit VARCHAR(50) NULL,
      notes TEXT NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
    )`
  },
  {
    name: 'stock_issued',
    sql: `CREATE TABLE IF NOT EXISTS stock_issued (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      operatingUnitId INT(11) NULL,
      issueNumber VARCHAR(50) NOT NULL,
      stockRequestId INT(11) NULL,
      issueDate DATE NOT NULL,
      issuedTo INT(11) NOT NULL,
      issuedBy INT(11) NOT NULL,
      department VARCHAR(100) NULL,
      projectId INT(11) NULL,
      status ENUM('draft', 'issued', 'cancelled') DEFAULT 'draft' NOT NULL,
      notes TEXT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  },
  {
    name: 'stock_issued_line_items',
    sql: `CREATE TABLE IF NOT EXISTS stock_issued_line_items (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      stockIssuedId INT(11) NOT NULL,
      stockItemId INT(11) NOT NULL,
      quantity DECIMAL(15,3) NOT NULL,
      unit VARCHAR(50) NULL,
      unitCost DECIMAL(15,2) NULL,
      totalCost DECIMAL(15,2) NULL,
      notes TEXT NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
    )`
  },
  {
    name: 'returned_items',
    sql: `CREATE TABLE IF NOT EXISTS returned_items (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      operatingUnitId INT(11) NULL,
      returnNumber VARCHAR(50) NOT NULL,
      returnDate DATE NOT NULL,
      returnedBy INT(11) NOT NULL,
      receivedBy INT(11) NULL,
      stockIssuedId INT(11) NULL,
      reason TEXT NULL,
      status ENUM('pending', 'received', 'rejected') DEFAULT 'pending' NOT NULL,
      notes TEXT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  },
  {
    name: 'returned_item_line_items',
    sql: `CREATE TABLE IF NOT EXISTS returned_item_line_items (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      returnedItemId INT(11) NOT NULL,
      stockItemId INT(11) NOT NULL,
      quantity DECIMAL(15,3) NOT NULL,
      condition ENUM('good', 'damaged', 'expired') DEFAULT 'good',
      notes TEXT NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
    )`
  },
  {
    name: 'vehicles',
    sql: `CREATE TABLE IF NOT EXISTS vehicles (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      operatingUnitId INT(11) NULL,
      vehicleCode VARCHAR(50) NOT NULL,
      plateNumber VARCHAR(50) NOT NULL,
      make VARCHAR(100) NULL,
      model VARCHAR(100) NULL,
      year INT(11) NULL,
      color VARCHAR(50) NULL,
      vehicleType ENUM('sedan', 'suv', 'pickup', 'van', 'truck', 'motorcycle', 'other') DEFAULT 'sedan',
      fuelType ENUM('petrol', 'diesel', 'electric', 'hybrid') DEFAULT 'petrol',
      engineNumber VARCHAR(100) NULL,
      chassisNumber VARCHAR(100) NULL,
      purchaseDate DATE NULL,
      purchasePrice DECIMAL(15,2) NULL,
      currentValue DECIMAL(15,2) NULL,
      currency VARCHAR(10) DEFAULT 'USD',
      mileage INT(11) DEFAULT 0,
      fuelCapacity DECIMAL(10,2) NULL,
      status ENUM('active', 'maintenance', 'out_of_service', 'disposed') DEFAULT 'active' NOT NULL,
      assignedDriverId INT(11) NULL,
      projectId INT(11) NULL,
      insuranceExpiryDate DATE NULL,
      registrationExpiryDate DATE NULL,
      photoUrl TEXT NULL,
      notes TEXT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  },
  {
    name: 'drivers',
    sql: `CREATE TABLE IF NOT EXISTS drivers (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      operatingUnitId INT(11) NULL,
      employeeId INT(11) NULL,
      driverCode VARCHAR(50) NOT NULL,
      firstName VARCHAR(100) NOT NULL,
      lastName VARCHAR(100) NOT NULL,
      firstNameAr VARCHAR(100) NULL,
      lastNameAr VARCHAR(100) NULL,
      phone VARCHAR(50) NULL,
      email VARCHAR(320) NULL,
      licenseNumber VARCHAR(100) NOT NULL,
      licenseType VARCHAR(50) NULL,
      licenseExpiryDate DATE NULL,
      status ENUM('active', 'inactive', 'suspended') DEFAULT 'active' NOT NULL,
      photoUrl TEXT NULL,
      notes TEXT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  },
  {
    name: 'vehicle_assignments',
    sql: `CREATE TABLE IF NOT EXISTS vehicle_assignments (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      vehicleId INT(11) NOT NULL,
      driverId INT(11) NULL,
      assignedTo INT(11) NULL,
      assignmentType ENUM('permanent', 'temporary', 'trip') NOT NULL,
      startDate DATE NOT NULL,
      endDate DATE NULL,
      purpose TEXT NULL,
      projectId INT(11) NULL,
      status ENUM('active', 'completed', 'cancelled') DEFAULT 'active' NOT NULL,
      notes TEXT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  },
  {
    name: 'vehicle_maintenance',
    sql: `CREATE TABLE IF NOT EXISTS vehicle_maintenance (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      vehicleId INT(11) NOT NULL,
      maintenanceType ENUM('preventive', 'corrective', 'emergency', 'inspection') NOT NULL,
      description TEXT NOT NULL,
      scheduledDate DATE NULL,
      completedDate DATE NULL,
      mileageAtService INT(11) NULL,
      cost DECIMAL(15,2) NULL,
      currency VARCHAR(10) DEFAULT 'USD',
      vendorName VARCHAR(255) NULL,
      invoiceNumber VARCHAR(100) NULL,
      status ENUM('scheduled', 'in_progress', 'completed', 'cancelled') DEFAULT 'scheduled' NOT NULL,
      nextServiceDate DATE NULL,
      nextServiceMileage INT(11) NULL,
      notes TEXT NULL,
      attachmentUrl TEXT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  },
  {
    name: 'vehicle_compliance',
    sql: `CREATE TABLE IF NOT EXISTS vehicle_compliance (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      vehicleId INT(11) NOT NULL,
      complianceType ENUM('insurance', 'registration', 'inspection', 'permit', 'other') NOT NULL,
      documentNumber VARCHAR(100) NULL,
      issueDate DATE NULL,
      expiryDate DATE NOT NULL,
      renewalCost DECIMAL(15,2) NULL,
      currency VARCHAR(10) DEFAULT 'USD',
      provider VARCHAR(255) NULL,
      status ENUM('valid', 'expiring_soon', 'expired', 'renewed') DEFAULT 'valid' NOT NULL,
      documentUrl TEXT NULL,
      notes TEXT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  },
  {
    name: 'fuel_logs',
    sql: `CREATE TABLE IF NOT EXISTS fuel_logs (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      vehicleId INT(11) NOT NULL,
      driverId INT(11) NULL,
      fuelDate DATE NOT NULL,
      fuelType ENUM('petrol', 'diesel', 'electric') NOT NULL,
      quantity DECIMAL(10,2) NOT NULL,
      unitPrice DECIMAL(10,2) NOT NULL,
      totalCost DECIMAL(15,2) NOT NULL,
      currency VARCHAR(10) DEFAULT 'USD',
      mileage INT(11) NULL,
      fuelStation VARCHAR(255) NULL,
      receiptNumber VARCHAR(100) NULL,
      projectId INT(11) NULL,
      notes TEXT NULL,
      attachmentUrl TEXT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  },
  {
    name: 'trip_logs',
    sql: `CREATE TABLE IF NOT EXISTS trip_logs (
      id INT(11) AUTO_INCREMENT PRIMARY KEY,
      organizationId INT(11) NOT NULL,
      operatingUnitId INT(11) NULL,
      vehicleId INT(11) NOT NULL,
      driverId INT(11) NULL,
      tripNumber VARCHAR(50) NOT NULL,
      tripDate DATE NOT NULL,
      startTime TIMESTAMP NULL,
      endTime TIMESTAMP NULL,
      startLocation VARCHAR(255) NULL,
      endLocation VARCHAR(255) NULL,
      startMileage INT(11) NULL,
      endMileage INT(11) NULL,
      distance INT(11) NULL,
      purpose TEXT NULL,
      passengers TEXT NULL,
      projectId INT(11) NULL,
      status ENUM('planned', 'in_progress', 'completed', 'cancelled') DEFAULT 'planned' NOT NULL,
      notes TEXT NULL,
      isDeleted TINYINT(1) DEFAULT 0 NOT NULL,
      deletedAt TIMESTAMP NULL,
      deletedBy INT(11) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      createdBy INT(11) NULL,
      updatedBy INT(11) NULL
    )`
  }
];

for (const table of logisticsTables) {
  console.log(`Creating ${table.name}...`);
  try {
    await conn.query(table.sql);
    console.log(`  ✅ ${table.name} created`);
  } catch (err) {
    console.log(`  ⚠️ ${table.name} error: ${err.message}`);
  }
}

console.log('\n=== VERIFYING LOGISTICS/PROCUREMENT TABLES ===');
for (const table of logisticsTables) {
  try {
    await conn.query('SELECT 1 FROM `' + table.name + '` LIMIT 1');
    console.log(`  ✅ ${table.name} exists`);
  } catch (e) {
    console.log(`  ❌ ${table.name} does NOT exist`);
  }
}

console.log('\n=== LOGISTICS/PROCUREMENT TABLES MIGRATION COMPLETE ===');
await conn.end();
