#!/usr/bin/env node

/**
 * Production Readiness Validation Script
 * Runs comprehensive checks on translation system before deployment
 * 
 * Usage: npx ts-node scripts/validate-production.ts
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

interface ValidationReport {
  timestamp: string;
  overallStatus: 'PRODUCTION_READY' | 'NEAR_READY' | 'NOT_READY';
  score: number;
  sections: {
    languagePersistence: ValidationSection;
    translationCompleteness: ValidationSection;
    typeSafety: ValidationSection;
    architectureUnification: ValidationSection;
    legacyCleanup: ValidationSection;
  };
  issues: string[];
  summary: string;
}

interface ValidationSection {
  name: string;
  status: 'PASS' | 'WARN' | 'FAIL';
  details: string[];
  score: number;
}

/**
 * Main validation function
 */
async function runValidation(): Promise<ValidationReport> {
  console.log('\n' + '='.repeat(80));
  console.log('PRODUCTION READINESS VALIDATION');
  console.log('='.repeat(80) + '\n');

  const issues: string[] = [];
  const sections: any = {};

  // Check 1: Language Persistence
  console.log('[1/5] Checking Language Persistence...');
  sections.languagePersistence = validateLanguagePersistence(issues);

  // Check 2: Translation Completeness
  console.log('[2/5] Checking Translation Completeness...');
  sections.translationCompleteness = validateTranslationCompleteness(issues);

  // Check 3: Type Safety
  console.log('[3/5] Checking Type Safety...');
  sections.typeSafety = validateTypeSafety(issues);

  // Check 4: Architecture Unification
  console.log('[4/5] Checking Architecture Unification...');
  sections.architectureUnification = validateArchitectureUnification(issues);

  // Check 5: Legacy Cleanup
  console.log('[5/5] Checking Legacy Cleanup...');
  sections.legacyCleanup = validateLegacyCleanup(issues);

  // Calculate overall status
  const scores = Object.values(sections).map((s: any) => s.score);
  const averageScore = scores.reduce((a: number, b: number) => a + b, 0) / scores.length;
  
  let overallStatus: 'PRODUCTION_READY' | 'NEAR_READY' | 'NOT_READY' = 'PRODUCTION_READY';
  if (averageScore < 90) overallStatus = 'NEAR_READY';
  if (averageScore < 75) overallStatus = 'NOT_READY';

  const report: ValidationReport = {
    timestamp: new Date().toISOString(),
    overallStatus,
    score: Math.round(averageScore),
    sections,
    issues,
    summary: generateSummary(sections, issues),
  };

  return report;
}

function validateLanguagePersistence(issues: string[]): ValidationSection {
  const details: string[] = [];

  // Check LanguageContext.tsx
  try {
    const content = readFileSync(resolve('contexts/LanguageContext.tsx'), 'utf-8');
    
    if (content.includes("(stored === 'ar' || stored === 'en' || stored === 'it')")) {
      details.push('✓ Italian added to localStorage check');
    } else {
      issues.push('Italian missing from LanguageContext.tsx initialization');
      details.push('✗ Italian not in persistence check');
    }

    if (content.includes('useTranslationContext')) {
      details.push('✓ LanguageContext derives from TranslationProvider (single source of truth)');
    } else {
      issues.push('LanguageContext does not derive from TranslationProvider');
      details.push('✗ Dual state architecture detected');
    }
  } catch (e) {
    issues.push('Could not read LanguageContext.tsx');
    details.push('✗ File not found');
  }

  return {
    name: 'Language Persistence',
    status: issues.filter(i => i.includes('persistence')).length === 0 ? 'PASS' : 'FAIL',
    details,
    score: issues.filter(i => i.includes('persistence')).length === 0 ? 100 : 50,
  };
}

function validateTranslationCompleteness(issues: string[]): ValidationSection {
  const details: string[] = [];

  try {
    const translationsPath = resolve('lib/translations-trilingual.ts');
    const content = readFileSync(translationsPath, 'utf-8');

    const hasEnglish = content.includes('export const en:');
    const hasArabic = content.includes('export const ar:');
    const hasItalian = content.includes('export const it:');

    if (hasEnglish && hasArabic && hasItalian) {
      details.push('✓ All three languages exported (en, ar, it)');
    } else {
      if (!hasEnglish) issues.push('English translations missing');
      if (!hasArabic) issues.push('Arabic translations missing');
      if (!hasItalian) issues.push('Italian translations missing');
      details.push('✗ Some languages missing');
    }

    // Check for autogenerated keys
    const autogenPattern = /\d+(_|[a-z])*:/g;
    const autogeneratedMatches = content.match(autogenPattern) || [];
    
    if (autogeneratedMatches.length === 0) {
      details.push('✓ No autogenerated keys detected (0 found)');
    } else {
      issues.push(`Autogenerated keys found: ${autogeneratedMatches.length}`);
      details.push(`✗ ${autogeneratedMatches.length} autogenerated keys detected`);
    }

    // Check for empty values
    const emptyPattern = /:\s*['"]?\s*['"]?,/g;
    const emptyMatches = content.match(emptyPattern) || [];
    
    if (emptyMatches.length === 0) {
      details.push('✓ No empty translation values');
    } else {
      issues.push(`Empty translation values found: ${emptyMatches.length}`);
      details.push(`✗ ${emptyMatches.length} empty values`);
    }

  } catch (e) {
    issues.push('Could not validate translations file');
    details.push('✗ translations-trilingual.ts not found');
  }

  const hasIssues = issues.filter(i => i.includes('translations') || i.includes('autogenerated') || i.includes('Empty')).length > 0;
  
  return {
    name: 'Translation Completeness',
    status: hasIssues ? 'FAIL' : 'PASS',
    details,
    score: hasIssues ? 50 : 100,
  };
}

function validateTypeSafety(issues: string[]): ValidationSection {
  const details: string[] = [];

  try {
    const content = readFileSync(resolve('lib/useTranslation.ts'), 'utf-8');

    if (content.includes('ValidTranslationPath')) {
      details.push('✓ Type-safe translation paths imported');
    } else {
      issues.push('ValidTranslationPath type not used');
      details.push('✗ Type safety not enforced');
    }

    if (content.includes('function t<T extends ValidTranslationPath>')) {
      details.push('✓ t() function enforces ValidTranslationPath type');
    } else if (content.includes('function t(keyPath: string)')) {
      issues.push('t() function accepts untyped strings');
      details.push('⚠ t() uses string parameter (runtime-only safety)');
    }

    if (content.includes('function tAny(')) {
      details.push('✓ tAny() available for dynamic keys');
    } else {
      details.push('⚠ tAny() not found (use t() instead)');
    }
  } catch (e) {
    issues.push('Could not validate useTranslation.ts');
    details.push('✗ File not found');
  }

  const typeIssues = issues.filter(i => i.includes('type') || i.includes('Type'));
  
  return {
    name: 'Type Safety',
    status: typeIssues.length > 1 ? 'FAIL' : 'PASS',
    details,
    score: typeIssues.length > 1 ? 60 : 85,
  };
}

function validateArchitectureUnification(issues: string[]): ValidationSection {
  const details: string[] = [];

  try {
    const providerContent = readFileSync(resolve('i18n/TranslationProvider.tsx'), 'utf-8');
    const contextContent = readFileSync(resolve('contexts/LanguageContext.tsx'), 'utf-8');

    // Check if TranslationProvider is the single source
    const providerHasStorage = providerContent.includes('TRANSLATION_STORAGE_KEY');
    const contextDerives = contextContent.includes('useTranslationContext');

    if (providerHasStorage && contextDerives) {
      details.push('✓ TranslationProvider owns language state');
      details.push('✓ LanguageContext derives from TranslationProvider');
      details.push('✓ Single storage key (app_language)');
    } else {
      issues.push('Dual language state detected');
      details.push('✗ Architecture not fully unified');
    }

    // Check for single storage key
    const contextStorage = contextContent.match(/LANGUAGE.*STORAGE/g) || [];
    if (contextStorage.length === 0) {
      details.push('✓ LanguageContext does not maintain its own storage');
    } else {
      issues.push('LanguageContext maintains separate storage');
      details.push('✗ Dual storage keys detected');
    }
  } catch (e) {
    issues.push('Could not validate architecture');
    details.push('✗ Files not found');
  }

  const archIssues = issues.filter(i => i.includes('architecture') || i.includes('storage') || i.includes('dual'));
  
  return {
    name: 'Architecture Unification',
    status: archIssues.length > 0 ? 'WARN' : 'PASS',
    details,
    score: archIssues.length > 0 ? 70 : 100,
  };
}

function validateLegacyCleanup(issues: string[]): ValidationSection {
  const details: string[] = [];

  try {
    const legacyContent = readFileSync(resolve('components/LanguageSwitcher.tsx'), 'utf-8');

    if (legacyContent.includes('DEPRECATED') || legacyContent.includes('AdvancedLanguageSwitcher')) {
      details.push('✓ LanguageSwitcher marked as deprecated/aliased');
      details.push('✓ No duplicate implementation');
    } else if (legacyContent.includes('useLanguage')) {
      issues.push('Legacy LanguageSwitcher still uses old implementation');
      details.push('✗ Legacy switcher not retired');
    } else {
      details.push('✓ LanguageSwitcher properly updated');
    }

    // Check if AdvancedLanguageSwitcher exists
    try {
      const advContent = readFileSync(resolve('components/AdvancedLanguageSwitcher.tsx'), 'utf-8');
      if (advContent.includes('useLanguageSelector')) {
        details.push('✓ AdvancedLanguageSwitcher uses TranslationProvider');
      }
    } catch (e) {
      issues.push('AdvancedLanguageSwitcher not found');
      details.push('✗ AdvancedLanguageSwitcher missing');
    }
  } catch (e) {
    issues.push('Could not validate legacy cleanup');
    details.push('✗ LanguageSwitcher.tsx not found');
  }

  const legacyIssues = issues.filter(i => i.includes('Legacy') || i.includes('deprecated') || i.includes('duplicate'));
  
  return {
    name: 'Legacy Cleanup',
    status: legacyIssues.length > 0 ? 'WARN' : 'PASS',
    details,
    score: legacyIssues.length > 0 ? 75 : 100,
  };
}

function generateSummary(sections: any, issues: string[]): string {
  const scores = Object.values(sections).map((s: any) => s.score);
  const avgScore = Math.round(scores.reduce((a: number, b: number) => a + b, 0) / scores.length);

  if (issues.length === 0) {
    return `All checks passed! System is production ready. Average score: ${avgScore}/100`;
  } else {
    return `${issues.length} issue(s) found. Review details above. Average score: ${avgScore}/100`;
  }
}

/**
 * Print report to console
 */
function printReport(report: ValidationReport): void {
  console.log('\n' + '='.repeat(80));
  console.log('VALIDATION RESULTS');
  console.log('='.repeat(80));

  console.log(`\nOverall Status: ${report.overallStatus}`);
  console.log(`Average Score: ${report.score}/100\n`);

  Object.entries(report.sections).forEach(([key, section]: [string, any]) => {
    const emoji = section.status === 'PASS' ? '✓' : section.status === 'WARN' ? '⚠' : '✗';
    console.log(`${emoji} ${section.name} (${section.score}/100)`);
    section.details.forEach((detail: string) => console.log(`  ${detail}`));
  });

  if (report.issues.length > 0) {
    console.log('\n' + '-'.repeat(80));
    console.log('ISSUES FOUND:');
    report.issues.forEach((issue, i) => {
      console.log(`  ${i + 1}. ${issue}`);
    });
  }

  console.log('\n' + '-'.repeat(80));
  console.log('SUMMARY: ' + report.summary);
  console.log('='.repeat(80) + '\n');

  // Save report to file
  const reportPath = resolve('validation-report.json');
  writeFileSync(reportPath, JSON.stringify(report, null, 2));
  console.log(`Report saved to: ${reportPath}\n`);
}

// Run validation
runValidation()
  .then((report) => {
    printReport(report);
    process.exit(report.overallStatus === 'PRODUCTION_READY' ? 0 : 1);
  })
  .catch((error) => {
    console.error('Validation failed:', error);
    process.exit(1);
  });
