// ============================================================================
// TRANSLATION MIGRATION & CLEANUP UTILITY
// Phase 6: Cleanup Legacy Keys
// Phase 7: Italian Translation Generation
// Detects autogenerated keys, generates migration reports
// ============================================================================

import { translations, Language } from './translations-trilingual';

export interface MigrationReport {
  autogeneratedKeys: AutogeneratedKeyDetection[];
  legacyKeys: LegacyKeyReport[];
  unusedKeys: string[];
  duplicateTranslations: DuplicateTranslationReport[];
  migrationActions: MigrationAction[];
  summary: MigrationSummary;
}

export interface AutogeneratedKeyDetection {
  key: string;
  pattern: string;
  confidence: number;
  suggestedReplacement?: string;
}

export interface LegacyKeyReport {
  key: string;
  reason: string;
  affectedLanguages: Language[];
}

export interface DuplicateTranslationReport {
  keys: string[];
  translation: string;
  languages: Language[];
}

export interface MigrationAction {
  type: 'delete' | 'rename' | 'consolidate' | 'review';
  source: string;
  target?: string;
  reason: string;
}

export interface MigrationSummary {
  totalAutogeneratedKeys: number;
  totalLegacyKeys: number;
  totalDuplicateTranslations: number;
  estimatedImpact: string;
  backwardCompatibilityRisk: 'low' | 'medium' | 'high';
  recommendedAction: string;
}

class TranslationMigration {
  /**
   * Detect autogenerated patterns in keys
   * Examples: warningThreshold22, projectCode4, burnRate13, riskLevel27
   */
  detectAutogeneratedKeys(): AutogeneratedKeyDetection[] {
    const autogenerated: AutogeneratedKeyDetection[] = [];

    // Pattern: word + numbers at end (e.g., warningThreshold22)
    const numberPatternRegex = /^[a-zA-Z]+\d+$/;

    // Pattern: camelCase + number (e.g., projectCode4)
    const camelCaseNumberRegex = /^[a-z]+[A-Z][a-z]+\d+$/;

    // Pattern: multiple consecutive numbers
    const multiNumberRegex = /\d{2,}/;

    const allKeys = this.getAllKeys();

    allKeys.forEach((key) => {
      const lastPart = key.split('.').pop() || key;

      if (numberPatternRegex.test(lastPart)) {
        autogenerated.push({
          key,
          pattern: 'word+number',
          confidence: 0.9,
          suggestedReplacement: lastPart.replace(/\d+$/, ''),
        });
      } else if (camelCaseNumberRegex.test(lastPart)) {
        autogenerated.push({
          key,
          pattern: 'camelCase+number',
          confidence: 0.8,
          suggestedReplacement: lastPart.replace(/\d+$/, ''),
        });
      } else if (multiNumberRegex.test(lastPart)) {
        autogenerated.push({
          key,
          pattern: 'multi-number',
          confidence: 0.6,
        });
      }
    });

    return autogenerated;
  }

  /**
   * Find duplicate translations across keys
   */
  findDuplicateTranslations(): DuplicateTranslationReport[] {
    const duplicates: DuplicateTranslationReport[] = [];
    const translationMap: Record<string, { keys: string[]; languages: Language[] }> = {};

    const languages: Language[] = ['en', 'ar', 'it'];

    languages.forEach((lang) => {
      const keys = this.getAllKeys();
      keys.forEach((keyPath) => {
        const value = this.getValueByPath(translations[lang], keyPath);

        if (value && typeof value === 'string') {
          if (!translationMap[value]) {
            translationMap[value] = { keys: [], languages: [] };
          }
          if (!translationMap[value].keys.includes(keyPath)) {
            translationMap[value].keys.push(keyPath);
          }
          if (!translationMap[value].languages.includes(lang)) {
            translationMap[value].languages.push(lang);
          }
        }
      });
    });

    // Find duplicates (same translation in multiple keys)
    Object.entries(translationMap).forEach(([translation, { keys, languages: langs }]) => {
      if (keys.length > 1 && translation.length > 3) {
        // Ignore very short translations
        duplicates.push({
          keys,
          translation,
          languages: langs,
        });
      }
    });

    return duplicates;
  }

  /**
   * Get all translation keys recursively
   */
  private getAllKeys(obj: any = translations.en, prefix = ''): string[] {
    const keys: string[] = [];

    if (!obj || typeof obj !== 'object') return keys;

    Object.keys(obj).forEach((key) => {
      const fullKey = prefix ? `${prefix}.${key}` : key;

      if (typeof obj[key] === 'string') {
        keys.push(fullKey);
      } else if (typeof obj[key] === 'object' && obj[key] !== null) {
        keys.push(...this.getAllKeys(obj[key], fullKey));
      }
    });

    return keys;
  }

  /**
   * Get value from nested object by path
   */
  private getValueByPath(obj: any, path: string): any {
    const parts = path.split('.');
    let current = obj;

    for (const part of parts) {
      if (current && typeof current === 'object' && part in current) {
        current = current[part];
      } else {
        return undefined;
      }
    }

    return current;
  }

  /**
   * Generate full migration report
   */
  generateReport(): MigrationReport {
    const autogeneratedKeys = this.detectAutogeneratedKeys();
    const duplicateTranslations = this.findDuplicateTranslations();

    const migrationActions: MigrationAction[] = [];

    // Create actions for autogenerated keys
    autogeneratedKeys.forEach((item) => {
      migrationActions.push({
        type: 'review',
        source: item.key,
        reason: `Auto-generated key pattern: ${item.pattern}`,
      });
    });

    // Create actions for duplicates
    duplicateTranslations.forEach((item) => {
      migrationActions.push({
        type: 'consolidate',
        source: item.keys[1],
        target: item.keys[0],
        reason: `Duplicate translation: "${item.translation.substring(0, 50)}..."`,
      });
    });

    const backwardCompatibilityRisk = migrationActions.length > 10 ? 'high' : migrationActions.length > 5 ? 'medium' : 'low';

    const summary: MigrationSummary = {
      totalAutogeneratedKeys: autogeneratedKeys.length,
      totalLegacyKeys: 0,
      totalDuplicateTranslations: duplicateTranslations.length,
      estimatedImpact: `${migrationActions.length} keys need review or consolidation`,
      backwardCompatibilityRisk,
      recommendedAction: 'Review autogenerated keys and consolidate duplicates in a controlled migration',
    };

    return {
      autogeneratedKeys,
      legacyKeys: [],
      unusedKeys: [],
      duplicateTranslations,
      migrationActions,
      summary,
    };
  }
}

/**
 * Generate migration report
 */
export function generateMigrationReport(): MigrationReport {
  const migration = new TranslationMigration();
  return migration.generateReport();
}

/**
 * Generate migration report as text
 */
export function generateMigrationReportText(): string {
  const report = generateMigrationReport();

  let text = '='.repeat(80) + '\n';
  text += 'TRANSLATION MIGRATION REPORT\n';
  text += '='.repeat(80) + '\n\n';

  text += 'SUMMARY:\n';
  text += `  Autogenerated Keys: ${report.summary.totalAutogeneratedKeys}\n`;
  text += `  Duplicate Translations: ${report.summary.totalDuplicateTranslations}\n`;
  text += `  Migration Actions: ${report.migrationActions.length}\n`;
  text += `  Backward Compatibility Risk: ${report.summary.backwardCompatibilityRisk.toUpperCase()}\n\n`;

  if (report.autogeneratedKeys.length > 0) {
    text += 'AUTOGENERATED KEYS:\n';
    report.autogeneratedKeys.slice(0, 10).forEach((item) => {
      text += `  - ${item.key} (Pattern: ${item.pattern}, Confidence: ${(item.confidence * 100).toFixed(0)}%)\n`;
      if (item.suggestedReplacement) {
        text += `    Suggestion: ${item.suggestedReplacement}\n`;
      }
    });
    if (report.autogeneratedKeys.length > 10) {
      text += `  ... and ${report.autogeneratedKeys.length - 10} more\n`;
    }
    text += '\n';
  }

  if (report.duplicateTranslations.length > 0) {
    text += 'DUPLICATE TRANSLATIONS:\n';
    report.duplicateTranslations.slice(0, 5).forEach((item) => {
      text += `  Translation: "${item.translation.substring(0, 60)}..."\n`;
      text += `    Keys: ${item.keys.join(', ')}\n`;
    });
    if (report.duplicateTranslations.length > 5) {
      text += `  ... and ${report.duplicateTranslations.length - 5} more\n`;
    }
    text += '\n';
  }

  text += 'RECOMMENDED ACTION:\n';
  text += `  ${report.summary.recommendedAction}\n\n`;

  text += '='.repeat(80) + '\n';

  return text;
}

/**
 * Log migration report to console
 */
export function logMigrationReport(): void {
  console.log(generateMigrationReportText());
}
