/**
 * Purchase Request Import Configuration
 * 
 * SINGLE SOURCE OF TRUTH for all PR export/import operations
 * Used by:
 * - exportTemplate (blank template)
 * - exportData (with data)
 * - import validation (backend)
 * - import processor (grouping & transformation)
 * 
 * CRITICAL: Changes here affect ALL three operations
 */

import { ImportConfig, ColumnDefinition } from '../importFramework';

/**
 * Column definitions for Purchase Request export/import
 * 
 * ARCHITECTURE NOTES:
 * - exportable: Include in export (template & data)
 * - importable: Allow in import (backend processes)
 * - readonly: Cannot be modified during import (exported for reference only)
 * - hidden: Not visible in UI but included in data
 * - default: Default value if empty during import
 */
export const PURCHASE_REQUEST_COLUMNS = [
  // Using 'as const' would narrow types, instead we use explicit typing below
  // ============================================================================
  // PR HEADER INFORMATION (Grouped for clarity)
  // ============================================================================
  
  {
    key: 'importGroupId',
    header: 'Import Group ID',
    headerAr: 'معرّف مجموعة الاستيراد',
    required: false,
    dataType: 'string',
    hidden: true,  // Not visible in UI
    exportable: true,
    importable: true,
    description: 'Groups multiple rows into single PR. Rows with same importGroupId = one PR with multiple line items',
  },
  
  {
    key: 'prNumber',
    header: 'PR Number',
    headerAr: 'رقم طلب الشراء',
    required: false,
    dataType: 'string',
    readonly: true,
    exportable: true,
    importable: false,  // ✅ CRITICAL: Never import PR number
    description: 'Auto-generated by system. Exported for reference only.',
  },
  
  {
    key: 'category',
    header: 'Category',
    headerAr: 'الفئة',
    required: true,
    dataType: 'enum',
    enumValues: ['goods', 'services', 'works'],
    exportable: true,
    importable: true,
  },
  
  {
    key: 'projectTitle',
    header: 'Project Title',
    headerAr: 'عنوان المشروع',
    required: true,
    dataType: 'string',
    exportable: true,
    importable: true,
  },
  
  {
    key: 'donorName',
    header: 'Donor Name',
    headerAr: 'اسم المانح',
    required: false,
    dataType: 'string',
    exportable: true,
    importable: true,
    referenceTable: 'donors',
    description: 'Must exist in donors table',
  },
  
  {
    key: 'budgetCode',
    header: 'Budget Code',
    headerAr: 'رمز الميزانية',
    required: false,
    dataType: 'string',
    exportable: true,
    importable: true,
    referenceTable: 'budgets',
    description: 'Must exist in budgets table',
  },
  
  {
    key: 'budgetTitle',
    header: 'Budget Title',
    headerAr: 'عنوان الميزانية',
    required: false,
    dataType: 'string',
    exportable: true,
    importable: false,  // Read-only, derived from budgetCode
  },
  
  {
    key: 'subBudgetLine',
    header: 'Sub Budget Line',
    headerAr: 'خط الميزانية الفرعي',
    required: false,
    dataType: 'string',
    exportable: true,
    importable: true,
  },
  
  {
    key: 'activityName',
    header: 'Activity Name',
    headerAr: 'اسم النشاط',
    required: false,
    dataType: 'string',
    exportable: true,
    importable: true,
  },
  
  {
    key: 'totalBudgetLine',
    header: 'Total Budget Line',
    headerAr: 'إجمالي خط الميزانية',
    required: false,
    dataType: 'number',
    min: 0,
    exportable: true,
    importable: false,  // Read-only, for reference
  },
  
  {
    key: 'currency',
    header: 'Currency',
    headerAr: 'العملة',
    required: true,
    dataType: 'enum',
    // NOTE: enumValues populated dynamically from finance_currencies table
    // Backend validation queries: SELECT code FROM finance_currencies WHERE isActive = 1
    exportable: true,
    importable: true,
    referenceTable: 'finance_currencies',
    description: 'Must exist in finance_currencies table with isActive=1',
  },
  
  {
    key: 'exchangeRate',
    header: 'Exchange Rate',
    headerAr: 'سعر الصرف',
    required: false,
    dataType: 'number',
    min: 0.000001,
    exportable: true,
    importable: true,
    default: 1.0,
  },
  
  {
    key: 'exchangeTo',
    header: 'Exchange To',
    headerAr: 'الصرف إلى',
    required: false,
    dataType: 'enum',
    // NOTE: enumValues populated dynamically from finance_currencies table
    exportable: true,
    importable: true,
    referenceTable: 'finance_currencies',
    description: 'Must exist in finance_currencies table with isActive=1',
  },
  
  {
    key: 'department',
    header: 'Department',
    headerAr: 'القسم',
    required: false,
    dataType: 'string',
    exportable: true,
    importable: true,
  },
  
  {
    key: 'requesterName',
    header: 'Requester Name',
    headerAr: 'اسم المطلوب',
    required: true,
    dataType: 'string',
    exportable: true,
    importable: true,
  },
  
  {
    key: 'requesterEmail',
    header: 'Requester Email',
    headerAr: 'بريد المطلوب الإلكتروني',
    required: true,
    dataType: 'string',
    pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    exportable: true,
    importable: true,
  },
  
  {
    key: 'neededByDate',
    header: 'Needed By Date',
    headerAr: 'مطلوب بحلول التاريخ',
    required: false,
    dataType: 'date',
    exportable: true,
    importable: true,
  },
  
  {
    key: 'urgency',
    header: 'Urgency',
    headerAr: 'الأولوية',
    required: false,
    dataType: 'enum',
    enumValues: ['low', 'normal', 'high', 'critical'],
    exportable: true,
    importable: true,
    default: 'normal',
  },
  
  {
    key: 'justification',
    header: 'Justification',
    headerAr: 'المبرر',
    required: false,
    dataType: 'string',
    exportable: true,
    importable: true,
  },
  
  {
    key: 'procurementLadder',
    header: 'Procurement Ladder',
    headerAr: 'سلم الشراء',
    required: false,
    dataType: 'enum',
    // NOTE: Use EXACT values from schema.ts purchaseRequests.procurementLadder
    enumValues: ['one_quotation', 'three_quotations', 'public_tender', 'tender'],
    exportable: true,
    importable: true,  // Imported as suggestion only
    description: 'Backend will recalculate authoritative value based on amount & category',
  },
  
  {
    key: 'status',
    header: 'Status',
    headerAr: 'الحالة',
    required: false,
    dataType: 'enum',
    enumValues: ['draft', 'submitted', 'validated_by_logistic', 'rejected_by_logistic', 'validated_by_finance', 'rejected_by_finance', 'approved', 'rejected_by_pm'],
    readonly: true,
    exportable: true,
    importable: false,  // Status set by workflow, not import
  },
  
  {
    key: 'prDate',
    header: 'PR Date',
    headerAr: 'تاريخ طلب الشراء',
    required: false,
    dataType: 'date',
    readonly: true,
    exportable: true,
    importable: false,  // Set by system
  },
  
  // ============================================================================
  // LINE ITEM INFORMATION
  // ============================================================================
  
  {
    key: 'lineNumber',
    header: 'Line #',
    headerAr: 'رقم السطر',
    required: true,
    dataType: 'number',
    min: 1,
    exportable: true,
    importable: true,
    description: 'Sequential line number within PR',
  },
  
  {
    key: 'budgetLine',
    header: 'Budget Line',
    headerAr: 'خط الميزانية',
    required: false,
    dataType: 'string',
    exportable: true,
    importable: true,
  },
  
  {
    key: 'description',
    header: 'Description',
    headerAr: 'الوصف',
    required: true,
    dataType: 'string',
    exportable: true,
    importable: true,
  },
  
  {
    key: 'descriptionAr',
    header: 'Description (AR)',
    headerAr: 'الوصف (AR)',
    required: false,
    dataType: 'string',
    exportable: true,
    importable: true,
    description: 'Arabic description for bilingual support',
  },
  
  {
    key: 'specifications',
    header: 'Specifications',
    headerAr: 'المواصفات',
    required: false,
    dataType: 'string',
    exportable: true,
    importable: true,
  },
  
  {
    key: 'specificationsAr',
    header: 'Specifications (AR)',
    headerAr: 'المواصفات (AR)',
    required: false,
    dataType: 'string',
    exportable: true,
    importable: true,
    description: 'Arabic specifications for bilingual support',
  },
  
  {
    key: 'quantity',
    header: 'Quantity',
    headerAr: 'الكمية',
    required: true,
    dataType: 'number',
    min: 0.01,
    exportable: true,
    importable: true,
  },
  
  {
    key: 'unit',
    header: 'Unit',
    headerAr: 'الوحدة',
    required: true,
    dataType: 'string',
    exportable: true,
    importable: true,
    default: 'Piece',
  },
  
  {
    key: 'unitPrice',
    header: 'Unit Price',
    headerAr: 'سعر الوحدة',
    required: true,
    dataType: 'number',
    min: 0,
    exportable: true,
    importable: true,
  },
  
  {
    key: 'totalPrice',
    header: 'Total Price',
    headerAr: 'السعر الإجمالي',
    required: false,
    dataType: 'number',
    min: 0,
    readonly: true,
    exportable: true,
    importable: false,  // ✅ CRITICAL: Do NOT import totalPrice
    description: 'Calculated as: quantity * unitPrice * recurrence. Backend authoritative.',
  },
  
  {
    key: 'recurrence',
    header: 'Recurrence',
    headerAr: 'التكرار',
    required: false,
    dataType: 'number',
    min: 1,
    max: 1000,
    default: 1,  // ✅ CRITICAL: Default to 1 if empty
    exportable: true,
    importable: true,
    description: 'How many times to repeat this line item. Defaults to 1 if empty.',
  },
];

/**
 * Purchase Request Import Configuration
 * Used by import validation framework
 */
export const PURCHASE_REQUEST_IMPORT_CONFIG: ImportConfig = {
  moduleName: 'Purchase Requests',
  moduleNameAr: 'طلبات الشراء',
  sheetName: 'Purchase Requests',
  sheetNameAr: 'طلبات الشراء',
  columns: PURCHASE_REQUEST_COLUMNS,
  allowDuplicates: false,
  language: 'en',
};

/**
 * Helper function to get exportable columns only
 * Used by exportTemplate and exportData
 */
export function getExportableColumns(): ColumnDefinition[] {
  return (PURCHASE_REQUEST_COLUMNS as ColumnDefinition[]).filter(col => col.exportable !== false);
}

/**
 * Helper function to get importable columns only
 * Used by import processor
 */
export function getImportableColumns(): ColumnDefinition[] {
  return (PURCHASE_REQUEST_COLUMNS as ColumnDefinition[]).filter(col => col.importable !== false);
}

/**
 * Helper function to convert column definitions to ExcelJS format
 * Used by exportTemplate and exportData
 */
export function getExcelJSColumns() {
  return getExportableColumns().map(col => ({
    header: col.header,
    key: col.key,
    width: col.width || 20,
  }));
}

/**
 * Helper function to get column by key
 */
export function getColumnByKey(key: string): ColumnDefinition | undefined {
  return PURCHASE_REQUEST_COLUMNS.find(col => col.key === key);
}

/**
 * Helper function to get default value for a column
 */
export function getDefaultValue(key: string): any {
  const col = getColumnByKey(key);
  return col?.default !== undefined ? col.default : null;
}

/**
 * Helper function to validate if column is readonly
 */
export function isColumnReadonly(key: string): boolean {
  const col = getColumnByKey(key);
  return col?.readonly === true;
}

/**
 * Helper function to validate if column is hidden
 */
export function isColumnHidden(key: string): boolean {
  const col = getColumnByKey(key);
  return col?.hidden === true;
}
